### ISSUE TITLE
Rename symbol feature

### ISSUE THREAD

**Issue by Sh4rK** [DisposaBoy/GoSublime#114]
It would be nice to have a feature to rename symbols (variables, structure fields, functions etc) in a syntax-aware way, and across all files of a package (or even inter-package, but I'm not sure about that).

**Comment by justinfx** [comment]
would love to see this merged. it's been 7 months since the pull request I had made.

**Comment by rafadev7** [comment]
me too...

**Comment by mdwhatcott** [comment]
@DisposaBoy - Thanks for creating a great plugin for go development. I've written so much code with this tool!

Being able to safely rename a variable across an entire project from within the editor is a powerful capability. This PR would be a great addition to GoSublime. Once you've had the ability to rename any token at will in other languages, programming in go feels clunky. The good news: The [go plugin for Intellij](https://github.com/go-lang-plugin-org/go-lang-idea-plugin) already supports this behavior and it's awesome. Just sayin'.

**Comment by justinfx** [comment]
Pretty sure the project is abandoned. What with this pull request being a year old.

**Comment by fulldump** [comment]
A great golang plugin has dead :(
