### ISSUE TITLE
No completion options for initializing struct members

### ISSUE THREAD

**Issue by hobbs** [DisposaBoy/GoSublime#200]
Currently I don't see completion options when initializing struct members by name.

For example:

```
type T struct {
    VarOne int
    VarTwo int
}

t := T{VarTwo: 2}
```

In this example, when typing "VarTwo" in the struct "t" initialization, ST2 does not offer any completion options.

**Comment by dancannon** [comment]
It looks like gocode has been updated, any update on this issue?
