### ISSUE TITLE
Show function arguments in popup

### ISSUE THREAD

**Issue by ghost** [DisposaBoy/GoSublime#212]
Currently popup displays only return values of a function. It would be helpful, if autocompletion could show whole declaration, for example:

Println(...) n int, er error
NewWriter(w io.Writer) *Writer
etc.

**Comment by joncalhoun** [comment]
I realize this is a really old issue, but I can't for the life of me get this to work. Any chance you could help me get full completion with argument types at the very least? 

Background: On Mac OS X and trying both `ctrl+.` then space or `cmd+.` then space doesnt' seem to give me full method definitions. I'm not really sure what I am doing wrong or what to change here. I'll keep digging in the meantime, but help would be awesome :)

**Comment by joncalhoun** [comment]
And I find it 10 minutes after finally posting (I think) - https://github.com/DisposaBoy/GoSublime/blob/master/Default%20(OSX).sublime-keymap#L122

@DisposaBoy Is there any way to make that info available in the popup panel? It sounds like there isn't but I got the impression from your last comment that `"autocomplete_live_hint": true
` would do it, but I don't see anything coming from that with it in my gosublime sublime-settings file. 

Thanks!
