### ISSUE TITLE
MarGo fails with newest version of Go.

### ISSUE THREAD

**Issue by daemonfire300** [DisposaBoy/GoSublime#361]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/go/bin/go', 'build', '-v', '-x', '-o', 'gosublime.margo_r13.08.31-1_go1.1.2.exe', 'gosubli.me/margo']`
|                > stdout: `WORK=/tmp/go-build104457796`
|                > stderr: `../../../../GoSublime/src/gosubli.me/margo/broker.go:4:2: cannot find package "bufio" in any of:
|                >  ~/go/src/pkg/bufio (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/bufio (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/broker.go:5:2: cannot find package "bytes" in any of:
|                >  ~/go/src/pkg/bytes (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/bytes (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/common.go:5:2: cannot find package "encoding/base64" in any of:
|                >  ~/go/src/pkg/encoding/base64 (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/encoding/base64 (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/broker.go:6:2: cannot find package "encoding/json" in any of:
|                >  ~/go/src/pkg/encoding/json (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/encoding/json (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/package.go:5:2: cannot find package "errors" in any of:
|                >  ~/go/src/pkg/errors (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/errors (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/main.go:7:2: cannot find package "flag" in any of:
|                >  ~/go/src/pkg/flag (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/flag (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/common.go:7:2: cannot find package "fmt" in any of:
|                >  ~/go/src/pkg/fmt (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/fmt (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/common.go:8:2: cannot find package "go/ast" in any of:
|                >  ~/go/src/pkg/go/ast (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/go/ast (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/m_play.go:5:2: cannot find package "go/build" in any of:
|                >  ~/go/src/pkg/go/build (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/go/build (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/common.go:9:2: cannot find package "go/parser" in any of:
|                >  ~/go/src/pkg/go/parser (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/go/parser (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/common.go:10:2: cannot find package "go/printer" in any of:
|                >  ~/go/src/pkg/go/printer (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/go/printer (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/m_lint.go:6:2: cannot find package "go/scanner" in any of:
|                >  ~/go/src/pkg/go/scanner (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/go/scanner (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/common.go:11:2: cannot find package "go/token" in any of:
|                >  ~/go/src/pkg/go/token (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/go/token (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/config.go:7:2: cannot find package "io" in any of:
|                >  ~/go/src/pkg/io (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/io (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/autocompletecontext.go:9:2: cannot find package "io/ioutil" in any of:
|                >  ~/go/src/pkg/io/ioutil (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/io/ioutil (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/main.go:10:2: cannot find package "log" in any of:
|                >  ~/go/src/pkg/log (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/log (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/types/const.go:12:2: cannot find package "math/big" in any of:
|                >  ~/go/src/pkg/math/big (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/math/big (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/server.go:5:2: cannot find package "net" in any of:
|                >  ~/go/src/pkg/net (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/net (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/m_pkgdoc.go:7:2: cannot find package "net/http" in any of:
|                >  ~/go/src/pkg/net/http (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/net/http (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/client.go:7:2: cannot find package "net/rpc" in any of:
|                >  ~/go/src/pkg/net/rpc (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/net/rpc (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/m_pkgdoc.go:8:2: cannot find package "net/url" in any of:
|                >  ~/go/src/pkg/net/url (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/net/url (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/autocompletecontext.go:10:2: cannot find package "os" in any of:
|                >  ~/go/src/pkg/os (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/os (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/os_posix.go:8:2: cannot find package "os/exec" in any of:
|                >  ~/go/src/pkg/os/exec (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/os/exec (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/m_doc.go:7:2: cannot find package "path" in any of:
|                >  ~/go/src/pkg/path (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/path (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/autocompletecontext.go:11:2: cannot find package "path/filepath" in any of:
|                >  ~/go/src/pkg/path/filepath (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/path/filepath (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/config.go:10:2: cannot find package "reflect" in any of:
|                >  ~/go/src/pkg/reflect (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/reflect (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/margo/m_lint.go:9:2: cannot find package "regexp" in any of:
|                >  ~/go/src/pkg/regexp (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/regexp (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/autocompletecontext.go:12:2: cannot find package "runtime" in any of:
|                >  ~/go/src/pkg/runtime (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/runtime (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/autocompletecontext.go:13:2: cannot find package "sort" in any of:
|                >  ~/go/src/pkg/sort (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/sort (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/client.go:10:2: cannot find package "strconv" in any of:
|                >  ~/go/src/pkg/strconv (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/strconv (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/decl.go:10:2: cannot find package "strings" in any of:
|                >  ~/go/src/pkg/strings (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/strings (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/decl.go:11:2: cannot find package "sync" in any of:
|                >  ~/go/src/pkg/sync (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/sync (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/package.go:13:2: cannot find package "text/scanner" in any of:
|                >  ~/go/src/pkg/text/scanner (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/text/scanner (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/autocompletecontext.go:14:2: cannot find package "time" in any of:
|                >  ~/go/src/pkg/time (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/time (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/cursorcontext.go:6:2: cannot find package "unicode" in any of:
|                >  ~/go/src/pkg/unicode (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/unicode (from $GOPATH)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/cursorcontext.go:7:2: cannot find package "unicode/utf8" in any of:
|                >  ~/go/src/pkg/unicode/utf8 (from $GOROOT)
|                >  ~/.config/sublime-text-2/Packages/GoSublime/src/unicode/utf8 (from $GOPATH)`
|                > exception: `None`
|   install state: busy
| sublime.version: 2221
| sublime.channel: stable
|       about.ann: a13.09.07-1
|   about.version: r13.08.31-1
|         version: r13.08.31-1
|        platform: linux-x64
|            ~bin: ~/.config/sublime-text-2/Packages/User/GoSublime/linux-x64/bin
|       margo.exe: ~bin/gosublime.margo_r13.08.31-1_go1.1.2.exe (missing)
|          go.exe: /usr/local/go/bin/go (ok)
|      go.version: go1.1.2
|          GOROOT: ~/go
|          GOPATH: ~/go/bin
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']

**Comment by jayrain** [comment]
i get the same trouble！

**Comment by obadonke** [comment]
I got this issue on Windows using go 1.5. Go version was not picked up and defaults to "go?" in the Margo compiled filename which is an invalid under windows. Suspect the regex is wrong in .\GoSublime\gosubl\about.py but since my regex is rusty, I just changed DEFAULT_GO_VERSION to "go1.5". Compiles OK now.
