### ISSUE TITLE
Integrate the go oracle tool (golang source analysis tool)

### ISSUE THREAD

**Issue by mulander** [DisposaBoy/GoSublime#363]
Please consider integrating the recently released go oracle tool in GoSublime:

http://www.reddit.com/r/golang/comments/1m6zbk/go_oracle_prototype_source_analysis_tool/

**Comment by alvarolm** [comment]
Thanks to [waigani](https://github.com/waigani) I have remplemented [GoOracle](https://github.com/waigani/GoOracle) for the guru tool:

https://github.com/alvarolm/GoGuru
https://packagecontrol.io/packages/GoGuru

If someone its interested any help is welcome ;)
