### ISSUE TITLE
impl back/fwd navigation

### ISSUE THREAD

**Issue by DisposaBoy** [DisposaBoy/GoSublime#388]
it'd be useful if we could go backward and forwards like the browser back/fwd button when GS nagivated somewhere... currently `.[` is broken but it only worked in a very limited way so it needs a little thought

**Comment by jothirams** [comment]
+1 for this

**Comment by agnivade** [comment]
Hi,

It still seems broken. Just wanted to check if there is any plan to fix this ?

**Comment by DisposaBoy** [comment]
(Assuming it works properly) Sublime Text has this feature: <kbd>Menu > Goto > Jump {Forward/Backward}</kbd>

**Comment by agnivade** [comment]
Yay, works !
