### ISSUE TITLE
gs_fmt doesn't fmt

### ISSUE THREAD

**Issue by idawes** [DisposaBoy/GoSublime#399]
Not sure what I've done, but somehow I've messed up my installation so that gs_fmt no longer auto-formats go files. I've re-installed ST3 fresh, with only package control and go sublime installed, including wiping out the "~/Library/Application Support/Sublime Text 3/" dir, and still no-dice.

There are no error logs on the ST3 console, and sublime.log_commands(True) shows that the gs_fmt command is being run. 

"go fmt" from 9o works, as does "go fmt" from the command line.

The problem exists for cmd-s, cmd-shift-s and cmd-.,cmd-f

I'm at a loss as to where to look now. Got any suggestions?

**Comment by davmaz** [comment]
This is crazy, but I installed SourceGraph for sublime text 3, and after that just about EVERYTHING was broken. Now I can't even get GoSublime to install correctly.

Any ideas?

**Comment by davmaz** [comment]
I reinstalled everything below .config and fixed the problem (I had a backup).AND, I installed Sourcegraph and it's working fine. Crazy day...

**Comment by uforic** [comment]
Spoke with @davmaz , and verified that he was able to run the Sourcegraph plugin Sublime [without issues.](https://github.com/sourcegraph/sourcegraph-sublime/issues/30)

**Comment by DisposaBoy** [comment]
@uforic I'm not sure what you're trying to say... was that comment meant for somewhere else?

**Comment by uforic** [comment]
@DisposaBoy, the Sourcegraph for Sublime Text plugin was mentioned in this thread, and I just wanted to post an update on that issue for posterity. It was an issue unrelated to GoSublime. I updated the comment to make that clearer, thanks for pointing that out.
