### ISSUE TITLE
MarGo build failed

### ISSUE THREAD

**Issue by cwouyang** [DisposaBoy/GoSublime#426]
I upgraded go to 1.2 and got some problem...
It seems that GoSublime cannot figure out what version of go I use.
Any idea?

| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\go\\bin\\go.exe', 'build', '-v', '-x', '-o', 'gosublime.margo_r13.12.17-1_go?.exe', 'gosubli.me/margo']`
|                > stdout: `
|                > stderr:`
|                > exception: `None`
|   install state: busy
| sublime.version: 3047
| sublime.channel: stable
|       about.ann: a13.12.17-1
|   about.version: r13.12.17-1
|         version: r13.12.17-1
|        platform: windows-x64
|            ~bin: D:\Software\Sublime Text Build 3047 x64\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r13.12.17-1_go?.exe (missing)
|          go.exe: C:\go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C:\go
|          GOPATH: D:\Dropbox\My Documents\Programming\GitRepos\gocode
|           GOBIN: C:\go\bin (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\WINDOWS\system32\cmd.exe', '/C', '${CMD}']

**Comment by callmewhy** [comment]
same question...in OS X 10.11. Install go with gvm.

**Comment by FreeLiveTutor** [comment]
I just had this same issue - the thread above helped me isolate.

I didn't have go installed on the machine I was running Sublime on! 

Seems obvious now, but I mention is as it's unlikely to get tested for, and does crop up if setting up a new machine and installing ST3 before setting up build tools.

**Comment by vishaltelangre** [comment]
Facing same issue.

From Sublime console:
```
GoSublime
cannot fmt file. error: `Abort. Cannot start MarGo: Exception: Cannot find command `/Users/vishal/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin/gosublime.margo_r14.12.06-1_go1.5.1.exe`
```
```
>>> from gosubl import sh; sh.go_cmd(['version']).run()
Result(out='go version go1.5.1 darwin/amd64\n', cmd_lst=['/usr/local/Cellar/go/1.5.1/libexec/bin/go', 'version'], err='', ok=True, exc=None)
```

**Comment by vrcoder** [comment]
also the same.

**Comment by wy-z** [comment]
try `chmod a+x gosublime.margo_r16.07.09-1_goXXX.exe` @vrcoder

**Comment by ZhouYanlang** [comment]
1. go env .    Check your go path 
2. Sublime ->Package Setting -> GoSublime -> settings - user
This is my go path
 {
    "env": {
        "GOPATH": "C:/Users/Tattoo.L/Documents/gowark",
        "GOROOT": "C:/Users/Tattoo.L/Documents/go"
    }
}
3. in Sublime. ctrl + B. check it

**Comment by skrzyneckik** [comment]
I had a similar problem as OP and I've installed MargoGo using `go get` as advised [here](https://stackoverflow.com/a/29858695):
>go get github.com/DisposaBoy/GoSublime/src/gosubli.me/margo
>go get github.com/DisposaBoy/GoSublime/tree/master/src/gosubli.me/margo

I've installed both packages, so, to be honest, I don't know which one resolved the issue
