### ISSUE TITLE
GoSublime blows away existing key mappings and can't be fixed.

### ISSUE THREAD

**Issue by brandonparsons** [DisposaBoy/GoSublime#440]
GoSublime currently sets all keybindings in a `KeyBindings - Default` file. This should really be in a `User` file that can be overwritten and does not get blown away every time GoSublime updates.

I use `super+.` for other plugins, and GoSublime is currently strong-arming them out of the way and I can't fix it!

**Comment by shishir127** [comment]
@brandonparsons Were you able to figure out a workaround for this one? Facing the exact same issue. Was wondering if there's any way to disable GoSublime per project.
