### ISSUE TITLE
Auto complete for fields in struct literals 

### ISSUE THREAD

**Issue by btracey** [DisposaBoy/GoSublime#463]
At least for me (OSX 10.9.1, most recent gosublime changelog 13.12.26-1) when constructing a struct literal, there is no autocompletion help. It would be great if that would exist

type Foo struct{
    Bar int
    Baz int
}

var MyFoo Foo = Foo{
    B    // It would be great if autocomplete menu popped up here with Bar and Baz

**Comment by conikeec** [comment]
Has #463 and #200 been merged ?
Does not seem so as there is no auto completion for structs as yet
