### ISSUE TITLE
Add option in cmd+.. to explicitly drop-cache in gocode

### ISSUE THREAD

**Issue by ucirello** [DisposaBoy/GoSublime#502]
Sometimes, gocode cash get stuck and an explicit drop-cache call solves the issue.

Better than opening a terminal and call gocode drop-cache, the option in GoSublime command palette would be handy.

**Comment by srinathh** [comment]
I've been able to fix this by running `go clean` on the package where the problem is showing up (ie. this gets rid of compiled files in he pkg directory) and then rebuilding whatever app you are working on
