### ISSUE TITLE
Things are not working right

### ISSUE THREAD

**Issue by lukescott** [DisposaBoy/GoSublime#515]
I apologize in advance for lumping this all together. The issues I've been having I've been "solving" by hard-resetting Sublime, and this has worked for me to "solve" these most of the time (temporarily) to allow me to keep working. I'm not sure if some of these have been fixed or not, or perhaps there is some setting I'm missing.

I haven't reported these before because they happen sporadically over time, and are hard to reproduce. It's starting to drive me nuts.
- Over a long period of time typing in Sublime gets really slow. It takes about 200 milliseconds per keystroke. This seems like a memory leak. Resetting sublime "solves" this.
- The auto complete is either not working (no choices) or is wrong (after choosing the parameters are wrong). Resetting Sublime solves it "not working". Today it's getting the interface wrong, and resetting Sublime is not solving it.
  
  It usually "doesn't work" when I haven't done a "go install" for a package (sometimes). If I do a "go run file.go" it doesn't pick up the interfaces at all. I'm not sure what the trigger is. When I was using Go 1.1 it seemed to work without me doing much of anything.
- Sometimes I'll get stuck in a "tab loop". I'll be typing in a function and hit tab to indent and the cursor jumps to the bottom of the screen. If I return the cursor to the top and hit tab it does it again. I've been able to "solve" this by hitting tab until it actually inserts a tab character and _then_ I return to where I'm wanting to type.

**Comment by zhum** [comment]
I confirm, working with enabled GoSublime is very hard - in slows down all sublime. Please, fix. May be I can disable some features, like auto-linting or something else?

**Comment by lukescott** [comment]
For me the slowness ended up not being GoSublime but GitGutter doing work in the main thread. There is a `non_blocking` option for it not to do that.

**Comment by ianchildress** [comment]
The GitGutter non_blocking option fixed this for me as well.
