### ISSUE TITLE
Auto gofmt on completion not working with custom GOROOT

### ISSUE THREAD

**Issue by btracey** [DisposaBoy/GoSublime#523]
Gofmt on save no longer works, and I believe this happened when I moved GOROOT away from /usr/local. I saw on a different issue that there can be problems with multiple go installations, so I deleted the old one. I tried reinstalling GoSublime, changing only the "env" variable. Goimports is not working either, so I'm guessing it's something with the save integration. There are no MarGo warnings on startup (which do occur if I have an incorrect GOROOT variable). I'm not sure what else to try. Thanks. 

In GoSublime.sublime-settings - GoSublime
"env": {
    "GOROOT": "/Users/brendan/go_1_2/go", 
    "GOPATH": "/Users/brendan/Documents/mygo"
},
"fmt_enabled": true,

The entire contents of the user settings are
{
    "fmt_cmd": ["goimports"]
}

Go environment variables:
brendan:~/Documents/mygo/src$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/brendan/Documents/mygo"
GORACE=""
GOROOT="/Users/brendan/go_1_2/go"
GOTOOLDIR="/Users/brendan/go_1_2/go/pkg/tool/darwin_amd64"
TERM="dumb"
CC="clang"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by davmaz** [comment]
I'm having a crazy issue. I have 2 SublimeText3 windows open. One of them correctly executes goimports when saving a file. The other show this in the log:

** 2016-01-28 16:58:03.882521 **:
GoSublime
cannot fmt file. error: `Blocking Call(sh): Timeout'
--------------------------------

**Comment by davmaz** [comment]
NEVERMIND! Sorry. If I have any syntax errors in the file, goimports won't get called. It's strange: to test if goimports is 'working' I just delete one of the imports -- that would give the error. Now it doesn't.
