### ISSUE TITLE
autocomplete not working for local packages

### ISSUE THREAD

**Issue by keyurva** [DisposaBoy/GoSublime#526]
I'm using ST3 on windows with the gosublime plugin. I'm developing an app engine application. Auto-complete works fine for packages from the standard library as well as from the app engine SDK. But it does not for local packages.

I've gone through a couple of issues related to this topic but to no avail. Appreciate your help.

Thanks,
Keyur

**Comment by Volox** [comment]
+1

**Comment by veegee** [comment]
Try updating the gocode binary, maybe that will help.

But I found a real solution to this: use Vim with vim-go or LiteIDE if you don't care about having a Vim mode. I gave Sublime Text a try, but it's pretty much now an unmaintained pile of trash.

**Comment by lukewilliamboswell** [comment]
+1

**Comment by Graha** [comment]
+1

**Comment by jaytaylor** [comment]
+1

**Comment by jaytaylor** [comment]
Local package auto-completion was working fine in ST3 until yesterday..now it is completely broken for me.  Anyone have any advice or ideas on how to resolve?

I didn't know how much I appreciated this until I no longer have it..very annoying to have to go open files all the time to see what functions are available.

**Comment by jaytaylor** [comment]
Additional note: auto-completion also no longer works for me in ST2.

**Comment by jaytaylor** [comment]
Alright, so I was able to fix it by taking the following steps:

* Upgrading from go 1.4 to go 1.4.2

* `rm -rf ~/go/pkg/darwin_amd64`

Cheers!

**Comment by coredump** [comment]
Is there a way to do the `gs9o_open` solution work without opening the bottom console?

**Comment by tylerl** [comment]
This problem goes away if you remove and re-create your personal GOPATH dir after go 1.4.2 upgrade.

**Comment by jaytaylor** [comment]
Great info, thanks!

**Comment by coredump** [comment]
What do you mean by recreate the path?

**Comment by codingrogue** [comment]
Like remove my go directory or my GOPATH env variable?

**Comment by jaytaylor** [comment]
The directory - you want everything under $GOPATH/pkg to be wiped.

**Comment by codingrogue** [comment]
Alright but it's still not working for me. I just refactored a function name and it's still suggesting the old name even after relaunching Sublime. I guess the point is not to always recreate the pkg folder.

**Comment by jaytaylor** [comment]
I feel your pain, when it wasn't working for me I was pretty upset about it!

You may also try removing $GOHOME/pkg

 e.g. /usr/local/go/pkg

**Comment by robertobc** [comment]
Any ideas? This just started happening. Seems like it was after I upgraded to go v1.5.3.

**Comment by jaytaylor** [comment]
I definitely had similar issues the last time I upgraded go versions.  Make sure to clear out previously compiled content from $GOPATH/pkg/*.

**Comment by tj** [comment]
@robertobc might be hitting #670. I didn't touch a single thing on my machine, it was fine, I saw GoSublime update and display the changelog, and then had issues, nothing to do with GOPATH etc unless GoSublime is fiddling with things.

**Comment by robertobc** [comment]
@tj It could be. I even tried reinstalling Sublime, Go and GoSublime. Still no luck.
The built in packages auto complete perfectly. The local ones don't. 
I'm on OSX in case other are having issues on different platforms.

**Comment by codepushr** [comment]
@robertobc Try building your projects without errors, this sometimes fixed it for me. I found switching to vim-go a better alternative anyway.

**Comment by robertobc** [comment]
@codepushr In the past that usually fixed it for me as well. This time no luck though :(

**Comment by DisposaBoy** [comment]
Some potentially useful information should be printed in the console after attempting completion on a package for the first time... other than that, and with no way to re-produce this, I can't help much

**Comment by robertobc** [comment]
@DisposaBoy Thanks! I checked the console and for whatever reason this time I saw errors I never saw before. Seems like there was an error in the $GOPATH even though I hadn't changed it. Changing it to something new and then back fixed the issue.

**Comment by paulcwarren** [comment]
+1 pls!

**Comment by monissiddiqui** [comment]
+1

**Comment by GeekyVenkat** [comment]
+1

**Comment by nishanttotla** [comment]
I started having this issue recently after updating to Go version `1.6`. Tried @robertobc's idea of updating and changing back `GOPATH`, but local package changes aren't being updated for autocomplete. Anyone have suggestions?

**Comment by wolfgangmeyers** [comment]
Also having this issue on 1.6. Importing from src makes no difference. Also not getting any autocomplete for some other packages, such as "github.com/stretchr/testify/mock"

**Comment by songleo** [comment]
+1

**Comment by RomanMinkin** [comment]
For **govendor** I have to ran following command every time I add a new package:
```bash
govendor build +vendor
```

fixed issue for me

**Comment by sharathbj** [comment]
I think the only solution to this problem is https://packagecontrol.io/packages/All%20Autocomplete

Enjoy!!!

**Comment by ishanray** [comment]
In Visual Studio Code, I can get autocomplete of builtin packages before importing.

```
package main

func main() {
    fmt.|
}
```

From here I can choose Println and after saving will autoimport the fmt package.

In GoSublime I need to import the package first before I see any completion. Is there a way to avoid that?

**Comment by songleo** [comment]
@ishanray  u can use `goimports`,  add a configuration in GoSublime.sublime-settings:

```
    "fmt_cmd": ["goimports"],
```

**Comment by ishanray** [comment]
@songleo yes I do use goimports, but requires me to save the file. In vscode even before saving the file I get autocomplete of local packages.

**Comment by darkwingg** [comment]
+1

**Comment by paulwalker** [comment]
FYI, for users of virtualgo (https://github.com/GetStream/vg), I found out that I needed to make sure to start sublime in the project directory and/or within a package directory located in the virtual GOPATH, so that sublime recognized the virtual GOPATH. You can user the "open log file" command to see the value that GoSublime (margo) uses.

**Comment by ramprasad1020** [comment]
i am using liteide.
code auto completion works even for local packages for me.
commands are:
cd $GOPATH/src/MYPACKAGE
go install

**Comment by morganwu277** [comment]
You can just follow this post: 
https://morganwu277.github.io/2018/05/30/Setup-Golang-Dev-Env-in-Sublime-Text3/
