### ISSUE TITLE
Gosublime Margo build failed

### ISSUE THREAD

**Issue by fanyang01** [DisposaBoy/GoSublime#528]
Today I eventually know that "Margo build failed"(Windows 8) is caused by the Chinese  character in my Windows user name.So Gosublime can't create temp building files in "C:\Users__\AppData\Temp".I have solved my problem by changing it into English word.But I hope this problem can be fixed.

**Comment by LxMit** [comment]
Yes, I have the same problem. And change the Chinese user folder name into English is complicated. I hope this problem can be fixed.
