### ISSUE TITLE
Color output in 9o

### ISSUE THREAD

**Issue by rnapier** [DisposaBoy/GoSublime#529]
It seems that 9o is supposed to support color output, but when running tools like ginkgo, I get output like:

````
[ `go test` | done: 4.112507473s ]
  Running Suite: Integration Suite
  ================================
  Random Seed: ESC[1m1398858945ESC[0m
  Will run ESC[1m3ESC[0m of ESC[1m3ESC[0m specs
````

Is this a configuration problem, or does 9o have trouble with color in tool output? It is colorizing its own output (the # in the prompt is red).

**Comment by qindj** [comment]
@rnapier I have the same issue, did you solve it ?

**Comment by DisposaBoy** [comment]
9o doesn't support color output and there are no plans to do so because Sublime Text doesn't allow for that without hacks which doesn't work well.
