### ISSUE TITLE
slowness when gosublime is enabled

### ISSUE THREAD

**Issue by acasanova** [DisposaBoy/GoSublime#530]
I've been experiencing some slowness when typing in *.go files. Is there anything I can do to troubleshoot or alleviate this slowness.

**Comment by blalor** [comment]
Still seeing this.  I've been getting around it by removing permissions on the margo binary, but it tends to come back after an upgrade.

**Comment by digikata** [comment]
I see this after i leaving a file in GoSublime mode open overnight, even typing single characters can be slow. (ST3 build 3083)

**Comment by ayhoung** [comment]
+1

**Comment by kjaleshire** [comment]
+1

**Comment by AntoineFinkelstein** [comment]
:+1:

**Comment by ppone** [comment]
+1
