### ISSUE TITLE
Per project GOROOT, GOPATH settings don't work

### ISSUE THREAD

**Issue by mprobst** [DisposaBoy/GoSublime#535]
GoSublime's documentation says that you can set `GOROOT` and `GOPATH` in a `.sublime-project`. That does not seem to work for me with an installation of regular go and an installation of AppEngine go, even with `installsuffix`.

If I set in `GoSublime.sublime-settings` (i.e., the global one):

``` js
{
  "env": {
    "GOROOT": "/usr/local/Cellar/go/1.2.2/libexec"  // same as go env reports
  }
}
```

And in my project specific one:

``` js
{
    "settings":
    {
        "GoSublime":
        {
            "installsuffix": "appengine",
            "env":
            {
                "GOPATH": "/Users/martin/src/goae",
                "GOROOT": "/usr/local/Cellar/go-app-engine-64/1.9.4/share/go-app-engine-64/goroot/"  // as goapp env reports
            }
        }
    }
}
```

Code completion does not work - I do not get any code completions at all.

However if I set GOROOT to be the App Engine specific one in `GoSublime.sublime-settings`, I get code completion as expected.

Another open issue (by @ralfr, issue #497) suggested adding your App Engine GOROOT to your GOPATH. That seems a bit wrong conceptually, and in any case doesn't change the situation for me.

Is it supposed to be possible to run a MarGo built with one go version on go code that is built with another version (architecture, installsuffix, ...)?

**Comment by fredsa** [comment]
With GoSublime r14.12.06-1 with Sublime Text 3083 I'm finding that:

1. Setting a value for `GOPATH` in `~/.bash_profile` (on OSX) causes GoSublime to *ignore* the `GOPATH` environment set by either `GoSublime.sublime-settings` or `myproject.sublime-project`
2. Note, that it's not the `GOPATH` in your current shell environment (in the case where you launch `subl` from a terminal window). Instead, the OS executes you `~/.bash_profile` when it launches the Sublime Text process.
3. An easy fix is to only set `GOPATH` in your `~/.bash_profile` when in an interactive shell, e.g.
```
if [ -n "$PS1" ]
then
  GOPATH=…
fi
```
4. If `GOPATH` is not set by your `~/.bash_profile`, then `GOPATH` from `myproject.sublime-project` takes precedence over `GOPATH` set in `GoSublime.sublime-settings`.
5. Changes to `GOPATH` in `GoSublime.sublime-settings` requires a restart to Sublime Text to take effect.
6. Changes to `GOPATH` in `myproject.sublime-project` take effect immediately.

**Comment by FiloSottile** [comment]
I'm deleting my fork and I don't know if this is still relevant, but here is the patch I had on my fork.

```patch
From 515c2c766f0dbdc7b118ee4c34d4533966b5252a Mon Sep 17 00:00:00 2001
From: Filippo Valsorda <filippo@cloudflare.com>
Date: Mon, 6 Oct 2014 18:21:49 +0100
Subject: [PATCH] Actually merge the project settings as pretended by USAGE.md

---
 gosubl/gs.py | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/gosubl/gs.py b/gosubl/gs.py
index a17dbdc..8b9fcf1 100644
--- a/gosubl/gs.py
+++ b/gosubl/gs.py
@@ -234,9 +234,14 @@ def settings_dict():
 		if v is not None:
 			m[k] = v
 
+	proj = attr('last_active_project_settings', {})
+
 	nv = dval(copy.copy(_settings.get('env')), {})
-	lpe = dval(attr('last_active_project_settings', {}).get('env'), {})
+	lpe = dval(proj.get('env'), {})
 	nv.update(lpe)
+
+	m.update(proj)
+
 	m['env'] = nv
 
 	return m
```

**Comment by javasgl** [comment]
how to fix this ?
my ST version is :  3.0, build 3143
gosublime version is : r17.12.17-1
