### ISSUE TITLE
another missing GOPATH

### ISSUE THREAD

**Issue by arxell** [DisposaBoy/GoSublime#563]
➜  ~  cat .zprofile
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/repo/go
export GOROOT=/usr/local/go

➜  ~  /bin/zsh --login -c "echo $GOPATH"
/Users/Ogorodnikov/repo/go

GoSublime Sanity Check

|   install state: done
| sublime.version: 3065
| sublime.channel: stable
|       about.ann: a14.02.25-1
|   about.version: r13.12.26-3
|         version: r13.12.26-3
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r13.12.26-3_go1.3.3.exe (ok)
|          go.exe: /usr/local/go/bin/go (ok)
|      go.version: go1.3.3
|          GOROOT: /usr/local/go
|          GOPATH: ~/repo/go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: ['/bin/zsh', '--login', '-c', '$CMD']
|       env.shell: /bin/zsh
|       shell.cmd: ['/bin/zsh', '--login', '-c', '${CMD}']
|       error log: *\* 2014-10-16 17:37:38.293276 **:
|                > MarGo: Missing required environment variables: GOPATH
|                > See the `Quirks` section of USAGE.md for info

MacOS

What is wrong?

**Comment by glennr** [comment]
+1

**Comment by burdiyan** [comment]
Any news about this issue?

**Comment by nathanboktae** [comment]
Same here. I can't for the life of me have margo recognize a `GOPATH` that is clearly there.

**Comment by andradei** [comment]
This is 3 years old. I'm having the same issue.
