### ISSUE TITLE
Remove extra CRLF on save

### ISSUE THREAD

**Issue by jordan2175** [DisposaBoy/GoSublime#575]
I have noticed that when you press save, the gosublime module removes all extra empty lines (CRLF).  Is there any way to turn off just that one feature?   All of the other make pretty features are good, I just do not care of that one.  It make seeing logical breaks in code more difficult.

**Comment by ashi009** [comment]
Make all go code look the same, is the purpose of gofmt. Which allows better collaboration with your team, easier diff/merging, etc.

If you are using blank lines to separate logic units between functions, probably you have done it wrong.

**Comment by jordan2175** [comment]
The idea behind blank lines between certain chunks of code, like functions, is purely eye-candy.  It makes it MUCH easier, IMO, to see the division when you have 2-3 spaces between functions then having a single space like everywhere else.
