### ISSUE TITLE
Browse Packages (Cmd+.,Cmd+O) should include all Go packages, even standard library.

### ISSUE THREAD

**Issue by shurcooL** [DisposaBoy/GoSublime#583]
GoSublime has a very useful feature "Browse Packages", activated via `Cmd+.,Cmd+O`. I use it all the time to open packages and browse/edit their code.

It includes all the Go packages in my $GOPATH, but it does not include standard Go packages in $GOROOT.

I think it would be better if it simply included all valid Go packages, rather than having this special rule (if in GOROOT, do not include, if not in GOROOT, do include).

Every now and then I want to use `Cmd+.,Cmd+O` to open a standard Go package and look at its source. For example, `ioutil` package. Since `Cmd+.,Cmd+O` doesn't include `io/ioutil`, I end up having to use `Cmd+O`, then browsing to `/usr/local/go`, then inside `src`, then `io`, then `ioutil`, then pick some .go file. It's more steps and a different process.

Any thoughts on this?

**Comment by mcmaur** [comment]
https://github.com/DisposaBoy/GoSublime/blob/master/USAGE.md#quirks

**Comment by shurcooL** [comment]
Ok, I've tried that.

I added `"env": { "GOROOT": "/usr/local/go" }` to my `GoSublime.sublime-settings` file.

It did not help with this issue, I still couldn't use `Cmd+.,Cmd+O` to open any standard library packages.

Just to make sure I was doing the right thing, I tried also setting GOPATH to an invalid folder to see if it would have any effect:

`"env": { "GOROOT": "/usr/local/go", "GOPATH": "/not/actually/a/gopath"}`

After I did that (and restarted ST), using `Cmd+.,Cmd+O` presented me with zero entries, saying "no source directories found".

That suggests to me that GoSublime has my correct GOROOT and it sees it. :/ Does `Cmd+.,Cmd+O` actually work for _anyone else_ to open standard library packages?

**Comment by shurcooL** [comment]
Ok, I just tried _updating_ GoSublime to latest version (via Sublime Package Control) and now I suddenly (for the first time ever) see standard library entries when doing `Cmd+.,Cmd+O`! Sorry, I should've done that sooner; I just assumed the version didn't matter since this feature never worked for me.

I think this can be closed then. Thanks!
