### ISSUE TITLE
Test Coverage Highlighting

### ISSUE THREAD

**Issue by derekperkins** [DisposaBoy/GoSublime#584]
I've dabbled with Atom recently, but it just isn't fast enough to work for me. Using https://atom.io/packages/go-plus was interesting, especially the feature that runs `go test -coverprofile` and uses the results to highlight in the editor which lines have been tested. Is that something in the pipeline?

**Comment by DisposaBlackSwan** [comment]
Not at this time, but it should be easy to implment in the future

**Comment by MrGossett** [comment]
+1
