### ISSUE TITLE
a wrong use := where = cause a format problem, format can't work 

### ISSUE THREAD

**Issue by foreversmart** [DisposaBoy/GoSublime#585]
tips in my sublime text2 GsLint(1), Line ....

**Comment by DisposaBlackSwan** [comment]
I'm not sure I understand the issue. If you mean that there's a syntax errors like below, then that's how it's designed. The builtin formatter will not format source code with invalid syntax.

	package main

	func main() {
	a[0] := 123
	}

**Comment by foreversmart** [comment]
yes， I find the invalid syntax make formatter not work, not only in the line of source code with invalid syntax.
