### ISSUE TITLE
Not available error report

### ISSUE THREAD

**Issue by mcmaur** [DisposaBoy/GoSublime#587]
Sometimes it doesn't show any error as you can see in the screenshot below:
![gosublimebug](https://cloud.githubusercontent.com/assets/3799031/5596892/e5653f78-9298-11e4-81a6-560ae03a09b5.jpg)
Other info:
![gosublimeversion](https://cloud.githubusercontent.com/assets/3799031/5596918/7e801ef8-9299-11e4-8067-53f5a037a624.jpg)
Available for add additional info on request

**Comment by DisposaBlackSwan** [comment]
AFAIK, by default only syntax errors are shown. If you didn't manually setup the tracking of compilation errors, then they won't be shown. This might be useful https://github.com/DisposaBoy/GoSublime/blob/master/articles/golint.md
