### ISSUE TITLE
Question: other editor

### ISSUE THREAD

**Issue by Alexey-T** [DisposaBoy/GoSublime#589]
Hi. Good work on Go autocomplete. Do you interested in making go autocomplete for Synwrite?
https://sourceforge.net/p/synwrite/wiki/python%20API/

(job for some donation)

**Comment by DisposaBlackSwan** [comment]
autocomplete is currently provided by https://github.com/nsf/gocode, you can use subprocess and a little bit of parsing to speak to its server.

**Comment by Alexey-T** [comment]
Yep. Subprocess.Popen helps.. Maybe u can help (for donation)?
