### ISSUE TITLE
Goto Definition not working on  method receivers

### ISSUE THREAD

**Issue by ypapax** [DisposaBoy/GoSublime#591]
Goto Definition works on usual methods like
`someFunc()`

```
func someFunc(){
}
```

but don't work on method receiver:
`someStruct.someOtherFunc()`

where `someOtherFunc` is defined

```
func (someStruct SomeStruct) someOtherFunc() {
}
```

**Comment by OneOfOne** [comment]
I can confirm this.

**Comment by parkghost** [comment]
+1

**Comment by dlclark** [comment]
This is handled in PR #571
