### ISSUE TITLE
GOPATH is not being respected on windows

### ISSUE THREAD

**Issue by prencher** [DisposaBoy/GoSublime#606]
`GOPATH` and `GS_GOPATH` do not seem to work at all on Windows.

Setting `GOPATH` globally works correctly for go build, but I get no completion inside of Sublime. The same thing happens with using `GS_GOPATH`, or a sublime project file.

Completion only ever works for standard library, and the current file. This is with a full fledged src, bin, pkg structure.

**Comment by prencher** [comment]
After much debugging, I got it to work by putting the following into my user-specific GoSublime settings:

```json
{
    "env": { "GOPATH": "$GS_GOPATH;" },
}
```

Note that the semicolon is important. MarGo complains about missing GOPATH otherwise, when not in a .go file (e.g. when sublime starts).

**Comment by JasonMing** [comment]
Thanks @prencher :+1: 
Nice trick, this solution is work, it solve the annoying MarGo error.
