### ISSUE TITLE
Why I got the wrong anwser in gosublime ?

### ISSUE THREAD

**Issue by micln** [DisposaBoy/GoSublime#609]
you can see my code first

``` go
package main

/*
#include <stdio.h>
void print(){
    printf("Hello\n");
}

typedef struct{
    char Name[10];
    int age;
}Person;
*/
import "C"
import (
    "fmt"
)

func main() {
    C.print()
    a := C.Person{}
    fmt.Println(a)
}

```

I run this code in bash it shows():

``` bash
Hello
{[0 0 0 0 0 0 0 0 0 0] [0 0] 0}
```

But when I use the gosublime, It gots:

``` bash
{[0 0 0 0 0 0 0 0 0 0] [0 0] 0}
Hello
```

**Comment by alecthomas** [comment]
This is not incorrect behaviour. C's `printf()` may be fully buffered, line buffered, or not buffered at all. It appears that when run at a console `printf()` is line buffered and so is flushed at the newline, while when run under gosublime's PTTY (I assume) it is fully buffered and does not get flushed until the program completes.

Go's `fmt.Println()` is unrelated to `printf()` and (I believe) is unbuffered by default.
