### ISSUE TITLE
Margo.exe missing

### ISSUE THREAD

**Issue by johngb** [DisposaBoy/GoSublime#612]
I haven't changed any GoSublime settings recently, but have recently started getting the following when doing a sanity check:

```
GoSublime Sanity Check

|   install state: done
| sublime.version: 3083
| sublime.channel: stable
|       about.ann: a14.02.25-1
|   about.version: r14.12.06-1
|         version: r14.12.06-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r14.12.06-1_go1.4.2.exe (missing)
|          go.exe: /usr/local/Cellar/go/1.4/libexec/bin/go (ok)
|      go.version: go1.4.2
|          GOROOT: ~/gocode/go_appengine/goroot/
|          GOPATH: ~/gocode/
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: ['/bin/zsh', '--login']
|       env.shell: /bin/zsh
|       shell.cmd: ['/bin/zsh', '--login']
```

I've tried removing GoSublime as a package; adding GoSublime as a package; and restarting Sublime, but no luck with it.

My $GOROOT is set for using AppEngine for Sublime builds, and I've had it set this way for months.

**Comment by strayobject** [comment]
If you get this error and have GOROOT defined in env inside your user settings, then all I had to do to was to remove that line and restart Sublime. So look for:
```
"env": {
  "GOROOT": "some/path/here"
}
```

**Comment by johngb** [comment]
@strayobject Was this with using AppEngine?

**Comment by strayobject** [comment]
@johngb No it was not. I have a local set up, but thought it was something worth checking out.
