### ISSUE TITLE
Auto remove unused imports

### ISSUE THREAD

**Issue by sundy-li** [DisposaBoy/GoSublime#613]
It will be better to auto remove unused imports in gosublime just like emacs (hooks after save), may be someone don't like it, it should be an optional feature many others enjoy.

**Comment by mgenov** [comment]
goimports is doing this automatically. I have the following definition in my user settings file:

```javascript
{
    "fmt_cmd": ["goimports"]
}
```

and after save imports are removed automatically.

**Comment by sundy-li** [comment]
That is really useful, thanks a lot

**Comment by leavengood** [comment]
Please close this issue since it has a solution.
