### ISSUE TITLE
goimports does not add packages outside std with gosublime

### ISSUE THREAD

**Issue by kortschak** [DisposaBoy/GoSublime#614]
I have `{... "fmt_cmd": ["goimports"], ...}` in my user settings and GOPATH and GOROOT are set correctly in the user config. I can see goimports is run on save via top, however imports for packages outside std are not added - goimports does work when called from the command line with -w.

**Comment by cv711** [comment]
+1
I have the same issue. I can use `goimports` everywhere else, but when I add it in the `fmt_cmd` it doesn't do anything for me.

**Comment by derekperkins** [comment]
It works just fine for me. Sometimes I have to run `go get github.com/.../...` for gocode and goimports to pick up the new / edited packages.

**Comment by gugahoi** [comment]
try using the full path to `goimports` or updating you $PATH in sublime
