### ISSUE TITLE
Add option to stop MarGo to save battery

### ISSUE THREAD

**Issue by ChristianSiegert** [DisposaBoy/GoSublime#617]
When editing Go files, MarGo runs constantly in the background. I understand that this is necessary for code completion but it drains the battery very quickly. Instead of the usual 10 hours of use I only get about 5 hours when GoSublime/MarGo is running. With other programs running in parallel I get even less which makes it hard to work on the road. I tried killing the MarGo processes but they keep respawning. To save battery it would be great if GoSublime/MarGo could be stopped and started at will.

**Comment by OneOfOne** [comment]
You can add it to your `"ignored_packages"` in your sublime config or use the package manager to enable/disable it.
