### ISSUE TITLE
MG|GS /Doc

### ISSUE THREAD

**Issue by DisposaBoy** [DisposaBoy/GoSublime#62]
mg/doc is currently just a stub implementation to allow design of gs/doc .

mg/doc currently supports only the expression pkgname.Funcname but the design(general interaction) of the goto definition and doc hint functionality in gs/doc ignoring a bit of styling is complete (direct #21 and #31 here)
- infer expression given only the values for row/col or offset into src
  - done
- search all types and vars in all packages not just top-level functions in import packages
  - partially complete - types are not resolved
- implement doc browser to quickly find _all_ definitions in GOPATH and GOROOT
  - done
- offer function parameter hint as you type - this would allow truncating the completion when it gets too long (ST2 truncates it in a weird way, but there's no way for me to know how wide the completion pop-up can be)

**Comment by tamird** [comment]
> not currently, no. Only pkg.X is supported

Is this still the case?

**Comment by diogomonica** [comment]
Yeah, is this still the case? I'm hitting the same problems.

@tamird nice seeing you here too.

**Comment by bportnoy** [comment]
Thanks for all the work on this; definitely +1 to this feature.

**Comment by tamird** [comment]
@diogomonica the solution is to use something that uses godef/oracle for symbol lookup. I'm using https://github.com/ironcladlou/GoTools

**Comment by dmitris** [comment]
I can right click on a method name and the mouse context menu shows "Goto Definition" as the first option.  But the "Cmd-. Cmd-g" (on Mac) does not work.  What is the recommended way to configure it or re-enable the shortcut which was so helpful?  Thanks!

**Comment by cloudapex** [comment]
F12
