### ISSUE TITLE
gb support questions

### ISSUE THREAD

**Issue by ardan-bkennedy** [DisposaBoy/GoSublime#621]
Hi, I was wondering if you had 5 minutes to answer a couple of questions?

**Comment by abourget** [comment]
Ask the questions!

**Comment by ghchinoy** [comment]
With `gb`, source can be somewhere outside GOPATH resulting in GoSublime not knowing about the code being developed. Manually adding the current project's path to `Packages/User/GoSublime.sublime-settings` is somewhat, well, manual. It'd be nice if there were a way for GoSublime to handle this, possibly by updating the settings (while leaving the system's GOPATH alone).

**Comment by ches** [comment]
I've used project settings like this for a `gb` project:

```json
{
	"folders":
	[
		{
			"path": "/absolute/path/to/project"
		}
	],
	"settings": {
		"GoSublime": {
			"env": {
				"GOPATH": "/absolute/path/to/project:/absolute/path/to/project/vendor",
				"PATH": "$PATH:$HOME/src/go/bin"
			}
		}
	}
}
```

Where `PATH` still refers to my normal globally-shared `$GOPATH`, so tools like `goimports` installed with `go get` are found without installing them in every project.
