### ISSUE TITLE
Doesn't show errors

### ISSUE THREAD

**Issue by alehano** [DisposaBoy/GoSublime#627]
Golint works ok. But I don't have any syntax errors highlighting. Cmd+.,Cmd+e shows: no errors to report.

Gosublime v.2014.12.06.17.15.26

**Comment by themartorana** [comment]
Same version, same situation. Dots appear in the gutter, and the relevant information is displayed in the status bar when focusing the cursor on that line, but there are no easily navigable errors in the GoSublime error list.

**Comment by kellyellis** [comment]
Same issue here.

**Comment by mcuadros** [comment]
+1
