### ISSUE TITLE
gocode(autocomplete) is not working 

### ISSUE THREAD

**Issue by zhaohaidao** [DisposaBoy/GoSublime#632]
OS: Mac OSX 10.10.3
ST:Sublime Text 3 3083

**Comment by mihneagiurgea** [comment]
I'm having some issues with autocomplete as well. Here's my experience:
 * correctly configure GOPATH and PATH
 * autocomplete works only on built-ins (e.g. "os" package)
 * but not on any packages from GOPATH/src/...

**Comment by zhaohaidao** [comment]
Can not thanks more
I  re-configure GOPATH as you suggested, it works perfectly.

**Comment by gr4y** [comment]
Well, it worked for me like a charm until some days ago, when I updated all packages with go get -u all and now I only get autocompletion for packages I installed via `go install`. And today I found Sublime Text 3 to not show my any autocompletion, no matter if built in or external packages. 
GoPath: `/Users/sascha/GoCode`
Path: `/Users/sascha/.gem/ruby/2.1.3/bin /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bin /opt/rubies/ruby-2.1.3/bin /usr/local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /usr/local/opt/go/libexec/bin /Users/sascha/GoCode/bin /Users/sascha/bin`
GoSublime User configuration:
 ```
{
  "autocomplete_builtins": true,
  "autocomplete_closures": true,
  "env": {
        "GOPATH": "/Users/sascha/GoCode"
    }
}
```

**Comment by gr4y** [comment]
Same Sublime build as @zhaohaidao running on OS X 10.10

**Comment by tnolet** [comment]
Same issue here. Code completion works great on standard packages, but not on any imported packages, my own or third party. Regardless of whether they are installed using `go install`

**Comment by gr4y** [comment]
Well... I have two projects. One where I use `godep` and one without `godep`. My autocompletion works for the project with `godep` with all packages, even my own.

**Comment by krsand** [comment]
Thanks @gr4y , It worked for me.

**Comment by jeffdeng** [comment]
Thanks @gr4y , It worked for me.

**Comment by wubin1989** [comment]
Thanks @gr4y , It worked for me.
