### ISSUE TITLE
Use different gocode binary?

### ISSUE THREAD

**Issue by mihneagiurgea** [DisposaBoy/GoSublime#641]
Is there any way to easily configure GoSublime / MarGo to use a different gocode binary? This would be useful for running either a newer version of gocode or even a custom one (different build).

**Comment by kylewolfe** [comment]
I second this. I need to configure gocode's lib-path to enable Go 1.5 vendor experiment auto completion.

**Comment by DisposaBoy** [comment]
If there's a problem, open an issue for *that problem*. Having a customizable gocode binary doesn't really solve any problems because any problem (like the vendor experiment) most likely also affect other parts of margo
