### ISSUE TITLE
 GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by lanlsots** [DisposaBoy/GoSublime#643]
i don't konw how to fix it.
i was rebuild it  but it's not work, too.

 > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-v', '-x', '-o', 'gosublime.margo_r14.12.06-1_go1.5.exe', 'gosubli.me/margo']`
|                > stdout: ``
|                > stderr: `WORK=~\AppData\Local\Temp\go-build493877418
|                > package gosubli.me/margo
|                > 	imports runtime: C source files not allowed when not using cgo or SWIG: atomic_amd64x.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_windows.c mfixalloc.c mgc0.c mheap.c msize.c netpoll_windows.c os_windows.c os_windows_amd64.c panic.c parfor.c proc.c runtime.c signal.c stack.c string.c sys_x86.c`
|                > exception: `None`
|   install state: busy
| sublime.version: 3083
| sublime.channel: stable
|       about.ann: a14.02.25-1
|   about.version: r14.12.06-1
|         version: r14.12.06-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r14.12.06-1_go1.5.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go1.5
|          GOROOT: C:\Go\
|          GOPATH: G:\workhard\godoc
|           GOBIN: C:\go\bin (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\Windows\\system32\\cmd.exe', '/C', '${CMD}']

please help  thanks very much !

**Comment by winxxp** [comment]
I fixed by 
```
  "env": {
        // "GOPATH": "$GS_GOPATH;$GOPATH",
     },
 ````
