### ISSUE TITLE
GoSublime error: MarGo build failed 

### ISSUE THREAD

**Issue by jackbing228** [DisposaBoy/GoSublime#645]
GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['D:\\Program Files\\Go\\bin\\go.exe', 'build', '-v', '-x', '-o', 'gosublime.margo_r14.12.06-1_go1.4.2.exe', 'gosubli.me/margo']`
|                > stdout: ``
|                > stderr: `WORK=~\AppData\Local\Temp\go-build207090487
|                > runtime
|                > go build runtime: windows/amd64 must be bootstrapped using make.bat`
|                > exception: `None`
|   install state: busy
| sublime.version: 3083
| sublime.channel: stable
|       about.ann: a14.02.25-1
|   about.version: r14.12.06-1
|         version: r14.12.06-1
|        platform: windows-x64
|            ~bin: D:\software\sublime text\Sublime Text Build 3083 x64\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r14.12.06-1_go1.4.2.exe (missing)
|          go.exe: D:\Program Files\Go\bin\go.exe (ok)
|      go.version: go1.4.2
|          GOROOT: D:\Program Files\Go
|          GOPATH: H:/go/development
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\Windows\\system32\\cmd.exe', '/C', '${CMD}']

this is my problem. How can i solve the problem?

**Comment by winxxp** [comment]
I fixed by 
```
  "env": {
        // "GOPATH": "$GS_GOPATH;$GOPATH",
     },
 ````
