### ISSUE TITLE
strange connection using gosublime package

### ISSUE THREAD

**Issue by cleesmith** [DisposaBoy/GoSublime#646]
While working on a Go project I noticed the following:
```
lsof -i -P
displays:
COMMAND   PID  USER FD   TYPE             DEVICE SIZE/OFF  NODE NAME
gosublime 1320 me   18u  IPv4 0x69c51c56390cce47      0t0  TCP  192.168.0.200:53249->li396-29.members.linode.com:443 (CLOSE_WAIT)
```
... this goes away only when I exit Sublime Text 2 (Version2.0.2, Build 2221).
What's this for ?
Is it sending messages to the mother ship ?
thanks

**Comment by DisposaBoy** [comment]
AFAICT, li396-29.members.linode.com is packagecontrol.io but I don't recall the released version of GoSublime having any binary called `gosublime` (older private versions do) and why it would connect to the internet (unless you shared code on play.golang.org)

**Comment by cleesmith** [comment]
Sometimes it just says "Sublime" instead of "gosublime" ... perhaps just reinstalling sublime will work?
