### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jesns** [DisposaBoy/GoSublime#650]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['D:\\Go\\bin\\go.exe', 'build', '-v', '-x', '-o', 'gosublime.margo_r14.12.06-1_go?.exe', 'gosubli.me/margo']`
|                > stdout: ``
|                > stderr: `go: cannot find GOROOT directory: D：\Go`
|                > exception: `None`
|   install state: busy
| sublime.version: 3083
| sublime.channel: stable
|       about.ann: a14.02.25-1
|   about.version: r14.12.06-1
|         version: r14.12.06-1
|        platform: windows-x64
|            ~bin: D:\Program Files\Sublime Text 3\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r14.12.06-1_go?.exe (missing)
|          go.exe: D:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: D：\Go
|          GOPATH: D:\Go\myGo
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\Windows\\system32\\cmd.exe', '/C', '${CMD}']

**Comment by DisposaBoy** [comment]
your `GOROOT` has the wrong type of colon http://unicode-table.com/en/FF1A/. it should probably be `C:\Go`
