### ISSUE TITLE
Illegal Character error

### ISSUE THREAD

**Issue by khuderm** [DisposaBoy/GoSublime#656]
![screen shot 2015-11-10 at 2 38 38 pm](https://cloud.githubusercontent.com/assets/8462132/11078135/c72a5910-87b8-11e5-90f2-0a44435377db.png)

getting that on a line with $. here is the line:

coll.Find({ location: { $near: [Longitude , Latitude] } })

This keeps the package from cleaning/formatting my code on save

**Comment by DisposaBoy** [comment]
I don't understand the issue. `$` is not valid Go syntax (and GoSublime does *not* fmt files with invalid syntax by design)

**Comment by khuderm** [comment]
Sorry this was my mistake. I should have closed this. I am trying out mongodb with go.
