### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by davidkuridza** [DisposaBoy/GoSublime#668]
GoSublime updated itself today, after restarting Sublime, the following error is thrown:

```
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/opt/go/bin/go', 'build', '-v', '-x', '-o', 'gosublime.margo_r16.01.09-1_go?.exe', 'gosubli.me/margo']`
|                > stdout: ``
|                > stderr: `go: cannot find GOROOT directory: /usr/local/opt/go/libexec:$GS_GOROOT`
|                > exception: `None`
|   install state: busy
| sublime.version: 3083
| sublime.channel: stable
|       about.ann: a16.01.09-1
|   about.version: r16.01.09-1
|         version: r16.01.09-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r16.01.09-1_go?.exe (missing)
|          go.exe: /usr/local/opt/go/bin/go (ok)
|      go.version: go?
|          GOROOT: /usr/local/opt/go/libexec:$GS_GOROOT
|          GOPATH: ~/work/go:
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/zsh
|       shell.cmd: ['/bin/zsh', '-l', '-c', '${CMD}']
```

I've removed the plugin, manually removed `Library/Application Support/Sublime Text 3/Packages/User/GoSublime*`, installed the plugin again, but the problem persists.

Thank you.

**Comment by davidkuridza** [comment]
Figured it out. These are the steps:

1. remove GoSublime using Package Control
2. quit Sublime
3. `rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/GoSublime*`
4. start Sublime
5. install GoSublime
6. quit Sublime
7. add GOPATH **only** to `Library/Application\ Support/Sublime\ Text\ 3/Packages/User/GoSublime.sublime-settings`
8. start Sublime and wait for GoMargo to be installed, quit Sublime
9. add GOROOT to `Library/Application\ Support/Sublime\ Text\ 3/Packages/User/GoSublime.sublime-settings`
10. start Sublime

Hope it helps.

**Comment by strayobject** [comment]
I followed @davidkuridza guide and it did not help, but it set me on the right track.
If you get the same error and have GOROOT defined in env inside your user settings, then all I had to do to was to remove that line and restart Sublime. So look for:
```
"env": {
  "GOROOT": "some/path/here"
}
```

**Comment by n1rvana** [comment]
Hmm... can you give me a TLDR of the issue?  I have GOROOT and GOPATH defined in my environment variables (Eg: in .bash_profile)... and that seems to be the problem.  I can't change that because other build stuff depends on those environment variables.  Neither of these are set in my user settings for sublime.

**Comment by michaelritsema** [comment]
I don't believe sublime cares about your .bash_profile settings. You have have something like this:

launchctl setenv GOROOT /usr/local/go
launchctl setenv GOPATH /Users/myusername/GoProjects

I did and this was interfering with the install. After removal the install worked.

**Comment by BigKuCha** [comment]
solution by @strayobject works for me!  check both `Setting-defaul`t and `Setting-User`, just remove `GOROOT` and restart SubLime~

**Comment by davidkuridza** [comment]
Finally figured it out while moving to new laptop :)

I'm using homebrew to handle go installation, and the problem with the GoSublime configuration was wrong `GOROOT` value. This is the change:

```diff
-  "GOPATH": "$HOME/work/go:$GS_GOPATH",
-  "GOROOT": "/usr/local/bin/go:$GS_GOROOT"
+  "GOPATH": "$HOME/go",
+  "GOROOT": "/usr/local/Cellar/go/1.7.4_2/libexec"
```

`GOROOT` needs to be updated when a new go version is installed, but that's a minor issue.

Big thanks to everyone in this thread!
