### ISSUE TITLE
Noisy/useless autocomplete "Pattern" suggestions

### ISSUE THREAD

**Issue by AaronO** [DisposaBoy/GoSublime#669]
When autocompleting an attribute/method on a pkg, or struct I get 3 useless `Pattern` suggestions at the top (using ST3 and latest GoSublime):

<img width="412" alt="screen shot 2016-01-14 at 11 27 39 am" src="https://cloud.githubusercontent.com/assets/949223/12322305/76ec12d0-bab3-11e5-96cc-0c12aebe405e.png">

Any idea what's causing this and how I could remove them ? (They are very distracting) Thanks !

**Comment by DisposaBoy** [comment]
Those are provided by Sublime Text or some other plugin. All GoSublime completions have a unicode character at the end. You can also try disabling Sublime Text's `Go` package by adding it to your `ignored_packages` list, GoSublime doesn't depend on it.
