### ISSUE TITLE
Completion no longer works

### ISSUE THREAD

**Issue by tj** [DisposaBoy/GoSublime#670]
As mentioned previously, one of my machines is fine (with the latest GoSublime), however my laptop is not. Just opening in case anyone has ideas, I'll cross-check config when I'm home and see if I can find what the issue might be. It works for some packages but not others (even stdlib), my Go config etc is fine, and unchanged from before GoSublime became active again.

**Comment by pzurek** [comment]
I'm seeing similar behaviour. Curious what it may be.

**Comment by tj** [comment]
Ended up just being cross-compiling for me, I was missing the .a files, I didn't realize gocode didn't work from source.

**Comment by bestplay** [comment]
You save my day @tj . I am using Express.js/koa.js. 👍 

After `go install -i `, I got all .a files of my packages, and autocomplete works.

For others who encounter the same issue: 
My GoSublime.settings : 
```
{
    "comp_lint_enabled": true,
    "comp_lint_commands": [
        {"cmd": ["golint *.go"], "shell": true},
        {"cmd": ["go", "vet"]},
        {"cmd": ["go", "install", "-i"]}
    ],
    "on_save": [
        {"cmd": "gs_comp_lint"}
    ]
}
```
