### ISSUE TITLE
YouTube demos channel does not exist.

### ISSUE THREAD

**Issue by nathany** [DisposaBoy/GoSublime#672]
The Readme states:

> New demos will be uploaded to http://www.youtube.com/user/GoSublime/videos

YouTube reports:

> This channel does not exist.

Is there a channel?

**Comment by DisposaBoy** [comment]
Sorry for the late reply. It seems I was unsubscribed from this repo.

I think deleted that channel a long time ago. I'll consider preparing some new demos soon.

**Comment by nathany** [comment]
Cool. Thanks
