### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by lmckoko-ericsson** [DisposaBoy/GoSublime#673]
GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/bin/go', 'build', '-v', '-x', '-o', 'gosublime.margo_r16.01.09-1_go1.exe', 'gosubli.me/margo']`
|                > stdout: `WORK=/tmp/go-build146297600
|                > mkdir -p $WORK/gosubli.me/something-borrowed/gocode/_obj/
|                > cd ~/.config/sublime-text-3/Packages/GoSublime/src/gosubli.me/something-borrowed/gocode
|                > /usr/lib/go/pkg/tool/linux_amd64/6g -o $WORK/gosubli.me/something-borrowed/gocode/_obj/_go_.6 -p gosubli.me/something-borrowed/gocode -D _~/.config/sublime-text-3/Packages/GoSublime/src/gosubli.me/something-borrowed/gocode -I $WORK ./autocompletecontext.go ./autocompletefile.go ./client.go ./config.go ./cursorcontext.go ./decl.go ./declcache.go ./formatters.go ./gocode.go ./gosublime_gocode_bridge.go ./os_posix.go ./package.go ./ripper.go ./rpc.go ./scope.go ./server.go ./utils.go
|                > mkdir -p $WORK/gosubli.me/something-borrowed/types/_obj/
|                > cd ~/.config/sublime-text-3/Packages/GoSublime/src/gosubli.me/something-borrowed/types
|                > /usr/lib/go/pkg/tool/linux_amd64/6g -o $WORK/gosubli.me/something-borrowed/types/_obj/_go_.6 -p gosubli.me/something-borrowed/types -D _~/.config/sublime-text-3/Packages/GoSublime/src/gosubli.me/something-borrowed/types -I $WORK ./api.go ./builtins.go ./check.go ./const.go ./conversions.go ./errors.go ./exportdata.go ./expr.go ./gcimporter.go ./objects.go ./operand.go ./predicates.go ./resolve.go ./scope.go ./sizes.go ./stmt.go ./types.go ./universe.go
|                > # gosubli.me/something-borrowed/gocode
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/autocompletefile.go:16: undefined: parser.AllErrors
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/autocompletefile.go:69: undefined: parser.AllErrors
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/gosublime_gocode_bridge.go:40: p.InstallSuffix undefined (type *package_lookup_context has no field or method InstallSuffix)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/utils.go:209: ctx.ReleaseTags undefined (type *build.Context has no field or method ReleaseTags)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/utils.go:210: ctx.InstallSuffix undefined (type *build.Context has no field or method InstallSuffix)
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/utils.go:225: unknown build.Context field 'ReleaseTags' in struct literal
|                > ../../../../GoSublime/src/gosubli.me/something-borrowed/gocode/utils.go:226: unknown build.Context field 'InstallSuffix' in struct literal
|                > /usr/lib/go/pkg/tool/linux_amd64/pack grc $WORK/gosubli.me/something-borrowed/types.a $WORK/gosubli.me/something-borrowed/types/_obj/_go_.6`
|                > stderr: `gosubli.me/something-borrowed/gocode
|                > gosubli.me/something-borrowed/types`
|                > exception: `None`
|   install state: busy
| sublime.version: 3103
| sublime.channel: stable
|       about.ann: a16.01.09-1
|   about.version: r16.01.09-1
|         version: r16.01.09-1
|        platform: linux-x64
|            ~bin: ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/bin
|       margo.exe: ~bin/gosublime.margo_r16.01.09-1_go1.exe (missing)
|          go.exe: /usr/bin/go (ok)
|      go.version: go1
|          GOROOT: /usr/lib/go
|          GOPATH: ~/go_workspace
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']

**Comment by DisposaBoy** [comment]
Your Go version is not supported (it's too old). You can download the latest Go version from https://golang.org/dl/
