### ISSUE TITLE
Syntax highlighting, explicit argument indices in sprintf/printf

### ISSUE THREAD

**Issue by EmperorEarth** [DisposaBoy/GoSublime#674]
Golang supports explicit argument indices, which aren't being highlighted with your plugin

`%[1]s` should be highlighted in `fmt.Printf("%[1]s %[1]s\n", stringFoo)`

A slightly longer [Playground example](http://play.golang.org/p/sHz1Kkhg76).

**Comment by DisposaBoy** [comment]
I'll consider swithcing back to the default `Go` syntax highlighting. If this annoys, you can switch to it, it seems to work fine with GoSublime.
