### ISSUE TITLE
fmt_cmd isn't use GOPATH env from GoSublime settings

### ISSUE THREAD

**Issue by p1gmale0n** [DisposaBoy/GoSublime#675]
am using custom GOPATH - configured in GoSublime.sublime-settings / project.sublime-settings
but goimports output differently from output on shell with the same GOPATH

**Comment by DisposaBoy** [comment]
If you press <kbd>ctrl</kbd>+<kbd>9</kbd> and type `env GOPATH` it should print what it think your `GOPATH` is
