### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by cdelorme** [DisposaBoy/GoSublime#676]
Output:

	| GoSublime error: MarGo build failed
	|                > This is possibly a bug or miss-configuration of your environment.
	|                > For more help, please file an issue with the following build output
	|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
	|                > or alternatively, you may send an email to: gosublime@dby.me
	|                > 
	|                > 
	|                > cmd: `['', 'build', '-v', '-x', '-o', 'gosublime.margo_r16.01.09-1_go1.5.3.exe', 'gosubli.me/margo']`
	|                > stdout: ``
	|                > stderr: ``
	|                > exception: `Cannot find command `go``
	|   install state: busy
	| sublime.version: 3103
	| sublime.channel: stable
	|       about.ann: a16.01.09-1
	|   about.version: r16.01.09-1
	|         version: r16.01.09-1
	|        platform: linux-x64
	|            ~bin: ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/bin
	|       margo.exe: ~bin/gosublime.margo_r16.01.09-1_go1.5.3.exe (missing)
	|          go.exe: go (missing)
	|      go.version: go1.5.3
	|          GOROOT: ~/.gvm/gos/go1.5
	|          GOPATH: ~/.gvm/pkgsets/go1.5/global
	|           GOBIN: (not set) (should usually be `(not set)`)
	|       set.shell: []
	|       env.shell: /bin/bash
	|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']

Looks like it found the correct GOPATH and GOROOT, but for some reason it couldn't find the go command?

Running debian jessie, and tried with explicit GoSublime settings with GOPATH, and then with both GOPATH and GOROOT, removing and reinstalling completely (including rm the related GoSublime folders) restarting in between each attempt.  Nothing works.

**Comment by cdelorme** [comment]
Well, I am out of ideas.  Here is what I tried without success:

- manually compiling
	- copied `subli.me/margo` to `$GOPATH/src
	- go build -v -x -o gosublime.margo_r16.01.09-1_go1.5.3.exe
	- adding to multiple bins:
		- `~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/r16.01.09-1_go1.5.3/bin/`
		- `~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/bin/`

After restarting sublime text I get the same error; it seems `_bins_exist()` can't find the executable.  Maybe it printed the wrong name, or maybe I have the wrong path?

- adding the PATH to cmd.env:
	- `'PATH': os.environ["PATH"],`
- setting the full path to go in the sh.Command arguments:
	- `os.path.join(os.environ["GOROOT"], "bin", "go")`

Both fail with the same tired message `exception: Cannot find command go`, which makes absolutely no sense to me unless sublime's python is somehow restricted like chroot (virtualenv?).

**Comment by lmckoko-ericsson** [comment]
Hi,
      
      I have copied the go binaries into /bin/. and /usr/bin/. and the
      problem has stopped.
      
      Thanks
      
      /Konstantin
      
      
      On 16-02-14 12:38 AM, Casey DeLorme wrote:
    
    
      
      Well, I am out of ideas. Here is what I tried without success:
      
        manually compiling
          
            copied subli.me/margo to `$GOPATH/src
            go build -v -x -o
              gosublime.margo_r16.01.09-1_go1.5.3.exe
            adding to multiple bins:
              
                ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/r16.01.09-1_go1.5.3/bin/
                ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/bin/
              
            
          
        
      
      After restarting sublime text I get the same error; it seems _bins_exist()
        can't find the executable. Maybe it printed the wrong name, or
        maybe I have the wrong path?
      
        adding the PATH to cmd.env:
          
            'PATH': os.environ["PATH"],
          
        
        setting the full path to go in the sh.Command arguments:
          
            os.path.join(os.environ["GOROOT"], "bin", "go")
          
        
      
      Both fail with the same tired message exception: Cannot
          find command go, which makes absolutely no sense to me
        unless sublime's python is somehow restricted like chroot
        (virtualenv?).
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by cdelorme** [comment]
Just to clarify, `/bin` as in the root bin folder(s)?  I'll give that a shot.

**Comment by lmckoko-ericsson** [comment]
Yes, the /bin folder in the root of the
      system.
      
      On 16-02-15 10:55 AM, Casey DeLorme wrote:
    
    
      
      Just to clarify, /bin as in the root bin
        folder(s)? I'll give that a shot.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by cdelorme** [comment]
I gave you suggestion a try, still getting the same errors.  It can't find the margo binary, and it can't build it because it can't find go, but then it proceeds to tell me exactly where my go1.5 is installed at (eg. GOPATH and GOROOT).

**Comment by DisposaBoy** [comment]
`$GOROOT/bin` should automatically be included in `$PATH` so if `~/.gvm/gos/go1.5/bin/go` really doesn't exist, I suggest you ditch `gvm` and install Go properly.

**Comment by cdelorme** [comment]
I have been using gvm for a while now; it adds convenience like being able to switch versions or upgrade very easily so I'd rather not ditch it.  It gets loaded by my `~/.bash_profile`, and was working perfectly fine with GoSublime until the latest Sublime Text 3 update.

Given that the GoSublime plugin broke and not gvm, I'll continue using gvm and just hope the bug eventually gets addressed.

**Comment by DisposaBoy** [comment]
I'm not sure what the bug is supposed to be. The error log output shows that the `go` command doesn't exist and as I said, `$GOROOT/bin` should be included in `$PATH` but you haven't confirmed whether or not `$GOROOT/bin/go` exists, and is executable.

**Comment by cdelorme** [comment]
From a fresh terminal:

	$ echo $GOPATH
	/home/cdelorme/.gvm/pkgsets/go1.5.3/global

	$ echo $GOROOT
	/home/cdelorme/.gvm/gos/go1.5.3

	$ echo $PATH
	/home/cdelorme/.gvm/pkgsets/go1.5.3/global/bin:/home/cdelorme/.gvm/gos/go1.5.3/bin:/home/cdelorme/.gvm/pkgsets/go1.5.3/global/overlay/bin:/home/cdelorme/.gvm/bin:/home/cdelorme/.gvm/bin:/home/cdelorme/.bin:/home/cdelorme/.gvm/pkgsets/go1.5.3/global/bin:/home/cdelorme/.gvm/gos/go1.5.3/bin:/home/cdelorme/.gvm/pkgsets/go1.5.3/global/overlay/bin:/home/cdelorme/.gvm/bin:/home/cdelorme/.gvm/bin:/home/cdelorme/.nvm/versions/node/v5.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

	$ which go
	/home/cdelorme/.gvm/gos/go1.5.3/bin/go

So, `GOPATH` and `GOROOT` are set, `PATH` contains `GOPATH` and `GOROOT`, and go exists at `$GOROOT/bin/`.

**Comment by cdelorme** [comment]
I just reinstalled the plugin, and things appear to be working again.  Might have been a recent update, going to close this ticket.  Thank you for the update.
