### ISSUE TITLE
code hint incorrect

### ISSUE THREAD

**Issue by Geoferry** [DisposaBoy/GoSublime#678]
Hi, I have a question.

At beginning, I have a function in package "utils" like this:
`utils.Foo()`

Then I rearrange my code and make function Foo be a method of a structure "P".
Usually, GoSublime will give us a hint
 `p.Foo()` 
when I input 
`p.` 
But I don't know what happened, it didn't give me the hint.

However, when I input `utils.`, it gives me a hint `utils.Foo()`

How to fix it?

**Comment by DisposaBoy** [comment]
It sounds like your package data is stale i.e. the new code wasn't `go installed`
