### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by cers000** [DisposaBoy/GoSublime#679]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['', 'build', '-v', '-x', '-o', 'gosublime.margo_r16.01.09-1_go?.exe', 'gosubli.me/margo']`
|                > stdout: `
|                > stderr:`
|                > exception: `Cannot find command`go``
|   install state: busy
| sublime.version: 3103
| sublime.channel: stable
|       about.ann: a16.01.09-1
|   about.version: r16.01.09-1
|         version: r16.01.09-1
|        platform: windows-x64
|            ~bin: D:\ProgramFiles\sublimetext\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.01.09-1_go?.exe (missing)
|          go.exe: go (missing)
|      go.version: go?
|          GOROOT: D:/go_bin/
|          GOPATH: D:/go/
|           GOBIN: (not set) (should usually be`(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\Windows\system32\cmd.exe', '/C', '${CMD}']

**Comment by nvcnvn** [comment]
I have similar issue after update from go 1.5 to 1.6 by overide the old goroot folder.
An comment on https://github.com/jmoiron/sqlx/issues/203 point out that we need to clean the goroot folder and replace with only go 1.6, I try and it work.

**Comment by DisposaBoy** [comment]
@cers000 you appear to have set an incorrect `GOROOT`
