### ISSUE TITLE
How to debug gosublime's gocode?

### ISSUE THREAD

**Issue by nsf** [DisposaBoy/GoSublime#680]
Hi, I have a case where normal gocode works and provides proper autocompletion results, but GoSublime fails. How can I debug gocode in GoSublime? Does it have something like gocode's `-debug` mode?

**Comment by DisposaBoy** [comment]
Sorry for the late reply it seems I was unsubscribed from this repo.

Some info like `GOROOT`, `LibPath`, etc. is printed to the Sublime Text console when margo starts and when switching to a package. Other than that there's currently no other debugging option.

**Comment by nsf** [comment]
Ok thanks, never mind then.
