### ISSUE TITLE
Margo build failed

### ISSUE THREAD

**Issue by envy124** [DisposaBoy/GoSublime#684]
> cmd: `['C:\\Go\\bin\\go.exe', 'build', '-v', '-x', '-o', 'gosublime.margo_r16.03.22-1_go?.exe', 'gosubli.me/margo']`
> |                > stdout: ``
> |                > stderr:`WORK=~\AppData\Local\Temp\go-build081711602
> |                > net
> |                > mkdir -p $WORK\net_obj\
> |                > mkdir -p $WORK\
> |                > gosubli.me/something-borrowed/types
> |                > mkdir -p $WORK\gosubli.me\something-borrowed\types_obj\
> |                > mkdir -p $WORK\gosubli.me\something-borrowed\
> |                > cd C:\Go\src\net
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\net.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p net -buildid 0d4005a894cb120d96500f20ea8925c993bfd231 -D _/C_/Go/src/net -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Go\src\net\cgo_stub.go" "C:\Go\src\net\dial.go" "C:\Go\src\net\dial_gen.go" "C:\Go\src\net\dnsclient.go" "C:\Go\src\net\dnsmsg.go" "C:\Go\src\net\fd_mutex.go" "C:\Go\src\net\fd_poll_runtime.go" "C:\Go\src\net\fd_posix.go" "C:\Go\src\net\fd_windows.go" "C:\Go\src\net\file.go" "C:\Go\src\net\file_windows.go" "C:\Go\src\net\hook.go" "C:\Go\src\net\hook_windows.go" "C:\Go\src\net\hosts.go" "C:\Go\src\net\interface.go" "C:\Go\src\net\interface_windows.go" "C:\Go\src\net\ip.go" "C:\Go\src\net\iprawsock.go" "C:\Go\src\net\iprawsock_posix.go" "C:\Go\src\net\ipsock.go" "C:\Go\src\net\ipsock_posix.go" "C:\Go\src\net\lookup.go" "C:\Go\src\net\lookup_windows.go" "C:\Go\src\net\mac.go" "C:\Go\src\net\net.go" "C:\Go\src\net\parse.go" "C:\Go\src\net\pipe.go" "C:\Go\src\net\port.go" "C:\Go\src\net\race0.go" "C:\Go\src\net\sendfile_windows.go" "C:\Go\src\net\sock_posix.go" "C:\Go\src\net\sock_windows.go" "C:\Go\src\net\sockopt_posix.go" "C:\Go\src\net\sockopt_windows.go" "C:\Go\src\net\sockoptip_posix.go" "C:\Go\src\net\sockoptip_windows.go" "C:\Go\src\net\tcpsock.go" "C:\Go\src\net\tcpsock_posix.go" "C:\Go\src\net\tcpsockopt_posix.go" "C:\Go\src\net\tcpsockopt_windows.go" "C:\Go\src\net\udpsock.go" "C:\Go\src\net\udpsock_posix.go" "C:\Go\src\net\unixsock.go" "C:\Go\src\net\unixsock_posix.go"
> |                > cd ~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\gosubli.me\something-borrowed\types.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p gosubli.me/something-borrowed/types -complete -buildid 85855a6c71b256ff359e8af055b5c4ef78851b3a -D _/C_/Users/envy1/AppData/Roaming/Sublime_Text_3/Packages/GoSublime/src/gosubli.me/something-borrowed/types -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\api.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\builtins.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\check.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\const.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\conversions.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\errors.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\exportdata.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\expr.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\gcimporter.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\objects.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\operand.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\predicates.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\resolve.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\scope.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\sizes.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\stmt.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\types.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\types\universe.go"
> |                > crypto/x509
> |                > mkdir -p $WORK\crypto\x509_obj\
> |                > net/textproto
> |                > mkdir -p $WORK\crypto\
> |                > cd C:\Go\src\crypto\x509
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\crypto\x509.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p crypto/x509 -complete -buildid f2bf64989feb8a133326121f4c081de9eaa2e29e -D _/C_/Go/src/crypto/x509 -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Go\src\crypto\x509\cert_pool.go" "C:\Go\src\crypto\x509\pem_decrypt.go" "C:\Go\src\crypto\x509\pkcs1.go" "C:\Go\src\crypto\x509\pkcs8.go" "C:\Go\src\crypto\x509\root.go" "C:\Go\src\crypto\x509\root_windows.go" "C:\Go\src\crypto\x509\sec1.go" "C:\Go\src\crypto\x509\verify.go" "C:\Go\src\crypto\x509\x509.go"
> |                > mkdir -p $WORK\net\textproto_obj\
> |                > mkdir -p $WORK\net\
> |                > cd C:\Go\src\net\textproto
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\net\textproto.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p net/textproto -complete -buildid 9ec27a3efde3d4e0292f9eea44ce40b26ef61e4e -D _/C_/Go/src/net/textproto -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Go\src\net\textproto\header.go" "C:\Go\src\net\textproto\pipeline.go" "C:\Go\src\net\textproto\reader.go" "C:\Go\src\net\textproto\textproto.go" "C:\Go\src\net\textproto\writer.go"
> |                > mime/multipart
> |                > mkdir -p $WORK\mime\multipart_obj\
> |                > mkdir -p $WORK\mime\
> |                > cd C:\Go\src\mime\multipart
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\mime\multipart.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p mime/multipart -complete -buildid c5986b2216e92995bd3bf54d5f6a4fbe69adbdec -D _/C_/Go/src/mime/multipart -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Go\src\mime\multipart\formdata.go" "C:\Go\src\mime\multipart\multipart.go" "C:\Go\src\mime\multipart\writer.go"
> |                > crypto/tls
> |                > mkdir -p $WORK\crypto\tls_obj\
> |                > cd C:\Go\src\crypto\tls
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\crypto\tls.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p crypto/tls -complete -buildid 25c92ef0abe34ecd66834a8e33fef668bd4e964f -D _/C_/Go/src/crypto/tls -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Go\src\crypto\tls\alert.go" "C:\Go\src\crypto\tls\cipher_suites.go" "C:\Go\src\crypto\tls\common.go" "C:\Go\src\crypto\tls\conn.go" "C:\Go\src\crypto\tls\handshake_client.go" "C:\Go\src\crypto\tls\handshake_messages.go" "C:\Go\src\crypto\tls\handshake_server.go" "C:\Go\src\crypto\tls\key_agreement.go" "C:\Go\src\crypto\tls\prf.go" "C:\Go\src\crypto\tls\ticket.go" "C:\Go\src\crypto\tls\tls.go"
> |                > net/http
> |                > mkdir -p $WORK\net\http_obj\
> |                > cd C:\Go\src\net\http
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\net\http.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p net/http -complete -buildid f8e3fdcec6c92d00af8b12f4e0f35eae98e3bc3e -D _/C_/Go/src/net/http -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Go\src\net\http\client.go" "C:\Go\src\net\http\cookie.go" "C:\Go\src\net\http\doc.go" "C:\Go\src\net\http\filetransport.go" "C:\Go\src\net\http\fs.go" "C:\Go\src\net\http\header.go" "C:\Go\src\net\http\jar.go" "C:\Go\src\net\http\lex.go" "C:\Go\src\net\http\request.go" "C:\Go\src\net\http\response.go" "C:\Go\src\net\http\server.go" "C:\Go\src\net\http\sniff.go" "C:\Go\src\net\http\status.go" "C:\Go\src\net\http\transfer.go" "C:\Go\src\net\http\transport.go"
> |                > net/http/pprof
> |                > mkdir -p $WORK\net\http\pprof_obj\
> |                > net/rpc
> |                > mkdir -p $WORK\net\http\
> |                > cd C:\Go\src\net\http\pprof
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\net\http\pprof.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p net/http/pprof -complete -buildid 92d020c9e1e7c259a38d5c04d42d77dd94d13837 -D _/C_/Go/src/net/http/pprof -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Go\src\net\http\pprof\pprof.go"
> |                > mkdir -p $WORK\net\rpc_obj\
> |                > cd C:\Go\src\net\rpc
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\net\rpc.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p net/rpc -complete -buildid 2c86d84f9997a00402fcd8ac8be68b632e9428b2 -D _/C_/Go/src/net/rpc -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Go\src\net\rpc\client.go" "C:\Go\src\net\rpc\debug.go" "C:\Go\src\net\rpc\server.go"
> |                > gosubli.me/something-borrowed/gocode
> |                > mkdir -p $WORK\gosubli.me\something-borrowed\gocode_obj\
> |                > cd ~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\gosubli.me\something-borrowed\gocode.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p gosubli.me/something-borrowed/gocode -complete -buildid 430f3a66f4e655f6cc67e6574d7d77ca083a71d8 -D _/C_/Users/envy1/AppData/Roaming/Sublime_Text_3/Packages/GoSublime/src/gosubli.me/something-borrowed/gocode -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -pack "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\autocompletecontext.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\autocompletefile.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\client.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\config.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\cursorcontext.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\decl.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\declcache.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\formatters.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\gocode.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\gosublime_gocode_bridge.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\os_windows.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\package.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\ripper.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\rpc.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\scope.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\server.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\something-borrowed\gocode\utils.go"
> |                > gosubli.me/margo
> |                > mkdir -p $WORK\gosubli.me\margo_obj\
> |                > mkdir -p $WORK\gosubli.me\margo_obj\exe\
> |                > cd ~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo
> |                > "C:\Go\pkg\tool\windows_amd64\compile.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\gosubli.me\margo.a" -trimpath "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -p main -complete -buildid a83838c78bab3ce20ea8e60703e13d86fa8708d1 -D _/C_/Users/envy1/AppData/Roaming/Sublime_Text_3/Packages/GoSublime/src/gosubli.me/margo -I "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -I "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\pkg\windows_amd64" -pack "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\broker.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\common.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\fx.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\g_autoinst.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_declarations.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_doc.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_env.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_fmt.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_gocode.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_hello.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_import_paths.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_imports.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_kill.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_lint.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_ping.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_pkg.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_pkgdirs.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_pkgdoc.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_pkgpaths.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_play.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_sh.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\m_share.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\main.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\oom.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\pkgpaths.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\registry.go" "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosubli.me\margo\srcpkg1.4.go"
> |                > cd .
> |                > "C:\Go\pkg\tool\windows_amd64\link.exe" -o "C:\Users\envy1\AppData\Local\Temp\go-build081711602\gosubli.me\margo\_obj\exe\a.out.exe" -L "C:\Users\envy1\AppData\Local\Temp\go-build081711602" -L "C:\Users\envy1\AppData\Roaming\Sublime Text 3\Packages\GoSublime\pkg\windows_amd64" -extld=gcc -buildmode=exe -buildid=a83838c78bab3ce20ea8e60703e13d86fa8708d1 "C:\Users\envy1\AppData\Local\Temp\go-build081711602\gosubli.me\margo.a"
> |                > cp $WORK\gosubli.me\margo_obj\exe\a.out.exe gosublime.margo_r16.03.22-1_go?.exe
> |                > go install gosubli.me/margo: open gosublime.margo_r16.03.22-1_go?.exe: The filename, directory name, or volume label syntax is incorrect.`
> |                > exception:`None`
> |   install state: busy
> | sublime.version: 3103
> | sublime.channel: stable
> |       about.ann: a16.03.22-1
> |   about.version: r16.03.22-1
> |         version: r16.03.22-1
> |        platform: windows-x64
> |            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
> |       margo.exe: ~bin\gosublime.margo_r16.03.22-1_go?.exe (missing)
> |          go.exe: C:\Go\bin\go.exe (ok)
> |      go.version: go?
> |          GOROOT: C:\Go\
> |          GOPATH: $YOUR_OWN_GOPATH:$PATH_TO_APPENGINE/goroot
> |           GOBIN: (not set) (should usually be`(not set)`)
> |       set.shell: []
> |       env.shell: 
> |       shell.cmd: ['C:\WINDOWS\system32\cmd.exe', '/C', '${CMD}']

**Comment by DisposaBoy** [comment]
It seems to be unable to detect the Go version. What's the output of running the command `go version`
