### ISSUE TITLE
GOPATH, GS_GOPATH and GB with GoSublime

### ISSUE THREAD

**Issue by kakysha** [DisposaBoy/GoSublime#687]
I'm using [GB](https://getgb.io) (project-based build tool for Go), that puts all the dependencies packages in /vendor subfolder of your project. So, your packages are in project/src and all the  imports paths are resolved against project/vendor/src.
I was trying to get autocompletion to work with my environment, but with no success.

What I have:
project/ - Sublime Text 3 project folder
project/src/hello/hello.go - my main package
project/vendor/src/github.com/uber/uber.go - my uber dependecy

My User-settings file for GoSublime:

```
{
    "use_gs_gopath": false,
     "env": {
                "GOPATH": "$GOPATH:$GS_GOPATH:$GS_GOPATH/vendor"
            }
}
```

`env GOPATH GS_GOPATH` output:

```
{
        "GOPATH": "C:\\go:C:\\work\\project:C:\\work\\project/vendor", 
        "GS_GOPATH": "C:\\work\\project"
    }
```

Notice: I think the problem is in colons and slashes and backslashes here ^^^^

hello.go:

```
package main

import (
    "github.com/uber/uber"
)
```

and I can't make `uber.` autocompletion to work

P.S. using both win and osx, so the configuration must be crossplatform

**Comment by DisposaBoy** [comment]
On windows the list separator is semi-colon `;` not colon `:`

**Comment by kakysha** [comment]
Tried both semicolons, colons, slashes, double backslashes - no effect. Also, look at my P.S.

**Comment by DisposaBoy** [comment]
Some debugging info should be printed in the Sublime Text console like what package `gocode` is currently working with; maybe that gives some clues. R.e. your `P.S.`: the `GOPATH` configuration above is Windows-specific, it can't work on OS X.

Also note that I don't use `gb`, so I'm assuming the configured paths are actually correct.

**Comment by shuhaowu** [comment]
I have a similar issue, am on Linux and I cannot get goimports to import the package in vendor. Autocompletion works if i manually import. Running goimports from command line with the correct GOPATH export also works, just not under GoSublime. anyway to make GS output more debugging info?

**Comment by wolfgangmeyers** [comment]
I'm also not seeing code completion for packages in vendor. On ubuntu 16.04.

**Comment by paraboul** [comment]
Looks like gb is using a different separator for generated .a file in pkg. (and GoCode is looking for .a files for completion)

https://github.com/constabulary/gb/issues/634

```
[09:34:30] margo: agent#010: log: Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/paraboul/go/src/git.xxx.com/x.yyy.com/api-server/vendor/pkg/linux_amd64:/home/paraboul/go/src/git.xxx.com/x.yyy.com/api-server/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/paraboul/go/src/git.xxx.com/x.yyy.com/api-server/vendor:/home/paraboul/go/src/git.xxx.com/x.yyy.com/api-server", InstallSuffix:""}
```
`linux_amd64` vs `linux-amd64`

Haven't found a proper fix yet...

**Comment by kakysha** [comment]
@paraboul proper fix is to abandon gb already :)

**Comment by DisposaBoy** [comment]
@paraboul, @kakysha  is right. GB and other non-official and/or un-released (vgo) build tools are not supported.

**Comment by paraboul** [comment]
I know it's out of scope. For readers informations : simple work around is
a symlink into pkg (e.g. linux-amd64 -> linux_amd64)
