### ISSUE TITLE
SUPPORT.md

### ISSUE THREAD

**Issue by DisposaBoy** [DisposaBoy/GoSublime#689]
This issue is used to track issues and discussion about the SUPPORT.md file

**Comment by renzhaojing** [comment]
- [ ] 

### > [``](# url)

**Comment by WheresWardy** [comment]
Sublime Text 3 is a paid upgrade, and Sublime Text 2 still works perfectly fine for me, so I'm not interested in upgrading right now.

I've not got a problem with GoSublime no longer being supported on ST2, but is there some way I can suppress the warning message from appearing every time I start it? Assuming there will no longer be any updates to ST2, I'm happy to leave some combination of ST2 and GoSublime in a "working" state without support updates.

**Comment by DisposaBoy** [comment]
Depending on when you bought that license, it might still be valid for ST3. If you don't mind pressing escape every so often to dismiss the popup that reminds you to buy a license, you don't need to buy one. You could also patch the dialog out if you're feeling adventurous.

I believe this commit was the first to break backward compatibility https://github.com/DisposaBoy/GoSublime/commit/c0c5fffc088effdde6e42b0ff585301ae4f65965 checking out any commit before that should work. It might turn out to be a waste of time though because if completion isn't already broken then it will be when Go 1.7 comes (beta coming in the next week or so)

**Comment by qq737310694** [comment]
Sublime Text 2 is so good to use highlight ablity which ST3 does not have.

**Comment by DisposaBoy** [comment]
@qq737310694 what is `highlight ablity`
