### ISSUE TITLE
fmt on save is not working on OSX

### ISSUE THREAD

**Issue by hbejgel** [DisposaBoy/GoSublime#693]
When I rune the command to Fmt and save manually it works just fine, but when I only save the file it is not fmt'd automatically.

My settings:

`
{
	"env": { "PATH": "$HOME/Documents/Projects/go/bin:$HOME/Documents/Projects/go/lib/bin:$PATH" ,
			 "GOPATH" : "$HOME/Documents/Projects/go",
			 "GOROOT" : "/usr/local/go" 
			},
	"shell": ["/bin/bash", "--login", "-c", "$CMD"]
}
`

**Comment by Eriken** [comment]
I am experiencing the same.
OS X 10.11.4
Sublime 2.0.2 build 2221
GoSublime 16.04.08-2

**Comment by DisposaBoy** [comment]
I'm going to assume this is the same issue as https://github.com/DisposaBoy/GoSublime/issues/688. If not, then re-open with some more details.

You should upgrade to Sublime Text 3. If you have a **good** reason to still be using Sublime Text 2 you can discuss that here https://github.com/DisposaBoy/GoSublime/issues/689.

You should've already read the CHANGELOG.md file that's opened on updated which tells you to read SUPPORT.md. See https://github.com/DisposaBoy/GoSublime/blob/master/SUPPORT.md#sublime-text, but you should read the whole file.

**Comment by hbejgel** [comment]
Sorry, I wasn't aware support for Sublime 2 had been discontinued, I updated to Sublime 3 and it works perfectly, thanks for the clarification.
