### ISSUE TITLE
can't jump to definition for libraries with dash (-) in name

### ISSUE THREAD

**Issue by voutasaurus** [DisposaBoy/GoSublime#694]
If a package has a `-` in its name then go will use whatever is before the `-` as the package name in code that uses that package. GoSublime appears to not be able to lookup on the short package name.

Reproduce: 

Create a package called `x-y` (in src) with a function Do(). Use from another package:

```
package main

import "x-y"

func main() {
  println(x.Do())
}
```

Try to jump to definition on `x.Do`. (osx: cmd+dot+g)

Got:
// GsDoc: no docs found

Expected:
to jump to the definition

**Comment by nathanboktae** [comment]
I'm seeing this too.

**Comment by voutasaurus** [comment]
I use vim with vim-go now so I never did figure out what the underlying cause of the problem was here. Sorry I can't be more help
