### ISSUE TITLE
toggle comment shortcut on Ubuntu broken

### ISSUE THREAD

**Issue by AndreasBriese** [DisposaBoy/GoSublime#697]
shortcut 'ctrl+/' to toggle comment for current line / selected lines is not working on SublimeText3 / Ubuntu 16.04 LTS  / installed via package control this week.

**Comment by DisposaBoy** [comment]
I can't reproduce that. There might be some errors in the Sublime Text console.

**Comment by AndreasBriese** [comment]
Hey,

Maybe it's a problem with non-QWERTY keyboard layouts?
But i use your goSublime since three years now (on OSX) and never had this problem before this recent setup on Ubuntu. 

Cheers

Am 28.04.2016 um 21:18 schrieb DisposaBoy <notifications@github.com>:

> I can't reproduce that. There might be some errors in the Sublime Text console.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

Mit freundlichen Grüßen

Andreas Briese

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
eduToolbox@Bri-C GmbH
Bri-C Vet-Institut GbR
Auf der Bleiche 2a
31157 Sarstedt

Geschäftsführung:
Dr. med. vet. Andreas Briese
Landesbeauftragter für den Tierschutz des Landes Niedersachsen a. D.
Fachtierarzt für Tierschutzkunde
Fachtierarzt für Tierhygiene
Fax: 05066 695 82 18
O2mobil: 0176 623 537 89
E-Mail: info@eduToolbox.de 
WWW: http://edutoolbox.de

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
This message is intended exclusively for the addressee. It may contain
information that is confidential. Any use or publication of this
e-mail message without permission of the sender is not allowed.

**Comment by DisposaBoy** [comment]
Open the Sublime console and call `sublime.log_commands(True)` and then try to toggle the comment. The command that's run will be printed in the console and should be something like `command: toggle_comment {"block": false}`. Call `sublime.log_commands(False)` to disable it again.

**Comment by AndreasBriese** [comment]
log_commands(True) prints out
move_to_group {"group":6}  for ctrl+shift+7 (this is the usual toggle comment key)
focus_group{"group":6} for ctrl+7 

but does not toggle of course

Andreas


Am 28.04.2016 um 21:31 schrieb DisposaBoy <notifications@github.com>:

**Comment by AndreasBriese** [comment]
i might ad that i freshly installed ubunt 16.04 on 4 Macs and Ubuntu 12.04 on six PCs, all manually switched to DE key layout, for a golang training course with submlimetext3 on monday (all qwertz keyboards) and it does not work on all of them.


Am 28.04.2016 um 21:31 schrieb DisposaBoy <notifications@github.com>:

> Open the Sublime console and call sublime.log_commands(True) and then try to toggle the comment. The command that's run will be printed in the console and should be something like command: toggle_comment {"block": false}. Call sublime.log_commands(False) to disable it again.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

Mit freundlichen Grüßen

Andreas Briese

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
eduToolbox@Bri-C GmbH
Bri-C Vet-Institut GbR
Auf der Bleiche 2a
31157 Sarstedt

Geschäftsführung:
Dr. med. vet. Andreas Briese
Landesbeauftragter für den Tierschutz des Landes Niedersachsen a. D.
Fachtierarzt für Tierschutzkunde
Fachtierarzt für Tierhygiene
Fax: 05066 695 82 18
O2mobil: 0176 623 537 89
E-Mail: info@eduToolbox.de 
WWW: http://edutoolbox.de

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
This message is intended exclusively for the addressee. It may contain
information that is confidential. Any use or publication of this
e-mail message without permission of the sender is not allowed.

**Comment by DisposaBoy** [comment]
I guess the solution is to file a bug with Sublime Text, or add a binding to the correct command e.g. `{ "keys": ["ctrl+shift+7"], "command": "toggle_comment" }`

**Comment by AndreasBriese** [comment]
Am 28.04.2016 um 22:19 schrieb DisposaBoy <notifications@github.com>:

> add a binding to the correct command e.g. { "keys": ["ctrl+shift+7"], "command": "toggle_comment" }

where does this need to added? in the goSublime default key-binding file??

**Comment by DisposaBoy** [comment]
It should be added to your `user` key bindings. `Preferences menu > Key Bindings - User`. The file is an array, so it should look like:

	[
		{ "keys": ["ctrl+shift+7"], "command": "toggle_comment" }
	]

**Comment by AndreasBriese** [comment]
solved
