### ISSUE TITLE
code hint does not work in one situation

### ISSUE THREAD

**Issue by hxiaodon** [DisposaBoy/GoSublime#699]
Hi,
I installed the Sublime 3 at Mac OS with gosublime plugin
The code hint worked OK before I update the gosublime plugin to latest 

I encounter the following problem
![image](https://cloud.githubusercontent.com/assets/10990210/14947051/57ef5156-105f-11e6-8e59-1d5f4ca8db66.png)

logs.Logger is a variable with interface type(seelog.LoggerInterface) . I could get the code hint when I type logs.Logger (Info Infof Error Errorf will be popped) with the old gosublime plugin

But with the latest gosublime plugin, I have to import the wrapped seelog package explicitly and use type assertion against logs.Logger to achieve the goal.

Any suggestion for it? Thanks~

**Comment by beast** [comment]
Same here, the latest update broke code hints...
