### ISSUE TITLE
Execute multiple on-save commands

### ISSUE THREAD

**Issue by josharian** [DisposaBoy/GoSublime#700]
First, thanks so very much for GoSublime.

goimports routinely times out for me; I have a slow drive and a large GOPATH, so increasing the timeout only goes so far. I can live with this, but when goimports times out, my code doesn't get gofmt'd either.

What I'd like to do is first gofmt the code (fast) and then goimports the code (best effort). I think the simplest way to do this is for GS to accept a list of on-save commands. Semantics: The commands are run serially. If a command fails, execution stops there. Timeout could be either global or reset per-command.

Other places to fix this are: add a timeout flag to goimports (hard to implement, kinda weird), write a wrapper script (not general purpose, not immediately available to others), fix goimports to be faster (very, very hard to implement).

What do you think? I'd be willing to take a hand at a PR (pointers appreciated).

**Comment by DisposaBoy** [comment]
I can fmt the code before passing it on to `fmt_cmd`. The timeout is for the ipc system not `goimports` and I don't really want to add any more options (there are far too many already) or more special-cases for `goimports`. I guess I don't understand why it has to be so slow. I see that its logic is inside a package(I don't like core functionality depending on calling commands) so if it does caching I can add it as part of margo but the problem there is that I don't use `goimports`, so I'll most likely never know when it needs updating or when it breaks.

**Comment by josharian** [comment]
> I can fmt the code before passing it on to fmt_cmd. 

That would be fabulous and would solve this issue entirely as far as I'm concerned. Everything else that follows is just chatter. :)

> I guess I don't understand why it has to be so slow.

In the worst case--it is trying to find an exported symbol that just doesn't exist--it has to load and parse all the code in your GOPATH.

>  I see that its logic is inside a package

It is. You should certainly feel free to use it as such. And if you encounter problems, file a bug (golang.org/issue) and cc me (@josharian). I have in the past helped to maintain it.

> if it does caching I can add it as part of margo

It doesn't do caching. Two challenges: (1) Appropriate cache invalidation and (2) where to store the cache? Cache invalidation in theory could use directory mtime, maybe, but I worry about OS variation. It is possible we could change the API to allow a caller (margo) to provide a means to store the cache, which would solve the second problem.

The long term, ideal thing would be to have file system notifications and automatically (and silently) spin off a goimports daemon that keeps track of everything. That's just waiting for @nathany to figure out the notifications piece once and for all, and get it into a place where goimports can reasonably get at it. :) (Nathan, if you want to discuss with me privately, send me an email.)

> I'll most likely never know when it needs updating or when it breaks

goimports has been quite stable for a while, and is kept stable at tip, so you could (e.g.) just update to the latest goimports as part of rolling a release.

**Comment by DisposaBoy** [comment]
If caching is to be done, it can store it in memory directly or via the caller. If all it needs (I didn't read the code) is the list of exports then it can also provide some way for the caller to resolve them which would be ideal in a client like MarGo because it already has to parse packages, etc.

MarGo already assumes the user's file system isn't broken (the pkg imports <kbd>ctrl+.</kbd>,<kbd>ctrl+p</kbd> does caching), so I wouldn't worry too much about mtime.

**Comment by josharian** [comment]
Interesting. Let me think about it a bit.

I saw the commit you added. Thanks you; that is going to make me so happy.
