### ISSUE TITLE
i do not know the error

### ISSUE THREAD

**Issue by windlybobo** [DisposaBoy/GoSublime#703]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.05.07-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                >`
|                > stderr: `
|                > go: cannot find GOROOT directory: $HOME\bin\go
|                >`
|                > exception: `None`
|   install state: busy
| sublime.version: 3103
| sublime.channel: stable
|       about.ann: a16.05.07-1
|   about.version: r16.05.07-1
|         version: r16.05.07-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.05.07-1_go?.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: $HOME/bin/go
|          GOPATH: $HOME/golang
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\Windows\system32\cmd.exe', '/C', '${CMD}']

**Comment by zhuharev** [comment]
> | > stderr:  | > go: cannot find GOROOT directory: $HOME\bin\go | >

GOROOT sould be `$HOME/go`, not `$HOME/bin/go`
