### ISSUE TITLE
Margo: fetching import paths up to 11 seconds

### ISSUE THREAD

**Issue by zhuharev** [DisposaBoy/GoSublime#704]
After last update, command `ctrl+.+p` makes for 11 seconds. 

In status bar I see "Margo fetching import paths".

**Comment by DisposaBoy** [comment]
If you have lots of non-Go files in your `GOPATH` press <kbd>ctrl+.</kbd>,<kbd>ctrl+.</kbd> and type `Edit MarGo Extension`

You can use a program like below to filter out whatever directory or file you don't want to search,
 like `node_modules`. After saving, restart Sublime Text.


	package gosublime

	import (
		"disposa.blue/margo"
		"disposa.blue/margo/meth/importpaths"
		"path/filepath"
		"strings"
	)

	func init() {
		margo.Configure(func(o *margo.Opts) {
			o.ImportPaths = importpaths.MakeImportPathsFunc(func(path string) bool {
				// note: the default filter includes node_modules

				// use the default filter
				return importpaths.PathFilter(path) &&
					// don't descened into huge node_modules directory
					!strings.Contains(path, filepath.Base("node_modules"))
			})
		})
	}
