### ISSUE TITLE
Import official packages with prefix "pkg"

### ISSUE THREAD

**Issue by howcrazy** [DisposaBoy/GoSublime#705]
After update plugin this month, pressing `super+dot`,`super+p` will import package with prefix "pkg"
like
`import (
    "time"
)`
will be
`import (
    "pkg/time"
)`

on OSX
user setting is
`{
    "env": {
    	"GOPATH": "/Users/crazy/work/server",
        "GOROOT": "/usr/local/go"
    }
}`
and project setting is
`"GoSublime": {
	"env": {
		"GOPATH": "/Users/crazy/work/server"
	}
}`

**Comment by DisposaBoy** [comment]
What version of go are you using? Such package layout (`GOROOT/src/pkg`) was changed in `go1.4` 2 years ago IIRC

**Comment by DisposaBoy** [comment]
Also make sure you've read https://github.com/DisposaBoy/GoSublime/blob/master/SUPPORT.md

**Comment by howcrazy** [comment]
Thx!  I updated golang to version 1.6 then it fixed.
