### ISSUE TITLE
GoSublime error: MarGo build failed - disposa.blue/something-borrowed/types errors

### ISSUE THREAD

**Issue by bkize** [DisposaBoy/GoSublime#707]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\dev\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.05.07-1_go1.6.2.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                >`
|                > stderr: `
|                > disposa.blue/margo
|                > disposa.blue/something-borrowed/types
|                > net
|                > disposa.blue/margo/meth/importpaths
|                > # disposa.blue/something-borrowed/types
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\api.go:34: undefined: Object
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\api.go:51: undefined: Type
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\api.go:61: undefined: Type
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\api.go:67: undefined: Field
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\api.go:72: undefined: Type
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\api.go:84: undefined: Package
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\api.go:93: undefined: Package
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\api.go:98: undefined: Package
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\check.go:24: undefined: Package
|                > ..\..\..\..\GoSublime\src\disposa.blue\something-borrowed\types\check.go:24: too many errors
|                > crypto/x509
|                > net/textproto
|                > mime/multipart
|                > crypto/tls
|                > net/http
|                > net/http/pprof
|                > net/rpc
|                > disposa.blue/something-borrowed/gocode
|                >`
|                > exception: `None`
|   install state: busy
| sublime.version: 3113
| sublime.channel: dev
|       about.ann: a16.05.07-1
|   about.version: r16.05.07-1
|         version: r16.05.07-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.05.07-1_go1.6.2.exe (missing)
|          go.exe: C:\dev\Go\bin\go.exe (ok)
|      go.version: go1.6.2
|          GOROOT: C:\dev\Go\
|          GOPATH: ~\dev\Go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\WINDOWS\system32\cmd.exe', '/C', '${CMD}']

**Comment by zhuharev** [comment]
Same error on linux-64

| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/go/bin/go', 'build', '-tags', 'gosublime', '-v', '-o', 'gosublime.margo_r16.05.07-1_go1.6.2.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > disposa.blue/margo
|                > net
|                > disposa.blue/margo/meth/importpaths
|                > disposa.blue/something-borrowed/types
|                > gosublime
|                > # gosublime
|                > ../../src/gosublime/gosublime.go:9: undefined: importpaths in importpaths.MakeImportPathsFunc
|                > ../../src/gosublime/gosublime.go:13: undefined: importpaths in importpaths.PathFilter
|                > ../../src/gosublime/gosublime.go:15: undefined: strings in strings.Contains
|                > ../../src/gosublime/gosublime.go:15: undefined: filepath in filepath.Base
|                > ../../src/gosublime/gosublime.go:16: undefined: strings in strings.Contains
|                > ../../src/gosublime/gosublime.go:16: undefined: filepath in filepath.Base
|                > crypto/x509
|                > net/textproto
|                > mime/multipart
|                > crypto/tls
|                > net/http
|                > net/http/pprof
|                > net/rpc
|                > disposa.blue/something-borrowed/gocode
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3083
| sublime.channel: stable
|       about.ann: a16.05.07-1
|   about.version: r16.05.07-1
|         version: r16.05.07-1
|        platform: linux-x64
|            ~bin: ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/bin
|       margo.exe: ~bin/gosublime.margo_r16.05.07-1_go1.6.2.exe (missing)
|          go.exe: /usr/local/go/bin/go (ok)
|      go.version: go1.6.2
|          GOROOT: /usr/local/go
|          GOPATH: ~/go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']

**Comment by DisposaBoy** [comment]
I don't know what could cause that except a broken Go installation.

**Comment by zhuharev** [comment]
where I can found `../../src/gosublime/gosublime.go file?`

**Comment by DisposaBoy** [comment]
You mean you didn't create that file yourself? It should be at `Packages/User/Sublime/src/gosublime/gosublime.go` or pressing <kbd>ctrl+dot</kbd><kbd>ctrl+x</kbd> should open it

**Comment by zhuharev** [comment]
My problem(#704) solved. I have errors in `gosublime.go` file. @BKize try reinstall gosublime

**Comment by BKize** [comment]
Reinstall fixed the issue. Thanks.
