### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by DisposaBoy** [DisposaBoy/GoSublime#71]
You may be notified by GoSublime that GOPATH and/or GOROOT are unset.
There is a long-standing bug? that affects GoSublime wherein it cannot see the environment variables that you set in your shell (~/.bashrc, ~/.profile, etc.). This has been reported on OS X and Ubuntu. The problem appears to be that the shell variables are not passed passed to GUIs(ST2 in this case) which is beyond GoSublime. Unfortunately, there doesn't seem to be a solution beyond configuring your system to make that happen. I don't want to give bad advice about how to configure one's system... therefore, my advice in this situation is simply to add `GOROOT` and `GOPATH` to the GS settings file in `Packages/User/GoSublime.sublime-settings` which can be accessed via the menu `Preferences > Package Settings > GoSublime > Settings - User`. the `PATH` is amended automatically to include `GOROOT/bin` and `GOPATH*/bin`. An example config entry is:

```
"env": {
    "GOPATH": "$HOME/go",
    "GOROOT": "/go"
}
```

**Comment by TannerMoore** [comment]
I took gtczap's advice and shuffled my .bashrc export settings to my .profile and it was fixed after a quick logout/login.
