### ISSUE TITLE
Support for custom gutter theme

### ISSUE THREAD

**Issue by melvinodsa** [DisposaBoy/GoSublime#712]
Is there a way so that sublimelinter gutter theme is not blocked by GoSublime

**Comment by DisposaBoy** [comment]
I don't know what exactly *blocking* means here, but it you mean it's overriding its icons, then I guess you have to disable gslint or bring the issue to Sublime HQ because Sublime Text doesn't support having multiple icons in the gutter or a proper way to prioritise a plugin's icons.

**Comment by melvinodsa** [comment]
By blocking I meant the icons I put for the gutter theme is getting overriden by GoSublime grey dots. Since Sublime doesn't support prioritizing gutter theme, is there a way GoSublime enables custom icon instead of grey dots?

**Comment by DisposaBoy** [comment]
> By blocking I meant the icons I put for the gutter theme is getting overriden by GoSublime grey dots

If you're using sublimelinter anyway you might as well set it up to us to to linting for Go as well.

> Since Sublime doesn't support prioritizing gutter theme, is there a way GoSublime enables custom icon instead of grey dots?

There's no support and I don't have any plans to add any support - maybe when I finish moving all the Python to Go.

If it bothers you, you can change the icon `dot` and syntax `comment` in `gslint.py` to whatever you like on these lines

https://github.com/DisposaBoy/GoSublime/blob/master/gslint.py#L105
https://github.com/DisposaBoy/GoSublime/blob/master/gslint.py#L110

docs for `add_regions` is on this page https://www.sublimetext.com/docs/3/api_reference.html

IIRC to set a custom icon you set it to `Packages/<package>/<path/to/icon>.png`

**Comment by melvinodsa** [comment]
Thanks  @DisposaBoy , that would do the work :+1:
