### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by lperry65** [DisposaBoy/GoSublime#713]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.05.07-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                >`
|                > stderr: `
|                > net
|                > disposa.blue/margo
|                > disposa.blue/something-borrowed/types
|                > disposa.blue/margo/meth/importpaths
|                > crypto/x509
|                > net/textproto
|                > mime/multipart
|                > crypto/tls
|                > net/http
|                > net/http/pprof
|                > net/rpc
|                > disposa.blue/something-borrowed/gocode
|                > disposa.blue/cmd/margo_pkg
|                > disposa.blue/cmd/margo
|                > go install disposa.blue/cmd/margo: open gosublime.margo_r16.05.07-1_go?.exe: The filename, directory name, or volume label syntax is incorrect.
|                >`
|                > exception: `None`
|   install state: busy
| sublime.version: 3114
| sublime.channel: stable
|       about.ann: a16.05.07-1
|   about.version: r16.05.07-1
|         version: r16.05.07-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.05.07-1_go?.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C:\Go\
|          GOPATH: /d/dev/go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\Windows\system32\cmd.exe', '/C', '${CMD}']

**Comment by DisposaBoy** [comment]
What's the output of `go version`
