### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by ChrisGNZ** [DisposaBoy/GoSublime#715]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.05.07-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                >`
|                > stderr: `
|                > disposa.blue/margo
|                > disposa.blue/something-borrowed/types
|                > net
|                > disposa.blue/margo/meth/importpaths
|                > crypto/x509
|                > net/textproto
|                > mime/multipart
|                > crypto/tls
|                > net/http
|                > net/http/pprof
|                > net/rpc
|                > disposa.blue/something-borrowed/gocode
|                > disposa.blue/cmd/margo_pkg
|                > disposa.blue/cmd/margo
|                > go install disposa.blue/cmd/margo: open gosublime.margo_r16.05.07-1_go?.exe: The filename, directory name, or volume label syntax is incorrect.
|                >`
|                > exception: `None`
|   install state: busy
| sublime.version: 3114
| sublime.channel: stable
|       about.ann: a16.05.07-1
|   about.version: r16.05.07-1
|         version: r16.05.07-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.05.07-1_go?.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C:\Go\
|          GOPATH: C:\go;
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\Windows\system32\cmd.exe', '/C', '${CMD}']

**Comment by ChrisGNZ** [comment]
Extra note: I am running Sublime Text 3 on Windows 7 64bit.  I've tried running Sublime Text as Administrator as well, but that made no difference.  Thanks and gratitude in advance for any assistance! :-)

**Comment by DisposaBoy** [comment]
What's the output of `go version`

**Comment by ChrisGNZ** [comment]
go version go1.6.2 windows/amd64

**Comment by DisposaBoy** [comment]
That's strange. I don't know why it would fail to detect the version string. I just noticed that your `GOROOT` and `GOPATH` are the same (which they shouldn't be), maybe it's throwing an error about.

Open the Sublime Text console and run `from gosubl import sh; sh.go_cmd(['version']).run()`

**Comment by ChrisGNZ** [comment]
I will sort out the GOROOT and GOPATH and see if that helps, thanks for pointing that out! 

In the meantime here is the console output:

>>> from gosubl import sh; sh.go_cmd(['version']).run()
Result(out='go version go1.6.2 windows/amd64\n', cmd_lst=['C:\\Go\\bin\\go.exe', 'version'], err='', ok=True, exc=None)

**Comment by DisposaBoy** [comment]
That's really strange... I can't imagine how it can fail as that string looks just fine and works if I copy it.

When Sublime starts there should some output with what was seen at the time on the line that starts with `GoSublime ... sh: load env vars`, maybe there's a race condition or something.

**Comment by skidder** [comment]
I encountered a similar issue this morning. I was using Go 1.6.2 installed using brew on Mac OS X. My `GOROOT` had been specified incorrectly as `/usr/local/bin` in my GoSublime user preferences. I updated the `GOROOT` path to `/usr/local/opt/go/libexec` in my GoSublime user preferences and the Margo build succeeded:

```
{
	"env": { 
		"GOROOT": "/usr/local/opt/go/libexec"
	}
}
```

**Comment by ken880812** [comment]
I meet this problem too. After trying many times, I fund that, it is work if GOPATH in the seam volume. For example, on my PC go.exe install in D:\Go\bin, when the GOPATH set to D:\workspace, this problem does not a apper again.
