### ISSUE TITLE
Will GoSublime support 'Key Bindings - User'? 

### ISSUE THREAD

**Issue by wjm3219** [DisposaBoy/GoSublime#717]
Some default key-bindings for GoSublime are not so convenient, like 'cmd+. cmd+g' for 'Goto'. I changed it to 'ctrl+,' in 'key Bindings - default' . But when upgrated, 'Key Bindings - default' will be renewed, and I need to edit it. How about make GoSublime support 'Key Bindings - User'?

**Comment by DisposaBoy** [comment]
No, you should be editing *your own* key bindings file <kbd>Preferences > Key Bindings - User</kbd>
