### ISSUE TITLE
Spaces are replaced with tabs despite - "fmt_tab_indent": false

### ISSUE THREAD

**Issue by jhurwich** [DisposaBoy/GoSublime#718]
STR:
1. Have any .go document with lines beginning with spaces throughout. 
2. Install GoSublime and set "fmt_tab_indent": false in User settings (settings attached)
3. Save the .go document

Observed:
- All line-leading spaces are converted to tabs.

Expected:
- Line-leading spaces are kept as spaces.

Note: if GoSublime is disabled and tabs are converted back to spaces in the document with SublimeText, saving does NOT change them back to tabs.

[GoSublime-sublime-settings.txt](https://github.com/DisposaBoy/GoSublime/files/324154/GoSublime-sublime-settings.txt)

**Comment by jhurwich** [comment]
System Info:
Mac 10.11.4
SublimeText (3) Build 3114

**Comment by DisposaBoy** [comment]
`gofmt` indents with tabs so that setting no longer does anything.
