### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by coderKong** [DisposaBoy/GoSublime#719]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.06.02-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > go: cannot find GOROOT directory: D:\Go
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3114
| sublime.channel: stable
|       about.ann: a16.06.02-1
|   about.version: r16.06.02-1
|         version: r16.06.02-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.06.02-1_go?.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: D:/Go
|          GOPATH: D:/mygopath
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\Windows\\system32\\cmd.exe', '/C', '${CMD}']

**Comment by DisposaBoy** [comment]
Your `GOROOT` (and maybe your `GOPATH`) looks wrong. The `go` binary is on drive **C**: yet you set your `GOROOT` to **D**:. You should stop setting `GOROOT` or correct it.
