### ISSUE TITLE
gosublime error

### ISSUE THREAD

**Issue by chun49** [DisposaBoy/GoSublime#721]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/go/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.07.09-1_go1.6.2.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                >`
|                > stderr: `
|                > ../../../../GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:4:2: cannot find package "bufio" in any of:
|                >  ~/go/src/bufio (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/bufio (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/bufio
|                > ../../../../GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:5:2: cannot find package "bytes" in any of:
|                >  ~/go/src/bytes (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/bytes (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/bytes
|                > ../../../../GoSublime/src/disposa.blue/cmd/margo_pkg/common.go:5:2: cannot find package "encoding/base64" in any of:
|                >  ~/go/src/encoding/base64 (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/encoding/base64 (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/encoding/base64
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/package_bin.go:4:2: cannot find package "encoding/binary" in any of:
|                >  ~/go/src/encoding/binary (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/encoding/binary (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/encoding/binary
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/config.go:5:2: cannot find package "encoding/json" in any of:
|                >  ~/go/src/encoding/json (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/encoding/json (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/encoding/json
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/package_text.go:5:2: cannot find package "errors" in any of:
|                >  ~/go/src/errors (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/errors (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/errors
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/client.go:4:2: cannot find package "flag" in any of:
|                >  ~/go/src/flag (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/flag (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/flag
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:5:2: cannot find package "fmt" in any of:
|                >  ~/go/src/fmt (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/fmt (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/fmt
|                > ../../../../GoSublime/src/disposa.blue/margo/meth/importpaths/importpaths.go:5:2: cannot find package "go/ast" in any of:
|                >  ~/go/src/go/ast (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/go/ast (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/go/ast
|                > ../../../../GoSublime/src/disposa.blue/margo/opts.go:4:2: cannot find package "go/build" in any of:
|                >  ~/go/src/go/build (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/go/build (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/go/build
|                > ../../../../GoSublime/src/disposa.blue/margo/meth/importpaths/importpaths.go:7:2: cannot find package "go/parser" in any of:
|                >  ~/go/src/go/parser (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/go/parser (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/go/parser
|                > ../../../../GoSublime/src/disposa.blue/cmd/margo_pkg/common.go:10:2: cannot find package "go/printer" in any of:
|                >  ~/go/src/go/printer (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/go/printer (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/go/printer
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletefile.go:7:2: cannot find package "go/scanner" in any of:
|                >  ~/go/src/go/scanner (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/go/scanner (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/go/scanner
|                > ../../../../GoSublime/src/disposa.blue/margo/meth/importpaths/importpaths.go:8:2: cannot find package "go/token" in any of:
|                >  ~/go/src/go/token (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/go/token (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/go/token
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/config.go:7:2: cannot find package "io" in any of:
|                >  ~/go/src/io (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/io (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/io
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/client.go:7:2: cannot find package "io/ioutil" in any of:
|                >  ~/go/src/io/ioutil (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/io/ioutil (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/io/ioutil
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletefile.go:9:2: cannot find package "log" in any of:
|                >  ~/go/src/log (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/log (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/log
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/types/const.go:12:2: cannot find package "math/big" in any of:
|                >  ~/go/src/math/big (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/math/big (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/math/big
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/server.go:8:2: cannot find package "net" in any of:
|                >  ~/go/src/net (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/net (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/net
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/gocode.go:7:2: cannot find package "net/http" in any of:
|                >  ~/go/src/net/http (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/net/http (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/net/http
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/gocode.go:8:2: cannot find package "net/http/pprof" in any of:
|                >  ~/go/src/net/http/pprof (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/net/http/pprof (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/net/http/pprof
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/client.go:8:2: cannot find package "net/rpc" in any of:
|                >  ~/go/src/net/rpc (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/net/rpc (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/net/rpc
|                > ../../../../GoSublime/src/disposa.blue/cmd/margo_pkg/m_pkgdoc.go:8:2: cannot find package "net/url" in any of:
|                >  ~/go/src/net/url (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/net/url (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/net/url
|                > ../../../../GoSublime/src/disposa.blue/margo/meth/importpaths/importpaths.go:9:2: cannot find package "os" in any of:
|                >  ~/go/src/os (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/os (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/os
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/declcache.go:11:2: cannot find package "os/exec" in any of:
|                >  ~/go/src/os/exec (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/os/exec (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/os/exec
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:10:2: cannot find package "path" in any of:
|                >  ~/go/src/path (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/path (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/path
|                > ../../../../GoSublime/src/disposa.blue/margo/filter.go:4:2: cannot find package "path/filepath" in any of:
|                >  ~/go/src/path/filepath (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/path/filepath (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/path/filepath
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/config.go:10:2: cannot find package "reflect" in any of:
|                >  ~/go/src/reflect (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/reflect (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/reflect
|                > ../../../../GoSublime/src/disposa.blue/cmd/margo_pkg/m_lint.go:9:2: cannot find package "regexp" in any of:
|                >  ~/go/src/regexp (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/regexp (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/regexp
|                > package disposa.blue/cmd/margo
|                >  imports runtime: cannot find package "runtime" in any of:
|                >  ~/go/src/runtime (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/runtime (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/runtime
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:13:2: cannot find package "sort" in any of:
|                >  ~/go/src/sort (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/sort (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/sort
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/client.go:11:2: cannot find package "strconv" in any of:
|                >  ~/go/src/strconv (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/strconv (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/strconv
|                > ../../../../GoSublime/src/disposa.blue/margo/meth/importpaths/importpaths.go:11:2: cannot find package "strings" in any of:
|                >  ~/go/src/strings (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/strings (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/strings
|                > ../../../../GoSublime/src/disposa.blue/margo/opts.go:5:2: cannot find package "sync" in any of:
|                >  ~/go/src/sync (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/sync (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/sync
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/package_text.go:10:2: cannot find package "text/scanner" in any of:
|                >  ~/go/src/text/scanner (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/text/scanner (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/text/scanner
|                > ../../../../GoSublime/src/disposa.blue/margo/meth/importpaths/importpaths.go:13:2: cannot find package "time" in any of:
|                >  ~/go/src/time (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/time (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/time
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/package_bin.go:9:2: cannot find package "unicode" in any of:
|                >  ~/go/src/unicode (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/unicode (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/unicode
|                > ../../../../GoSublime/src/disposa.blue/something-borrowed/gocode/package_bin.go:10:2: cannot find package "unicode/utf8" in any of:
|                >  ~/go/src/unicode/utf8 (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/User/GoSublime/src/unicode/utf8 (from $GOPATH)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/unicode/utf8
|                >`
|                > exception: `None`
|   install state: busy
| sublime.version: 3114
| sublime.channel: stable
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: linux-x32
|            ~bin: ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x32/bin
|       margo.exe: ~bin/gosublime.margo_r16.07.09-1_go1.6.2.exe (missing)
|          go.exe: /usr/local/go/bin/go (ok)
|      go.version: go1.6.2
|          GOROOT: ~/go
|          GOPATH: ~/work
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']

**Comment by DisposaBoy** [comment]
your `GOROOT` looks wrong. you probably shouldn't be setting it at all
