### ISSUE TITLE
GoSublime error: MarGo build failed, go tool: no such tool "compile"

### ISSUE THREAD

**Issue by mdragonCN** [DisposaBoy/GoSublime#722]
I tried searching to resolve this myself, and tried removing and re-installing, but still get the same errors.  Apologize in advance if this is just something goofy with my environment.  This is not critical that I have this up and running this moment, I just opened Sublime for non-Go work and got the message

| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.07.09-1_go1.6.2.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > disposa.blue/margo
|                > go tool: no such tool "compile"
|                > disposa.blue/something-borrowed/types
|                > net
|                > go tool: no such tool "compile"
|                > go tool: no such tool "compile"
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3114
| sublime.channel: stable
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: windows-x64
|            ~bin: C:\progs\sublime\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.07.09-1_go1.6.2.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go1.6.2
|          GOROOT: C:\Go\
|          GOPATH: C:\git\go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\WINDOWS\\system32\\cmd.exe', '/C', '${CMD}']

**Comment by chrispassas** [comment]
I have a similar issue on OS X

```
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/opt/go/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.07.09-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > go: cannot find GOROOT directory: /usr/local/bin/go
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3118
| sublime.channel: dev
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r16.07.09-1_go?.exe (missing)
|          go.exe: /usr/local/opt/go/bin/go (ok)
|      go.version: go?
|          GOROOT: /usr/local/bin/go
|          GOPATH: ~/go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']
```

**Comment by chrispassas** [comment]
Sorry I now see this appears to be the same issue reported in #721

**Comment by mdragonCN** [comment]
I think your output is different from both mine and #721 

Yours seems to not find the path specified as the GOROOT, #721 seems to not find many packages within the GOROOT, and mine seems to not find a tooling executable: compile

**Comment by chrispassas** [comment]
I removed GOROOT from my bash_profile and it fixed the GoSublime error. I'll have to look at it more later to see why its not liking my GOROOT.

**Comment by DisposaBoy** [comment]
@mdragonCN it looks like your Go installation is broken. Mabe you've got files from multiples versions mixed together or you have some anti-virus software deleting files from your Go installation.

**Comment by DisposaBoy** [comment]
@chrispassas I don't know why you're setting `GOROOT`, but you seem to be setting it to the `go` binary which would be wrong.

**Comment by chrispassas** [comment]
@DisposaBoy you're right, once I removed that the error went away.

**Comment by mdragonCN** [comment]
@DisposaBoy This made it work when I did it manually from a cmd window:
cd \progs\sublime\Data\Packages\GoSublime\src\disposa.blue\cmd\margo
set GOPATH=C:\progs\sublime\Data\Packages\GoSublime
C:\Go\bin\go.exe build -tags -v -o gosublime.margo_r16.07.09-1_go1.6.2.exe disposa.blue/cmd/
margo

I had uninstalled 1.6.2 and installed 1.6.3 in the meantime, but after doing that the Sublime driven build still failed.
