### ISSUE TITLE
"GoSublime: Installing MarGo" each time I launch Sublime Text 3.

### ISSUE THREAD

**Issue by shurcooL** [DisposaBoy/GoSublime#729]
I've been seeing this happen for the last few weeks/months. It didn't happen before, rather it only happened when there was an update to a new version of GoSublime. But now it happens _every_ time I quit and launch Sublime Text 3.

It takes a couple seconds and feels quite annoying having to wait, especially since I can't do
<kbd>Cmd</kbd>+<kbd>.</kbd>, <kbd>Cmd</kbd>+<kbd>O</kbd> to start opening a Go package until it finishes.

I'm not sure if it's an issue in GoSublime, or Package Manager. I have that configured with default settings, which includes automatically updating packages. I don't mind that normally, but I've heard @DisposaBoy discourage that. Is it related to this issue?

Using Sublime Text 3, Dev Channel, Builds 3120. OS X 10.11.6. Go 1.7. Tried searching issues and surprisingly did not find this.

**Comment by shurcooL** [comment]
This happened for a long time from the time when I originally reported this, but I haven't seen it happen for many months now.

I'll wait a bit more and pay extra attention to this. If I still don't see any occurrences, I'll close this since it's likely resolved by now.

**Comment by DisposaBoy** [comment]
I think I missed this one.

If it happens again, look in the Sublime Text console for the line `> 	shell bootstrap took ...`. If it's taking more than 500ms in go1.10 it's worth improving.

**Comment by shurcooL** [comment]
I'm seeing:

```
# first time after system restart

> 	go version: `go1.10` (raw version string `go1.10`)
> 	shell bootstrap took 0.589s

# second time

> 	shell bootstrap took 0.216s

# third time

> 	shell bootstrap took 0.217s
```

The original issue is definitely long since resolved. Back when it was happening, it was very reproducible, and made ST3 time to interactive (when you're able to type and use it) as long as 4-6 seconds _each_ and every time you started ST3. That's not the case now.
