### ISSUE TITLE
Use new Phantoms API to show build errors inline

### ISSUE THREAD

**Issue by maxsz** [DisposaBoy/GoSublime#732]
From the sublime text [blog](https://www.sublimetext.com/blog/articles/sublime-text-3-build-3124):

> Build errors are now shown inline, at the location the error occurred. This is done via the new Phantoms API, which allows HTML annotations to be added to the text buffer by plugins:
> ![build_error](https://cloud.githubusercontent.com/assets/540025/18740250/0fa64e30-80a9-11e6-8189-546e3ba6f3c6.png)

[API documentation](http://www.sublimetext.com/docs/3/api_reference.html#sublime.Phantom)

**Comment by qmmp123** [comment]
Take a look on my solution
![screenshot_20161105_203719](https://cloud.githubusercontent.com/assets/6360702/20030067/7cfa84e6-a3a0-11e6-99a8-7514bd17e888.png)
![screenshot_20161105_203829](https://cloud.githubusercontent.com/assets/6360702/20030068/7d032d08-a3a0-11e6-9b5f-45088c8ce543.png)

**Comment by qmmp123** [comment]
https://github.com/DisposaBoy/GoSublime/pull/742

**Comment by dmkc** [comment]
Up 🐐  for this issue. super useful to see errors inline.

**Comment by DisposaBoy** [comment]
Do you know of a plugin that has a *good* implementation of phantoms and/or tooltips?

I tried them when these features were first released, but found them very annoying/distracting when they're activated automatically. The only use I can think of is to maybe replace the error palette (<kbd>ctrl+.</kbd>,<kbd>ctrl+e</kbd>) with phantoms.

**Comment by dmkc** [comment]
> The only use I can think of is to maybe replace the error palette 
Exactly. I don't know of any good implementations offhand but can dig into it.

**Comment by DisposaBoy** [comment]
I'm going to introduce the HUD as an alternative to popups and inline phantoms in the next release. See https://github.com/DisposaBoy/GoSublime/issues/846#issuecomment-440672086 for details.
