### ISSUE TITLE
GsFmt timing out in macOS Sierra

### ISSUE THREAD

**Issue by sb10** [DisposaBoy/GoSublime#736]
I upgraded to macOS 10.12 today, and now GsFmt doesn't work anymore. When I save a file I get a little pop-up error at the mouse pointer position that says:

> GoSublime: GsFmt: Blocking call(fmt) timed out after 1.000 second(s). you might need to increase the 'ipc_timeout' setting.

It's not an issue with the file I'm working on. It actually works fine the first few times I save after loading Sublime Text (build 3126). But after a while (a ~minute) I have a few gosublime.marge_r16.07.09-1_go.1.6.exe processes using 70% cpu each, my fans are blaring, and then I start getting the above error.

**Comment by sb10** [comment]
updating to go1.7 and/or installing gosublime by cloning the repo instead of using normal sublime text package management seems to have fixed the issue.

**Comment by Newt0n** [comment]
@sb10 same issue as you bro, awesome workaround 👍
