### ISSUE TITLE
go process spinning on my machine

### ISSUE THREAD

**Issue by cirel10** [DisposaBoy/GoSublime#738]
I've observed a process consuming ~60% CPU for hours, at seemingly random times during the day. Haven't paid enough attention to know what exactly causes it, I figure y'all will know what specifically invokes this process and why it would take so long.

Today I noticed it upon launching Sublime for the first time. Other days I've only become aware by the sound of my laptop's fan, sometimes hours after I've stopped using Sublime.

I've attached a sample, although this is taken after only about a minute of it running. If I notice it later maybe I can get you a sample after it's been running for many minutes.

Also attached sublime_output.txt which I noticed got logged when I killed this process. Maybe not that useful since I killed it manually after only maybe a minute.

[ps.txt](https://github.com/DisposaBoy/GoSublime/files/537316/ps.txt)
[sample.txt](https://github.com/DisposaBoy/GoSublime/files/537318/sample.txt)
[sublime_output.txt](https://github.com/DisposaBoy/GoSublime/files/537320/sublime_output.txt)

**Comment by feisan** [comment]
Yes, I met the same problem.

If I open a golang project with some large library (such as github.com/coreos/etcd/clientv3 and  google.golang.org/grpc), the GoSublime process would use ~65% CPU, and show some message like this:

GoSublime: GsFmt
Blocking Call(fmt) timed out after 1.000 second(s). You might need to increase the `ipc_timeout` setting

I had tried to install GoSublime with the trunk from repo, it couldn't resolve the problem.

**Comment by feisan** [comment]
I found something new.

I am using glide to manage my golang packages, and it installed all packages in the vendor folder. When I tried to move all files in the vendor folder to the top level source folder, and restart my sublime text, everything seems to be ok.

**Comment by idevz** [comment]
any update for this?
