### ISSUE TITLE
MarGo build failed

### ISSUE THREAD

**Issue by festum** [DisposaBoy/GoSublime#745]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['D:\\fe0\\bin\\go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.07.09-1_go1.7.3.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > runtime/internal/sys
|                > # runtime/internal/sys
|                > D:\fe0\bin\go\src\runtime\internal\sys\arch_amd64.go:8: undefined: AMD64
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3125
| sublime.channel: dev
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: windows-x64
|            ~bin: C:\fe0\bin\Sublime Text\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.07.09-1_go1.7.3.exe (missing)
|          go.exe: D:\fe0\bin\go\bin\go.exe (ok)
|      go.version: go1.7.3
|          GOROOT: D:\fe0\bin\go
|          GOPATH: D:\Dev\work\fe0\gimlet
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\WINDOWS\\system32\\cmd.exe', '/C', '${CMD}']

**Comment by go2run** [comment]
hi, did you solve this problem?
i meet it too, no idea...

**Comment by Juev** [comment]
#778
