### ISSUE TITLE
go1.8 gosublime not work

### ISSUE THREAD

**Issue by 285979593** [DisposaBoy/GoSublime#747]
Gocode pkg: "."
Gocode env: gocode.margoEnv{LibPath:"/usr/local/go/pkg/darwin_amd64:/Users/fuyun/Desktop/framework/1.8go/pkg/darwin_amd64", GOOS:"darwin", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/local/go", GOPATH:"/Users/fuyun/Desktop/framework/1.8go", InstallSuffix:""}
margo: 2016/12/26 23:28:00 broker.go:105: gocode_complete#mg9.autoken.c1977672-b694-4226-9714-89cfd39fa6d4 PANIC: One of the package cache updaters panicked
goroutine 65 [running]:
disposa.blue/cmd/margo_pkg.(*Broker).call.func1(0xc420160160, 0xc42000f5e0)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:104 +0xc2
panic(0x143e500, 0xc420136610)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
disposa.blue/something-borrowed/gocode.update_packages(0xc4202cf988)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:382 +0x1ef
disposa.blue/something-borrowed/gocode.(*auto_complete_context).update_caches(0xc420016a00)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:166 +0x1e1
disposa.blue/something-borrowed/gocode.(*auto_complete_context).apropos(0xc420016a00, 0xc4202e2000, 0x2c2, 0x300, 0xc4202dc0c0, 0x35, 0x1d6, 0x1, 0x1, 0xc4202dc0c0, ...)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/autocompletecontext.go:303 +0x1e6
disposa.blue/something-borrowed/gocode.(*margoState).Complete(0xc4200ac630, 0x0, 0x0, 0x0, 0xc4202ee160, 0xd, 0xc420136610, 0x1, 0x1, 0xc4202e2000, ...)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode/gosublime_gocode_bridge.go:78 +0x144
disposa.blue/cmd/margo_pkg.(*mGocode).completions(0xc4202ec200, 0xc4202e2000, 0x2c2, 0x300, 0xc4202dc0c0, 0x35, 0x1d6, 0xc42002ac00, 0x1051e10, 0xc42002ac00)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:95 +0x144
disposa.blue/cmd/margo_pkg.(*mGocode).Call(0xc4202ec200, 0x14f9668, 0xc420160160, 0xc42000f5e0, 0xc42006c190)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/m_gocode.go:76 +0x2cc
disposa.blue/cmd/margo_pkg.(*Broker).call(0xc42000f5e0, 0xc420160160, 0x16e7be0, 0xc4202ec200)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:113 +0x9a
disposa.blue/cmd/margo_pkg.(*Broker).worker(0xc42000f5e0, 0xc420071370, 0xc42006e4e0)
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:188 +0xda
created by disposa.blue/cmd/margo_pkg.(*Broker).Loop
	/Users/fuyun/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/cmd/margo_pkg/broker.go:209 +0x119

**Comment by Unknwon** [comment]
:sob: My sublime is dying!

**Comment by ckeyer** [comment]
+1

**Comment by sqhua** [comment]
+1

**Comment by Unknwon** [comment]
He updated! https://github.com/DisposaBoy/GoSublime/commit/241030c5ee79778d36440e790ec01f6be4f114ab
