### ISSUE TITLE
MarGo: Missing required environment variables: GOROOT

### ISSUE THREAD

**Issue by craigcosmo** [DisposaBoy/GoSublime#751]
Open sublime and I got this error in sublime console

`MarGo: Missing required environment variables: GOROOT`

**Comment by MACDfree** [comment]
![image](https://cloud.githubusercontent.com/assets/3363410/23006744/9dd8b432-f43e-11e6-8887-63b8fc827b53.png)

**Comment by craigcosmo** [comment]
I'm on the mac

**Comment by MACDfree** [comment]
GOROOT: go installation path
GOPATH: go workspace path
PATH: go bin path

**Comment by xavi-** [comment]
Yeah, every time I update.  GoSublime breaks  Quite irritating.

**Comment by PichuChen** [comment]
@craigcosmo GOROOT: /usr/local/go/

**Comment by MokeThirteen** [comment]
Go on high sierra is /usr/local/bin/go
