### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by msyarif04** [DisposaBoy/GoSublime#754]
When i open sublime text 3, i got this problem:

GoSublime: | GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r16.07.09-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > disposa.blue/margo
|                > net
|                > disposa.blue/margo/meth/importpaths
|                > disposa.blue/something-borrowed/types
|                > crypto/x509
|                > net/textproto
|                > mime/multipart
|                > net/http/httptrace
|                > crypto/tls
|                > net/http
|                > net/http/pprof
|                > net/rpc
|                > disposa.blue/something-borrowed/gocode
|                > disposa.blue/cmd/margo_pkg
|                > disposa.blue/cmd/margo
|                > go install disposa.blue/cmd/margo: open gosublime.margo_r16.07.09-1_go?.exe: The filename, directory name, or volume label syntax is incorrect.
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3126
| sublime.channel: stable
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r16.07.09-1_go?.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C:\Go\
|          GOPATH: /Users/<username>/code/go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\WINDOWS\\system32\\cmd.exe', '/C', '${CMD}']

How can I fix it ? Thanks

**Comment by msyarif04** [comment]
when i open the Sublime Text console and run 

from gosubl import sh; sh.go_cmd(['version']).run()

Result(out='', cmd_lst=['C:\\Go\\bin\\go.exe', 'version'], err='go: GOPATH entry is relative; must be absolute path: "/Users/<username>/code/go".\nRun \'go help gopath\' for usage.\n', ok=True, exc=None)

**Comment by plmnko** [comment]
If you defined GOROOT and GOPATH in the user setting of GoSublime, then try remove it. 
Check this: https://github.com/DisposaBoy/GoSublime/issues/668

I got the same error as yours when GoSublime auto upgraded, and this solution worked for me.

**Comment by cers000** [comment]
把之前安装的Golang环境全部删除重新安装最新的1.8版本的Golang，就可以正常编译了

**Comment by msyarif04** [comment]
@plmnko thank you for your suggession. Its work for me
@cers000 thank you, when i upgrade to new version, its no problem with the package
