### ISSUE TITLE
I don`t want format my code when I save

### ISSUE THREAD

**Issue by Neveryu** [DisposaBoy/GoSublime#764]
I don`t want format my code when I save.
could you tell me how to setting it that do not format my code when I save file 
Thank you

**Comment by dionb** [comment]
In you user settings add "fmt_enabled": false
If you don't know where to find the user settings use Ctrl+Shift+P then enter "GoSublime: User Settings"

**Comment by Neveryu** [comment]
@dionb Thank you.
you are better man.
