### ISSUE TITLE
Autocomplete window not opening on dot

### ISSUE THREAD

**Issue by AndreasBackx** [DisposaBoy/GoSublime#765]
I've been facing the same issue as #175, but none of my packages seem to be the cause. I disabled all of my packages except for GoSublime and still doesn't open an autocomplete window when typing the dot `.`. It does open with the hotkey `ctrl+space`. `"auto_complete"` in the ST3 settings is also set to `true`. What could be the cause here?

**Comment by stefan-o** [comment]
I'm experiencing the same issue, would be keen to hear if there is another configuration parameter for this.

**Comment by ivanmrchk** [comment]
+1

**Comment by DisposaBoy** [comment]
GoSublime doesn't trigger the autocomplete. If <kbd>ctrl+space</kbd> works and none of your other plugins are overriding `auto_complete_triggers`, it's probably a Sublime Text issue.
