### ISSUE TITLE
Got a MarGo Build Failed when installing

### ISSUE THREAD

**Issue by marksou** [DisposaBoy/GoSublime#769]
I just installed GoSublime and got a MarGo Build Failed error. I'm running Sublime 3 Build 3126
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/Cellar/go/1.4.2/libexec/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r17.03.05-1_go1.4.2.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > failed MSpanList_Insert 0x753930 0x4123129353f 0x0
|                > fatal error: MSpanList_Insert
|                > 
|                > runtime stack:
|                > runtime.MSpanList_Insert(0x6a3730, 0x753930)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:692 +0x8f
|                > runtime.MHeap_Free(0x6a36c0, 0x753930, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:500 +0x5b
|                > runtime.MCentral_FreeSpan(0x6ad058, 0x753930, 0x2, 0xc2080d2000, 0xc2080d3000, 0x93a00, 0x64)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:181 +0x1bb
|                > runtime.MSpan_Sweep(0x753930, 0x1300000000, 0xc200000001)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.c:1099 +0x477
|                > 
|                > goroutine 3 [running]:
|                > runtime.switchtoM()
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:198 fp=0xc20801dfa8 sp=0xc20801dfa0
|                > runtime.gosweepone(0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.c:1168 +0x1e fp=0xc20801dfc0 sp=0xc20801dfa8
|                > runtime.bgsweep()
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.go:85 +0x36 fp=0xc20801dfe0 sp=0xc20801dfc0
|                > runtime.goexit()
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
|                > created by gc
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.c:1386
|                > 
|                > goroutine 1 [syscall]:
|                > syscall.Syscall(0x3, 0x3, 0xc2080c8000, 0x1000, 0x36, 0x7a508, 0xc208102500)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:20 +0x5
|                > syscall.read(0x3, 0xc2080c8000, 0x1000, 0x1000, 0x35, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:970 +0x6e
|                > syscall.Read(0x3, 0xc2080c8000, 0x1000, 0x1000, 0x7a57b, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_unix.go:136 +0x58
|                > os.(*File).read(0xc20802e018, 0xc2080c8000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:191 +0x86
|                > os.(*File).Read(0xc20802e018, 0xc2080c8000, 0x1000, 0x1000, 0x58, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x91
|                > bufio.(*Reader).fill(0xc208060120)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
|                > bufio.(*Reader).ReadByte(0xc208060120, 0x4375e0, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:196 +0x86
|                > go/build.(*importReader).readByte(0xc208100c80, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/read.go:41 +0x36
|                > go/build.(*importReader).peekByte(0xc208100c80, 0x42f801, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/read.go:74 +0xaa
|                > go/build.(*importReader).readKeyword(0xc208100c80, 0x47db90, 0x7)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/read.go:122 +0x2d
|                > go/build.readImports(0x760838, 0xc20802e018, 0xc20802e000, 0x0, 0x0, 0x0, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/read.go:207 +0xe7
|                > go/build.(*Context).matchFile(0x693820, 0xc2080b9c20, 0x2e, 0xc2080f43ef, 0x6, 0x101, 0xc2080b81e0, 0x0, 0x0, 0x0, ...)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/build.go:958 +0x5be
|                > go/build.(*Context).Import(0x693820, 0x47f3f0, 0x7, 0xc2080b92f0, 0x2d, 0x4, 0xc2080018c0, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/build.go:624 +0x1d10
|                > main.loadImport(0x47f3f0, 0x7, 0xc2080b92f0, 0x2d, 0xc20801efe0, 0x0, 0x0, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:267 +0x4d9
|                > main.(*Package).load(0xc208075800, 0xc20801efe0, 0xc2080a2c00, 0x0, 0x0, 0x4)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:584 +0x3d88
|                > main.loadImport(0xc2080bc709, 0x6, 0xc2080e4bd0, 0x2c, 0xc20801efe0, 0xc2080aea50, 0x2, 0x2, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:275 +0x635
|                > main.(*Package).load(0xc208074c00, 0xc20801efe0, 0xc2080a2900, 0x0, 0x0, 0x4)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:584 +0x3d88
|                > main.loadImport(0xc2080bd677, 0x5, 0xc2080b9a40, 0x2c, 0xc20801efe0, 0xc2080af360, 0x2, 0x2, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:275 +0x635
|                > main.(*Package).load(0xc208074400, 0xc20801efe0, 0xc2080a2600, 0x0, 0x0, 0x4)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:584 +0x3d88
|                > main.loadImport(0xc2080bc6f1, 0x5, 0xc208070af0, 0x6f, 0xc20801efe0, 0xc2080ae4b0, 0x2, 0x2, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:275 +0x635
|                > main.(*Package).load(0xc208075400, 0xc20801efe0, 0xc2080a2300, 0x0, 0x0, 0x4)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:584 +0x3d88
|                > main.loadImport(0xc20801f261, 0x1a, 0xc2080704d0, 0x6b, 0xc20801efe0, 0xc2080b8b70, 0x1, 0x1, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:275 +0x635
|                > main.(*Package).load(0xc208075000, 0xc20801efe0, 0xc2080a2000, 0x0, 0x0, 0x4)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:584 +0x3d88
|                > main.loadImport(0x7fff5fbffa6d, 0x16, 0xc20800a080, 0x70, 0xc20801efe0, 0x0, 0x0, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:275 +0x635
|                > main.loadPackage(0x7fff5fbffa6d, 0x16, 0xc20801efe0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:867 +0xf7c
|                > main.packagesAndErrors(0xc2080bcfa0, 0x1, 0x1, 0x0, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:906 +0x366
|                > main.packagesForBuild(0xc20800a070, 0x1, 0x1, 0x0, 0x0, 0x0)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:919 +0x74
|                > main.runBuild(0x68e900, 0xc20800a070, 0x1, 0x1)
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/build.go:266 +0x78
|                > main.main()
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/main.go:163 +0x608
|                > 
|                > goroutine 5 [syscall]:
|                > os/signal.loop()
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
|                > created by os/signal.init·1
|                > 	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3126
| sublime.channel: stable
|       about.ann: a17.03.05-1
|   about.version: r17.03.05-1
|         version: r17.03.05-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r17.03.05-1_go1.4.2.exe (missing)
|          go.exe: /usr/local/Cellar/go/1.4.2/libexec/bin/go (ok)
|      go.version: go1.4.2
|          GOROOT: /usr/local/Cellar/go/1.4.2/libexec
|          GOPATH: ~/go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/zsh
|       shell.cmd: ['/bin/zsh', '-l', '-c', '${CMD}']

**Comment by Juev** [comment]
#778

**Comment by marksou** [comment]
Fixed
