### ISSUE TITLE
Goimports doesn't work in GoSublime anymore.

### ISSUE THREAD

**Issue by taggedboy** [DisposaBoy/GoSublime#773]
I whenever installed Sublime Text on a new computer I followed [this tutorial](https://michaelwhatcott.com/gosublime-goimports/) and Goimports worked automatically in GoSublime. But the last time I installed it, it's not working anymore.

**Comment by nasitra** [comment]
If you use on Windows, there is something wrong with goimports.

Fix <code>%GOPATH%/src/golang.org/x/tools/imports/fix.go</code>

```diff
--- a/fix.go
+++ b/fix.go
@@ -254,10 +254,12 @@ func fixImports(fset *token.FileSet, f *ast.File, filename string) (added []stri
        results := make(chan result)
        for pkgName, symbols := range refs {
                go func(pkgName string, symbols map[string]bool) {
-                       sibling := packageInfo.Imports[pkgName]
-                       if sibling.Path != "" {
-                               results <- result{ipath: sibling.Path, name: sibling.Alias}
-                               return
+                       if packageInfo != nil {
+                               sibling := packageInfo.Imports[pkgName]
+                               if sibling.Path != "" {
+                                       results <- result{ipath: sibling.Path, name: sibling.Alias}
+                                       return
+                               }
                        }
                        ipath, rename, err := findImport(pkgName, symbols, filename)
                        r := result{ipath: ipath, err: err}
```

Then reinstall goimports

```
go install golang.org/x/tools/cmd/goimports
```

**Comment by taggedboy** [comment]
Thank You @nasitra! It worked for me.
Did you push this change to the GoSublime?

**Comment by nasitra** [comment]
The change merged into 'golang/tools', not GoSublime.

https://github.com/golang/tools/commit/6e57528ade4c045edb91dac8af1c4a3ab30fa738

Now, we don't need to change the code locally.
You can get the latest goimports program and update it.

<pre>
go get -u golang.org/x/tools/cmd/goimports
</pre>
