### ISSUE TITLE
MarGo build failed

### ISSUE THREAD

**Issue by lamg** [DisposaBoy/GoSublime#778]
With the following output:
> cmd: `['~/golang/bin/go', 'build', '-tags', 'gosublime', '-v', '-o', 'gosublime.margo_r17.08.23-1_devel+0b6fbaae6e.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > runtime/internal/sys
|                > runtime/internal/atomic
|                > runtime
|                > errors
|                > internal/cpu
|                > internal/race
|                > sync/atomic
|                > unicode
|                > unicode/utf8
|                > math
|                > sync
|                > encoding
|                > unicode/utf16
|                > internal/nettrace
|                > math/bits
|                > io
|                > syscall
|                > internal/singleflight
|                > container/list
|                > bytes
|                > strings
|                > bufio
|                > path
|                > hash
|                > hash/crc32
|                > crypto/subtle
|                > crypto/internal/cipherhw
|                > crypto/cipher
|                > strconv
|                > math/rand
|                > time
|                > internal/syscall/unix
|                > crypto/hmac
|                > vendor/golang_org/x/crypto/poly1305
|                > vendor/golang_org/x/crypto/curve25519
|                > vendor/golang_org/x/text/transform
|                > reflect
|                > encoding/base64
|                > crypto/aes
|                > crypto
|                > internal/poll
|                > crypto/sha512
|                > crypto/md5
|                > crypto/rc4
|                > crypto/sha1
|                > os
|                > crypto/sha256
|                > html
|                > text/tabwriter
|                > runtime/trace
|                > fmt
|                > sort
|                > encoding/binary
|                > path/filepath
|                > regexp/syntax
|                > crypto/des
|                > encoding/pem
|                > io/ioutil
|                > go/token
|                > net/url
|                > text/template/parse
|                > go/scanner
|                > regexp
|                > log
|                > go/ast
|                > encoding/json
|                > text/template
|                > flag
|                > context
|                > go/parser
|                > net
|                > compress/flate
|                > math/big
|                > go/doc
|                > compress/gzip
|                > encoding/hex
|                > vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
|                > vendor/golang_org/x/crypto/chacha20poly1305
|                > go/build
|                > vendor/golang_org/x/net/http2/hpack
|                > vendor/golang_org/x/text/unicode/bidi
|                > disposa.blue/margo
|                > crypto/rand
|                > disposa.blue/margo/meth/importpaths
|                > crypto/elliptic
|                > encoding/asn1
|                > crypto/rsa
|                > crypto/dsa
|                > vendor/golang_org/x/text/secure/bidirule
|                > vendor/golang_org/x/text/unicode/norm
|                > vendor/golang_org/x/net/proxy
|                > mime
|                > crypto/ecdsa
|                > crypto/x509/pkix
|                > mime/quotedprintable
|                > crypto/x509
|                > net/textproto
|                > net/http/internal
|                > html/template
|                > mime/multipart
|                > vendor/golang_org/x/net/idna
|                > runtime/pprof
|                > crypto/tls
|                > encoding/gob
|                > vendor/golang_org/x/net/lex/httplex
|                > os/exec
|                > text/scanner
|                > disposa.blue/something-borrowed/types
|                > go/printer
|                > net/http/httptrace
|                > net/http
|                > gosublime
|                > net/http/pprof
|                > net/rpc
|                > disposa.blue/something-borrowed/gocode
|                > disposa.blue/cmd/margo_pkg
|                > disposa.blue/cmd/margo
|                > # disposa.blue/cmd/margo
|                > runtime.getclosureptr: call to external function
|                > runtime.memhash_varlen: relocation target runtime.getclosureptr not defined
|                > runtime.strequal: relocation target runtime.eqstring not defined
|                > runtime.gogetenv: relocation target runtime.eqstring not defined
|                > runtime.(*itab).init: relocation target runtime.eqstring not defined
|                > runtime.(*itab).init: relocation target runtime.eqstring not defined
|                > runtime.parsedebugvars: relocation target runtime.eqstring not defined
|                > runtime.index: relocation target runtime.eqstring not defined
|                > runtime.moduledataverify1: relocation target runtime.eqstring not defined
|                > runtime.getArgInfo: relocation target runtime.eqstring not defined
|                > runtime.getArgInfo: relocation target runtime.eqstring not defined
|                > runtime.showframe: relocation target runtime.eqstring not defined
|                > runtime.typesEqual: relocation target runtime.eqstring not defined
|                > runtime.typesEqual: relocation target runtime.eqstring not defined
|                > runtime.typesEqual: relocation target runtime.eqstring not defined
|                > runtime.typesEqual: relocation target runtime.eqstring not defined
|                > runtime.typesEqual: relocation target runtime.eqstring not defined
|                > runtime.typesEqual: relocation target runtime.eqstring not defined
|                > runtime.typesEqual: relocation target runtime.eqstring not defined
|                > runtime.typesEqual: relocation target runtime.eqstring not defined
|                > runtime.vdso_find_version: relocation target runtime.eqstring not defined
|                > ~/golang/pkg/tool/linux_amd64/link: too many errors
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3126
| sublime.channel: stable
|       about.ann: a17.08.23-1
|   about.version: r17.08.23-1
|         version: r17.08.23-1
|        platform: linux-x64
|            ~bin: ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/bin
|       margo.exe: ~bin/gosublime.margo_r17.08.23-1_devel+0b6fbaae6e.exe (missing)
|          go.exe: ~/golang/bin/go (ok)
|      go.version: devel+0b6fbaae6e
|          GOROOT: ~/golang
|          GOPATH: ~/go
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']

**Comment by Juev** [comment]
I think, problem is:
`| GOBIN: (not set) (should usually be (not set))`
By default this variable is not used. But MarGo not used default `$GOPATH/bin`, I dont know, why.
But if you will set this variable:
`export GOBIN=$GOPATH\bin`
This issue should be resolved. At least it helped me.

**Comment by lamg** [comment]
It worked for me too. Thanks!

**Comment by DisposaBoy** [comment]
I don't understand how setting `GOBIN` can fix the issue, unless maybe `GOROOT` or `GOPATH` is incorrect.

**Comment by lamg** [comment]
You're right. I haven't set GOROOT, since having the installation at $HOME/golang is enough. I tried setting GOROOT=$HOME/golang and it worked too.

**Comment by Juev** [comment]
@DisposaBoy As we can see on https://golang.org/doc/install by default we don't set GOROOT variable. But if we use a custom location for installation, we should set this variable. 
Then we should set variable GOPATH, and this variable will indicate our workspace. For Golang this actions is enough. But for MarGo we should additionally setting GOBIN variable.
