### ISSUE TITLE
"Jump back" not working with "Goto Definition"

### ISSUE THREAD

**Issue by ApsOps** [DisposaBoy/GoSublime#784]
Version: **Current master HEAD - [40439d](https://github.com/DisposaBoy/GoSublime/tree/40439d234ceee70a6203dc2241b86099f99ddb31)**
Platform: **MacOS**
SublimeText version: **Sublime Text 3.0 build 3143**

When I go to a definition (using `cmd+.`, `cmd+g` or `cmd+shift+left click`) in the same or different file, I'm unable to jump back to original position (using `cmd+.`, `cmd+[`).

For "goto definition", I see logs like these:
```
** 2017-10-17 17:08:08.223231 **:
opening /Users/aps/workspace/golang/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_kinesis_firehose_delivery_stream_test.go:357:5
--------------------------------
```
But no logs when I try to jump back.

Is this a bug, or am I doing something wrong here? Thanks!

**Comment by DisposaBoy** [comment]
Use the native Sublime Text feature <kbd>alt+-</kbd> or <kbd>shift+alt+-</kbd>.
