### ISSUE TITLE
~bin\gosublime.margo_r17.11.14-1_go?.exe (missing)

### ISSUE THREAD

**Issue by bestplay** [DisposaBoy/GoSublime#788]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['D:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r17.11.14-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > disposa.blue/margo
|                > net
|                > disposa.blue/something-borrowed/types
|                > disposa.blue/margo/meth/importpaths
|                > crypto/x509
|                > vendor/golang_org/x/net/lex/httplex
|                > vendor/golang_org/x/net/proxy
|                > net/textproto
|                > mime/multipart
|                > crypto/tls
|                > net/http/httptrace
|                > net/http
|                > net/http/pprof
|                > net/rpc
|                > disposa.blue/something-borrowed/gocode
|                > disposa.blue/cmd/margo_pkg
|                > disposa.blue/cmd/margo
|                > go install disposa.blue/cmd/margo: open gosublime.margo_r17.11.14-1_go?.exe: The filename, directory name, or volume label syntax is incorrect.
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3143
| sublime.channel: stable
|       about.ann: a17.11.14-1
|   about.version: r17.11.14-1
|         version: r17.11.14-1
|        platform: windows-x64
|            ~bin: D:\Sublime Text Build 3143 x64\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r17.11.14-1_go?.exe (missing)
|          go.exe: D:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: D:\Go
|          GOPATH: D:\backup\prj\work\job;D:\backup\prj\work\job\src;
|           GOBIN: D:\Go\bin
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\WINDOWS\\system32\\cmd.exe', '/C', '${CMD}']

**Comment by DisposaBoy** [comment]
there might be more useful info the sublime console. looks for lines that start with `GoSublime ` e.g. `GoSublime r17.11.13-1 sh: go version:`

**Comment by bestplay** [comment]
It is golang's issue in Window 10.

When using multiple GOPATH with semicolon.

[https://github.com/golang/go/issues/21928](https://github.com/golang/go/issues/21928)

I will close this issue. Thanks @DisposaBoy
