### ISSUE TITLE
Syntax highlighting fails on malformed template string 

### ISSUE THREAD

**Issue by josharian** [DisposaBoy/GoSublime#789]
For this line:

https://github.com/golang/go/blob/4a41da5bac1da4a71b237581ab30dd7a84c5bc55/src/text/template/multi_test.go#L43

the built-in ST3 syntax highlighter does the right thing, but the GoSublime-Go highlighter interprets the lone double quote in the backticks in the final test to be the beginning of an unclosed string literal, mostly destroying syntax highlighting for the rest of the file.

**Comment by DisposaBoy** [comment]
I switched back to a copy of the syntax that's shipped with Sublime Text. Everything's working AFAICS.
