### ISSUE TITLE
17.11.25-1 update ruins syntax highlight

### ISSUE THREAD

**Issue by xlab** [DisposaBoy/GoSublime#790]
Hi, I'd like to submit a complaint about the latest update that just rolled out.

```
## 17.11.25-1
	* use the latest Sublime Text Go syntax
    * convert all our existing syntax definitions to .sublime-synta
```

The problem is, that syntax highlight is now working odd on my usual setup. See two screenshots attached, the first one is `17.11.14-1` and the second one is `17.11.25-1`. I tried to switch different languages for these files, but seems that the issue is permanent. GoSublime now fallbacks to some other scheme, clearly.

<img width="1000" alt="screen shot 2017-11-26 at 22 33 43" src="https://user-images.githubusercontent.com/477998/33243574-f9208064-d2f9-11e7-95e6-897dc349c432.png">

<img width="960" alt="screen shot 2017-11-26 at 22 23 08" src="https://user-images.githubusercontent.com/477998/33243573-f9049c3c-d2f9-11e7-8d9a-8182cae9546e.png">

It may be unclear on the screenshots, but the issue is that syntax highlight works differently, in my case it paints almost all code red now. But I've been a couple of years on GoSublime scheme and previously it's been OK!

**Comment by DisposaBoy** [comment]
If the only problem is the color change then my advice is to either report it to SublimeHQ and see if they're willing to improve it or downgrade and I will add a copy of the old syntax in the next update.

**Comment by andyone** [comment]
Looks like golang syntax highlighting broken [a long time ago](https://forum.sublimetext.com/t/incorrect-go-syntax-highlighting-in-func-arguments/10975/2) and Sublime authors don't want to fix it.

**Comment by xlab** [comment]
Agreed with @andyone, 
btw syntax highlight is roughly 50% of features I use in GoSublime, the other 50% is autocomplete :)

> If the only problem is the color change

It looks like old GoSublime highlighting has more info about the code. Currently it has the same color for everything.

**Comment by DisposaBoy** [comment]
I pushed a new release that should fix this.

**Comment by andyone** [comment]
Thank you very much!

**Comment by vjeantet** [comment]
it works on my side with last release.
