### ISSUE TITLE
r17.11.25-1 does not take snippets into account

### ISSUE THREAD

**Issue by vjeantet** [DisposaBoy/GoSublime#791]
Hello,

   since last update snippets does not work anymore.
   I tried to replace my snippets with the default one.... same behavior... no more snippets.

Thanks for your help, and for this wonderfull project !

**Comment by DisposaBoy** [comment]
I pushed a new release that should fix this... But looking at the syntax definition, it looks like the definitions that make `local` snippets went missing about 4 years ago.

**Comment by vjeantet** [comment]
Hello, thanks for the fix, it's OK with last release.

for information, here are the 2 snippets i use a LOT.

```
    "snippets": [
        {
            "match": {"global": true}, // these snippets will only be presented in the global scope
            "snippets": [
                {"text": "pp", "title": "PrettyPrint", "value": "pp.Println(\"$1-->\", $1)"},
                {"text": "err", "title": "err clause", "value": "if err != nil {\n\treturn err$2\n}\n$3"}
            ]
        }
    ]
```
