### ISSUE TITLE
code format on save moves cursor

### ISSUE THREAD

**Issue by Leryan** [DisposaBoy/GoSublime#795]
Hi,

SublimeText 3 build 3156 with the latest available stable version of GoSublime installed, Go 1.9.2.

When i do save a Go file (`ctrl+s`), even without modifications, the cursors jumps elsewhere and so does the "file buffer", not sure how to designate that.

**Comment by DisposaBoy** [comment]
I can't reproduce this.
Does it still happen if you switch back to an older version of Sublime Text?
Is it happening with all files?

**Comment by Leryan** [comment]
It doesn't happen with other files.

I'll check with a stable version of ST3 as soon as possible.

**Comment by DisposaBoy** [comment]
Is it a file that you can share? I went so far as to patch the view instead of just replacing it in order to avoid this issue. I can't think of why it would happen even if the whole file was replaced.

**Comment by Leryan** [comment]
Hum, properly closing every window of ST3 and reopening the .go file made it fix the problem because it switched from space indentation to tab mode.

I had a setting that make ST alway use spaces instead of tabs. Changed to `"detect_indentation": true` and now it's ok…

Sorry for the noise.
