### ISSUE TITLE
toggle_comment shortcut not working anymore

### ISSUE THREAD

**Issue by Kerhael** [DisposaBoy/GoSublime#797]
Hi,

First, thanks a lot for this amazing package, I use it everyday at work.

I am currently using GoSublime on **Sublime Text 3.0**.
Since the latest GoSublime update (**17.11.27-1**), following shortcuts are not working anymore:
```
{ "keys": ["ctrl+/"], "command": "toggle_comment", "args": { "block": false } },
{ "keys": ["ctrl+shift+/"], "command": "toggle_comment", "args": { "block": true } },
```

No error is displayed in the console, and `sublime.log_commands(True)` shows the correct commands are called.
However, my code is not commented.
This happens only with `.go` files.

Thanks in advance for any help you can provide;

Kind regards

**Comment by DisposaBoy** [comment]
It should be fixed in the latest release

**Comment by Kerhael** [comment]
Thanks a lot!

**Comment by Kerhael** [comment]
Tested now after update and it is fixed :)
