### ISSUE TITLE
 GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by hu18359780442** [DisposaBoy/GoSublime#798]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['D:/Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r17.12.08-1_go?.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > can't load package: package disposa.blue/cmd/margo: cannot find package "disposa.blue/cmd/margo" in any of:
|                > 	D:\Go\src\disposa.blue\cmd\margo (from $GOROOT)
|                > 	D:\SOFT\SublimeText3_ha\Sublime Text 3.3126x64\Data\Packages\User\GoSublime\src\disposa.blue\cmd\margo (from $GOPATH)
|                > 	D:\SOFT\SublimeText3_ha\Sublime Text 3.3126x64\Data\Packages\GoSublime\src\disposa.blue\cmd\margo
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3126
| sublime.channel: stable
|       about.ann: a17.12.08-1
|   about.version: r17.12.08-1
|         version: r17.12.08-1
|        platform: windows-x64
|            ~bin: D:\SOFT\SublimeText3_ha\Sublime Text 3.3126x64\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r17.12.08-1_go?.exe (missing)
|          go.exe: D:/Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: D:/Go
|          GOPATH: D:/Go/go_pro
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\Windows\\system32\\cmd.exe', '/C', '${CMD}']
|    sh.bootstrap: 
|                > 	error running sh-bootstrap.go: CreateFile sh-bootstrap.go: The system cannot find the file specified.
|                > 
|                > 	go version: `` (raw version string ``)
|                > 	shell bootstrap took 1.478s
|                > 

This file gosublime.margo_r17.12.08-1_go.exe will be deleted in Sublime Text 3.3126x64\Data\Packages\User\GoSublime\windows-x64\bin and warn me again when I reopen sublime3

**Comment by DisposaBoy** [comment]
I don't know how to reproduce that. Does the file `D:\SOFT\SublimeText3_ha\Sublime Text 3.3126x64\Data\Packages\GoSublime\gosubl\sh-bootstrap.go` exist and is readable?
