### ISSUE TITLE
Per-project Settings & Project-based GOPATH don`t work for Gdef

### ISSUE THREAD

**Issue by javasgl** [DisposaBoy/GoSublime#801]
here is the issue: https://github.com/buaazp/Godef/issues/17

per-project GOPATH config don`t work.
my project settings like this:
```
{
	"settings": {
		"GoSublime": {
			"env": {
				"GOPATH": "/Users/songgl/codes/studygolang",
				"GOROOT": "/usr/local/go"
			}
		}
	}
}
```
but , Gdef load failed because of no GOPATH defined
```
===============[Godef]Load Begin==============
[Godef]ERROR: no GOPATH defined
===============[Godef] Load End===============
```

**Comment by DisposaBoy** [comment]
GoSublime doesn't modify the Sublime Text enviornment variables (to avoid breaking other plugins).
I'd be willing to add some support for doing that, but I can't guarantee it will continue working forever.

**Comment by javasgl** [comment]
That wolud be wonderfu

**Comment by arsham** [comment]
The issue you are describing is not GoSublime's issue. However I've made a fix for that in [this](https://github.com/buaazp/Godef/pull/24) pull request.

**Comment by DisposaBoy** [comment]
I thought I already reponded to this (or maybe it was another issue), but support for this was added a while ago via the [export_env_vars](https://github.com/DisposaBoy/GoSublime/blob/master/GoSublime.sublime-settings#L333).
