### ISSUE TITLE
GoSublime error: MarGo build failed

### ISSUE THREAD

**Issue by notnot** [DisposaBoy/GoSublime#802]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/go/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r17.12.17-1_go1.9.2.exe', 'disposa.blue/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > net
|                > os/user
|                > disposa.blue/margo
|                > disposa.blue/something-borrowed/types
|                > disposa.blue/margo/meth/importpaths
|                > crypto/x509
|                > vendor/golang_org/x/net/proxy
|                > net/textproto
|                > vendor/golang_org/x/net/lex/httplex
|                > mime/multipart
|                > crypto/tls
|                > net/http/httptrace
|                > net/http
|                > net/http/pprof
|                > net/rpc
|                > disposa.blue/something-borrowed/gocode
|                > go build disposa.blue/something-borrowed/gocode: /usr/local/go/pkg/tool/darwin_amd64/compile: chdir ~/Library/Application Support/Sublime Text 3/Packages/GoSublime/src/disposa.blue/something-borrowed/gocode: no such file or directory
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3143
| sublime.channel: stable
|       about.ann: a17.12.17-1
|   about.version: r17.12.17-1
|         version: r17.12.17-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r17.12.17-1_go1.9.2.exe (missing)
|          go.exe: /usr/local/go/bin/go (ok)
|      go.version: go1.9.2
|          GOROOT: /usr/local/go
|          GOPATH: ~/prog/go/extern:~/prog/go/jpad
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']
|    sh.bootstrap: 
|                > 	using shell env GOPATH=~/prog/go/extern:~/prog/go/jpad
|                > 	using shell env GOROOT=/usr/local/go
|                > 	using shell env PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:~/prog/go/extern/bin:~/prog/go/jpad/bin:/opt/pkgconfig/bin:~/bin:~/go/bin:/usr/local/opt/go/bin:/opt/pkgconfig/bin
|                > 	go version: `go1.9.2` (raw version string `go1.9.2`)
|                > 	shell bootstrap took 99.735s
|                >

**Comment by notnot** [comment]
After i quit Sublime Text and opened it again, Margo was built successfully.

**Comment by donkeysharp** [comment]
Having the same issue:
SublimeText 3 Build: 3126
Operating System: GNU/Linux Debian 8

Even if I quit getting the same error

**Comment by donkeysharp** [comment]
after investigating a bit more I was able to solve by removing the package using Package Manager and installing it manually using git clone

**Comment by kunalpowar** [comment]
Had the same issue. I **solved** it with these steps.

- Remove GoSublime Package (either from package manager or manual)
- Find out where `gosublime/gosublime.go:4:2` exists. For me this was in `$HOME/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/src/gosublime .go`
- Remove all GoSublime related things in ``$HOME/Library/Application Support/Sublime Text 3/Packages/User/`
- Re-install GoSublime Package

**Comment by bmunoz89** [comment]
I have the same problem, but with the solution of @kunalpowar its works again! 👏

**Comment by yeqown** [comment]
the solution solves my problem @kunalpowar

**Comment by hiyanxu** [comment]
just Reinstall GoSublime,it works!

**Comment by cskonopka** [comment]
Worked for me. Thanks @kunalpowar !
