### ISSUE TITLE
gslint not working

### ISSUE THREAD

**Issue by geekofalltrades** [DisposaBoy/GoSublime#805]
gslint seems to have completely stopped working. I'm working with a go file that has missing imports, and so should obviously be triggering linter errors, but none are coming up. `Ctrl + .`, `Ctrl + e` also turns up no errors. Linting was working before; I'm unsure what triggered this.

gslint is enabled in my settings (I'm using the default settings).

No logs about the lack of linting are showing up in the ST3 console. Here's the startup log for GoSublime:

```
GoSublime init r18.01.17-1 (0.000s)
|   install margo: no
|   install state: done
| sublime.version: 3143
| sublime.channel: stable
|       about.ann: a18.01.17-1
|   about.version: r18.01.17-1
|         version: r18.01.17-1
|        platform: linux-x64
|            ~bin: ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/bin
|       margo.exe: ~bin/gosublime.margo_r18.01.17-1_go1.9.2.exe (ok)
|          go.exe: /usr/lib/go-1.9/bin/go (ok)
|      go.version: go1.9.2
|          GOROOT: /usr/lib/go-1.9
|          GOPATH: ~/git/hopcloud
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']
|    sh.bootstrap: 
|                > 	using shell env GOPATH=~/git/hopcloud
|                > 	using shell env GOROOT=/usr/lib/go-1.9
|                > 	using shell env PATH=/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin::/usr/lib/go-1.9/bin:~/git/hopcloud/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:~/git/ehit/bin:~/.local/bin:~/bin:~/go/bin:/usr/local/go/bin:/usr/local/opt/go/bin
|                > 	go version: `go1.9.2` (raw version string `go1.9.2`)
|                > 	shell bootstrap took 0.166s
|                >
--------------------------------
```

I'm running Ubuntu 16.04. I had previously installed GoSublime with Package Control, but I uninstalled it in the course of troubleshooting and installed with the recommended method, and the problem still persists. I tried rolling back to r17.12.08-1, and the problem still persists.

**Comment by DisposaBoy** [comment]
I just tried and it seems to work for me using the example config from [articles/golint.md](https://github.com/DisposaBoy/GoSublime/blob/master/articles/golint.md).

Maybe check the console for errors.
