### ISSUE TITLE
{• <current_time> •}

### ISSUE THREAD

**Issue by li-ang** [DisposaBoy/GoSublime#812]
Current time is displayed on the status bar after updating GoSublime

![image](https://user-images.githubusercontent.com/13193708/36355524-9204d5b6-151f-11e8-9513-3b5b5783e339.png)

Does GoSublime cause it?

**Comment by li-ang** [comment]
@DisposaBoy

**Comment by DisposaBoy** [comment]
Yes, but only if you enabled the margo extension. Press <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd> to edit the file. The comments should explain what the file does (hopefully)

**Comment by li-ang** [comment]
Lovely !
