### ISSUE TITLE
Recent changes to GoSublime/Margo use CPU heavily

### ISSUE THREAD

**Issue by xlab** [DisposaBoy/GoSublime#813]
The problem which doesn't exist previously is that when I'm working with projects using GoSublime, it start to use CPU heavily, 400% on all cores. Investigated htop and it seems that it runs background compile jobs, a thing I never seen before.

<img width="1145" alt="screen shot 2018-02-27 at 14 24 11" src="https://user-images.githubusercontent.com/477998/36715822-6efde5d8-1bca-11e8-8a10-0035577603f8.png">

This drains battery quickly and makes my notebook noisy all the time, is there any possibility to opt out from this feature?

```
Go 1.10
MacBook Pro (Retina, 13-inch, Mid 2014)
2.8 GHz Intel Core i5
8 GB 1600 MHz DDR3
```

**Comment by DisposaBoy** [comment]
The screenshot is missing the important part that says what it's compiling. The output in the Sublime Text console should also be helpful.

The only (new) things that should be compiled automatically by default are the two new binaries `margo` followed by `margo.sublime` and these should be cached.

My only other guess is that you enabled the new binaries (probably by pressing <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd>) and have gocode's `Autobuild` set to `true` (the default). If that's the case, just remove that line.

**Comment by xlab** [comment]
Okay, new binaries autoenabled themselves (I got the face in the bottomline). And after pressing `Cmd+. Cmd+x` I got into `margo.go` where replaced `Autobuild: true,` with `false`. Let's see if it helps.

> The screenshot is missing the important part that says what it's compiling.

Some random packages from my project, not margo (I know it previously compiled margo somtimes, it was ok).

**Comment by DisposaBoy** [comment]
`Enabled` is a bit confusing here (my fault). By default, the binaries are installed and started, but they do nothing unless you create/edit the margo extension (`margo.go`).

There is a setting `autoinst` that's enabled by default that could cause this, but that's been there for years.

Also, please note that you will need to restart Sublime Text after *the first time* you edit the `margo.go` file. If you kept the `DayTimeStatus` line, the face should be replaced with the current time in the status bar. Since battery life is a concern, you might want to remove it (the `DayTimeStatus,` line) because it re-renders the time every second.

**Comment by xlab** [comment]
@DisposaBoy okay, i played a little with all these flags, it seems that build process triggers on a single project. I'm too lazy to debug and see the root cause..

Also, `goimports` upon save stopped working and putting all flags referenced above doesn't help. See my config below. I just made a rollback to `r17.13.08-1` and continue to live happily.


```
{
  "fmt_cmd": ["goimports"],
  "ipc_timeout": 5,
  "autocomplete_builtins": true,
  "autocomplete_closures": true,
  "autocomplete_suggest_imports": true,
}
```

**Comment by DisposaBoy** [comment]
@xlab 

> Also, goimports upon save stopped working and setting all flags referenced above to true doesn't help

Just change your `margo.go` file to use `GoImports` instead. By default it uses `GoFmt` and the GoSublime `fmt` feature is disabled. Your `margo.go` file will likely be different, but it should contain a section similar to this [margo.go](https://github.com/DisposaBoy/GoSublime/blob/master/src/disposa.blue/margo/extension-example/extension-example.go#L18)

**Comment by xlab** [comment]
@DisposaBoy that was a rough migration! Thanks, the solution works, I can also disable autoinst for sure. I will close this issue.

**Comment by xlab** [comment]
@DisposaBoy oh, your  `golang.GoImports` works slightly different from `goimports`.

Example:

```go
package main

import (
"github.com/jawher/mow.cli"
)

var app = cli.App("foo", "bar")
```

Here it will remove the import of `"github.com/jawher/mow.cli"` and `goimports` would add it as 
`cli "github.com/jawher/mow.cli"`

**Comment by DisposaBoy** [comment]
Which version of `goimports` or which flags produce `cli "github.com/jawher/mow.cli"`? or is that a typo?

Using what I assume is the latest version (`go get -u golang.org/x/tools/cmd/goimports`) and the command `goimports -srcdir $file_name`, it outputs:

```
package main

import (
	"github.com/jawher/mow.cli"
)

var app = cli.App("foo", "bar")
```

**Comment by xlab** [comment]
@DisposaBoy if the line exists, it leaves it AS-IS. If not exists, it finds the package and writes import as `cli "github.com/jawher/mow.cli"`

**Comment by DisposaBoy** [comment]
The latest releases just calls the `goimports` binary so it should now be fixed.
