### ISSUE TITLE
margo build failed

### ISSUE THREAD

**Issue by cyy2yjp** [DisposaBoy/GoSublime#814]
GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r18.02.17-2_go?.exe', 'gosublime/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\broker.go:4:2: cannot find package "bufio" in any of:
|                > 	~\go\src\bufio (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\bufio (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\bufio
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\broker.go:5:2: cannot find package "bytes" in any of:
|                > 	~\go\src\bytes (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\bytes (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\bytes
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\common.go:5:2: cannot find package "encoding/base64" in any of:
|                > 	~\go\src\encoding\base64 (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\encoding\base64 (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\encoding\base64
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\package_bin.go:4:2: cannot find package "encoding/binary" in any of:
|                > 	~\go\src\encoding\binary (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\encoding\binary (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\encoding\binary
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\broker.go:6:2: cannot find package "encoding/json" in any of:
|                > 	~\go\src\encoding\json (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\encoding\json (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\encoding\json
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\package_text.go:5:2: cannot find package "errors" in any of:
|                > 	~\go\src\errors (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\errors (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\errors
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\main.go:7:2: cannot find package "flag" in any of:
|                > 	~\go\src\flag (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\flag (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\flag
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\common.go:7:2: cannot find package "fmt" in any of:
|                > 	~\go\src\fmt (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\fmt (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\fmt
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\common.go:8:2: cannot find package "go/ast" in any of:
|                > 	~\go\src\go\ast (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\go\ast (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\go\ast
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\m_import_paths.go:5:2: cannot find package "go/build" in any of:
|                > 	~\go\src\go\build (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\go\build (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\go\build
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\common.go:9:2: cannot find package "go/parser" in any of:
|                > 	~\go\src\go\parser (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\go\parser (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\go\parser
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\common.go:10:2: cannot find package "go/printer" in any of:
|                > 	~\go\src\go\printer (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\go\printer (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\go\printer
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\m_lint.go:6:2: cannot find package "go/scanner" in any of:
|                > 	~\go\src\go\scanner (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\go\scanner (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\go\scanner
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\common.go:11:2: cannot find package "go/token" in any of:
|                > 	~\go\src\go\token (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\go\token (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\go\token
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\config.go:7:2: cannot find package "io" in any of:
|                > 	~\go\src\io (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\io (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\io
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\client.go:7:2: cannot find package "io/ioutil" in any of:
|                > 	~\go\src\io\ioutil (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\io\ioutil (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\io\ioutil
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\autocompletecontext.go:9:2: cannot find package "log" in any of:
|                > 	~\go\src\log (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\log (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\log
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\types\const.go:12:2: cannot find package "math/big" in any of:
|                > 	~\go\src\math\big (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\math\big (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\math\big
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\server.go:8:2: cannot find package "net" in any of:
|                > 	~\go\src\net (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\net (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\net
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\gocode.go:7:2: cannot find package "net/http" in any of:
|                > 	~\go\src\net\http (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\net\http (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\net\http
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\gocode.go:8:2: cannot find package "net/http/pprof" in any of:
|                > 	~\go\src\net\http\pprof (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\net\http\pprof (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\net\http\pprof
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\client.go:8:2: cannot find package "net/rpc" in any of:
|                > 	~\go\src\net\rpc (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\net\rpc (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\net\rpc
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\m_pkgdoc.go:8:2: cannot find package "net/url" in any of:
|                > 	~\go\src\net\url (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\net\url (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\net\url
|                > ..\..\..\..\GoSublime\src\gosublime\margo\meth\importpaths\importpaths.go:9:2: cannot find package "os" in any of:
|                > 	~\go\src\os (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\os (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\os
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\declcache.go:11:2: cannot find package "os/exec" in any of:
|                > 	~\go\src\os\exec (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\os\exec (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\os\exec
|                > ..\..\..\..\GoSublime\src\gosublime\cmd\margo_pkg\m_doc.go:7:2: cannot find package "path" in any of:
|                > 	~\go\src\path (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\path (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\path
|                > ..\..\..\..\GoSublime\src\gosublime\margo\filter.go:4:2: cannot find package "path/filepath" in any of:
|                > 	~\go\src\path\filepath (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\path\filepath (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\path\filepath
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\config.go:10:2: cannot find package "reflect" in any of:
|                > 	~\go\src\reflect (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\reflect (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\reflect
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\config.go:11:2: cannot find package "regexp" in any of:
|                > 	~\go\src\regexp (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\regexp (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\regexp
|                > package gosublime/cmd/margo
|                > 	imports runtime: cannot find package "runtime" in any of:
|                > 	~\go\src\runtime (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\runtime (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\runtime
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\autocompletecontext.go:13:2: cannot find package "sort" in any of:
|                > 	~\go\src\sort (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\sort (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\sort
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\client.go:11:2: cannot find package "strconv" in any of:
|                > 	~\go\src\strconv (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\strconv (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\strconv
|                > ..\..\..\..\GoSublime\src\gosublime\margo\meth\importpaths\importpaths.go:11:2: cannot find package "strings" in any of:
|                > 	~\go\src\strings (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\strings (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\strings
|                > ..\..\..\..\GoSublime\src\gosublime\margo\opts.go:5:2: cannot find package "sync" in any of:
|                > 	~\go\src\sync (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\sync (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\sync
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\os_windows.go:7:2: cannot find package "syscall" in any of:
|                > 	~\go\src\syscall (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\syscall (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\syscall
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\package_text.go:10:2: cannot find package "text/scanner" in any of:
|                > 	~\go\src\text\scanner (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\text\scanner (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\text\scanner
|                > ..\..\..\..\GoSublime\src\gosublime\margo\meth\importpaths\importpaths.go:13:2: cannot find package "time" in any of:
|                > 	~\go\src\time (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\time (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\time
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\package_bin.go:10:2: cannot find package "unicode" in any of:
|                > 	~\go\src\unicode (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\unicode (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\unicode
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\package_bin.go:11:2: cannot find package "unicode/utf8" in any of:
|                > 	~\go\src\unicode\utf8 (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\unicode\utf8 (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\unicode\utf8
|                > ..\..\..\..\GoSublime\src\gosublime\something-borrowed\gocode\os_windows.go:8:2: cannot find package "unsafe" in any of:
|                > 	~\go\src\unsafe (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\unsafe (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\unsafe
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3143
| sublime.channel: stable
|       about.ann: a18.02.17-1
|   about.version: r18.02.17-2
|         version: r18.02.17-2
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r18.02.17-2_go?.exe (missing)
|          go.exe: c:/go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C:/Users/user/go
|          GOPATH: c:/go
|           GOBIN: C:\Go\\bin
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\Windows\\system32\\cmd.exe', '/C', '${CMD}']
|    sh.bootstrap: 
|                > 	error running sh-bootstrap.go: import cycle not allowed
|                > package main
|                > 	imports encoding/json
|                > 	imports bytes
|                > 	imports errors
|                > 	imports runtime
|                > 	imports runtime/internal/atomic
|                > 	imports unsafe
|                > 	imports runtime
|                > 
|                > 	go version: `` (raw version string ``)
|                > 	shell bootstrap took 0.740s

**Comment by DisposaBoy** [comment]
I think you configured your `GOROOT` and `GOPATH` incorrectly. Typically `C:/Users/user/go` would be `GOPATH`, not `GOROOT`. You should also probably stop setting `GOROOT` and `GOBIN`.

**Comment by cyy2yjp** [comment]
@DisposaBoy thx  ,i resolve this problem,it is the GOROOT incorrectly
