### ISSUE TITLE
MarGo build failed

### ISSUE THREAD

**Issue by andyone** [DisposaBoy/GoSublime#815]
Looks like something wrong with the latest release. 

````
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r18.02.17-2_go?.exe', 'gosublime/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > gosublime/margo
|                > net
|                > gosublime/something-borrowed/types
|                > gosublime/margo/meth/importpaths
|                > crypto/x509
|                > vendor/golang_org/x/net/lex/httplex
|                > vendor/golang_org/x/net/proxy
|                > net/textproto
|                > mime/multipart
|                > crypto/tls
|                > net/http/httptrace
|                > net/http
|                > net/http/pprof
|                > net/rpc
|                > gosublime/something-borrowed/gocode
|                > gosublime/cmd/margo_pkg
|                > gosublime/cmd/margo
|                > go install gosublime/cmd/margo: open gosublime.margo_r18.02.17-2_go?.exe: The filename, directory name, or volume label syntax is incorrect.
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3143
| sublime.channel: stable
|       about.ann: a18.02.17-1
|   about.version: r18.02.17-2
|         version: r18.02.17-2
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r18.02.17-2_go?.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C:\Go\
|          GOPATH: D:\Workspace\gocode\
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\WINDOWS\\system32\\cmd.exe', '/C', '${CMD}']
|    sh.bootstrap: 
|                > 	error running gosubl/sh-bootstrap.go: "bin" ­Ґ пў«пҐвбп ў­гваҐ­­Ґ© Ё«Ё ў­Ґи­Ґ©

|                > Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.

|                > 
|                > 	go version: `` (raw version string ``)
|                > 	shell bootstrap took 0.826s
|                > 
````

**Comment by andyone** [comment]
I think I found a root of the problem. 
Package currently installed to `AppData\Roaming\Sublime Text 3\Packages\GoSublime\` but try to find and use margo in `AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin\`.

The second directory exists and empty.

**Comment by DisposaBoy** [comment]
Is `error running gosubl/sh-bootstrap.go: "bin" ­Ґ пў«пҐвбп ў­гваҐ­­Ґ© Ё«Ё ў­Ґ` the message that is printed in the Sublime Text console? or is that a copy-paste corruption?

It should've created the binary `Packages\GoSublime\bin\gosubl-sh-bootstrap.exe` and is trying to run it but for some reason it fails.

**Comment by andyone** [comment]
Yes, that message printed in the console. Also look on strange margo file name, which contains `?` symbol. Maybe some source files have wrong encoding?

**Comment by andyone** [comment]
> It should've created the binary Packages\GoSublime\bin\gosubl-sh-bootstrap.exe and is trying to run it but for some reason it fails.

No, all files created successfully (`gosubl-sh-bootstrap.exe`, `margo.sublime.exe`, `margo.exe`). But they are located in `\AppData\Roaming\Sublime Text 3\Packages\GoSublime\bin\` not in `\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin`.

**Comment by DisposaBoy** [comment]
The paths `Packages\GoSublime\bin` is correct. `Packages\User\GoSublime\windows-x64\bin` is the old directory created to work-around issues that should now be fixed in the Go compiler.

The question mark in the file name is intentional. It's replaced with the Go version when we're able to detect it, but the detection failed. This strange naming with the versions is also done in order to work around Go compiler issues from the past.

I've pushed a change to use the old method of calling `go run` while I try to reproduce this.

**Comment by andyone** [comment]
> "bin" ­Ґ пў«пҐвбп ў­гваҐ­­Ґ© Ё«Ё ў­Ґи­Ґ© Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.

This is message in CP1251 encoding (standard encoding for text in Windows with Russian interface language) and it says _"bin" is not recognized as an internal or external command_

**Comment by DisposaBoy** [comment]
Interesting. I'm not a Windows user so I assumed calling the command `bin/xxx.exe` would run it. It seems my assumption was wrong. I'm now downloading a Windows VM so I should be able to reproduce it.

**Comment by andyone** [comment]
> I've pushed a change to use the old method of calling go run while I try to reproduce this.
It helped.

I will try to find why this code doesn't work and update this issue.

**Comment by DisposaBoy** [comment]
It's trying to run the command `bin/gosubl-sh-bootstrap.exe` from inside `Packages\GoSublime`. My guess is that I need to use do `./bin/gosubl-sh-bootstrap.exe` but I'll find out soon enough.

**Comment by andyone** [comment]
I found the reason. Windows use `\` instead of `/` for paths. I think you can do something like this:
````py
if gs.os_is_windows():
  bs_fn = 'gosubl\\sh-bootstrap.go'
  bs_exe = 'bin\\gosubl-sh-bootstrap.exe'
else:
  bs_fn = 'gosubl/sh-bootstrap.go'
  bs_exe = 'bin/gosubl-sh-bootstrap.exe'

````

**Comment by DisposaBoy** [comment]
Yes that fixes it. I will push a more thorough fix laterr today or tomorrow.
