### ISSUE TITLE
margo build fail with go is not found in the %PATH%

### ISSUE THREAD

**Issue by runner-mei** [DisposaBoy/GoSublime#816]
plugins loaded
	GoSublime r18.02.17-2: gs.init()
	GoSublime r18.02.17-2: sh.init()
	GoSublime r18.02.17-2 sh: using shell env GOBIN=D:\tools\go\bin\go.exe
	GoSublime r18.02.17-2 sh: using shell env GOPATH=D:\developing\go\meijing\tpt_vendor;D:\developing\go\meijing
	GoSublime r18.02.17-2 sh: using shell env GOROOT=D:\tools\go
	GoSublime r18.02.17-2 sh: using shell env PATH=D:\tools\go\bin;D:\developing\go\meijing\tpt_vendor\bin;D:\developing\go\meijing\bin;D:\tools\go\bin\go.exe;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\runne\AppData\Local\Microsoft\WindowsApps;D:\tools\strawberry\perl\site\bin;D:\tools\strawberry\perl\bin;D:\developing\go\gometalinter;C:\Program Files\Microsoft VS Code\bin;C:\Users\runne\bin;C:\Users\runne\go\bin;C:\Go\bin
	GoSublime r18.02.17-2 sh: go version: `go1.9` (raw version string `go1.9`)
	GoSublime r18.02.17-2 sh: shell bootstrap took 0.616s
	GoSublime r18.02.17-2: margo.init()
	GoSublime r18.02.17-2: mg9.init()
	[23:39:57] margo: agent#007: starting

	** 2018-03-02 23:39:57.436809 **:
	GoSublime init r18.02.17-2 (0.000s)
	|   install margo: no
	|   install state: done
	| sublime.version: 3143
	| sublime.channel: stable
	|       about.ann: a18.02.17-1
	|   about.version: r18.02.17-2
	|         version: r18.02.17-2
	|        platform: windows-x64
	|            ~bin: D:\tools\sublime3\Data\Packages\User\GoSublime\windows-x64\bin
	|       margo.exe: ~bin\gosublime.margo_r18.02.17-2_go1.9.exe (ok)
	|          go.exe: D:\tools\go\bin\go.exe (ok)
	|      go.version: go1.9
	|          GOROOT: D:\tools\go
	|          GOPATH: D:\developing\go\meijing\tpt_vendor;D:\developing\go\meijing
	|           GOBIN: D:\tools\go\bin\go.exe
	|       set.shell: []
	|       env.shell:
	|       shell.cmd: ['C:\\WINDOWS\\system32\\cmd.exe', '/C', '${CMD}']
	|    sh.bootstrap: 
	|                > 	using shell env GOBIN=D:\tools\go\bin\go.exe
	|                > 	using shell env GOPATH=D:\developing\go\meijing\tpt_vendor;D:\developing\go\meijing
	|                > 	using shell env GOROOT=D:\tools\go
	|                > 	using shell env PATH=D:\tools\go\bin;D:\developing\go\meijing\tpt_vendor\bin;D:\developing\go\meijing\bin;D:\tools\go\bin\go.exe;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;~\AppData\Local\Microsoft\WindowsApps;D:\tools\strawberry\perl\site\bin;D:\tools\strawberry\perl\bin;D:\developing\go\gometalinter;C:\Program Files\Microsoft VS Code\bin;~\bin;~\go\bin;C:\Go\bin
	|                > 	go version: `go1.9` (raw version string `go1.9`)
	|                > 	shell bootstrap took 0.616s
	|                >
	--------------------------------

	[23:39:58] margo: agent#007: ['D:\\tools\\sublime3\\Data\\Packages\\GoSublime\\bin\\margo.exe', 'sublime', '-codec', 'msgpack']
	[23:39:58] margo: agent#007: log: run["go" "install" "-v" "-tags" "margo" "disposa.blue/margo/cmd/margo.sublime"]
	[23:39:58] margo: agent#007: log: cannot install margo.sublime: exec: "go": executable file not found in %PATH%

**Comment by DisposaBoy** [comment]
I can't reproduce this.

Are you sure you didn't accidentally overwrite the `go.exe` or something?

You've set `GOBIN` to `D:\tools\go\bin\go.exe` which is incorrect. `GOBIN` is a *directory* where binaries will be installed, instead of the default `%GOPATH%\bin`.

**Comment by runner-mei** [comment]
I fix it, becase GOROOT=f:\tools\go in project files.

			"env":
			{
				"GOPATH": "f:/developing/go/3td;f:/developing/go/meijing",
				"GOROOT": "f:/tools/go",
				"PATH": "%PATH%;d:/tools/mingw64/bin"
			}
