### ISSUE TITLE
Several stuffs stop working after the latest update to go 1.9.2

### ISSUE THREAD

**Issue by jwall149** [DisposaBoy/GoSublime#817]
1. Package completion/suggestion stop working
2. `goimports` on save

This is my Gosublime's configurations on mac.

```
GoSublime init r18.02.17-2 (0.004s)
|   install margo: no
|   install state: done
| sublime.version: 3143
| sublime.channel: stable
|       about.ann: a18.02.17-1
|   about.version: r18.02.17-2
|         version: r18.02.17-2
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r18.02.17-2_go1.9.2.exe (ok)
|          go.exe: /usr/local/Cellar/go/1.9.2/libexec/bin/go (ok)
|      go.version: go1.9.2
|          GOROOT: /usr/local/Cellar/go/1.9.2/libexec
|          GOPATH: ~/pkg/go
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']
|    sh.bootstrap: 
|                > 	using shell env GOPATH=~/pkg/go
|                > 	using shell env GOROOT=/usr/local/Cellar/go/1.9.2/libexec
```

**Comment by DisposaBoy** [comment]
Maybe check for errors in the Sublime Text console.

Also you can view your settings by pressing <kbd>cmd+.</kbd>,<kbd>cmd+5</kbd>.

Re: no autocmplete:

Check if you have completion of names inside the package you're currently editing. If you do, that indicates that maybe you just need to (re-)install your packages because gocode only works on binary (imported) packages.


Re: goimports:

If you enabled the new margo extension by pressing <kbd>cmd+.</kbd>,<kbd>cmd+x</kbd>, you need to read all the comments in the file because it comes with `gofmt` enabled by default, not `goimports`.

**Comment by jwall149** [comment]
Thanks

Confirm that after switch to `goimports`, it works.

I'm trying to find out the first problem.

Also I want to donate but can only do so Paypal, do you have any donate link?

**Comment by DisposaBoy** [comment]
Thank you :) donation links are here https://github.com/DisposaBoy/GoSublime#supporters

**Comment by jwall149** [comment]
Hmm, cannot donate from Japan, what's up with Paypal.

**Comment by jwall149** [comment]
Just add a snippet from sublime to replace package completion
```
<snippet>
    <content><![CDATA[
package ${TM_FILEPATH/.*\/(.*)\/.*/\1/g}
]]></content>
    <tabTrigger>package</tabTrigger>
    <scope>source.go, source.go</scope>
    <description>Package</description>
</snippet>

```

**Comment by DisposaBoy** [comment]
@jwall149 I think I mis-understood the original issue and thought you meant autocompletion in general as opposed to literally the `package ...` snippet.

The latest release brought that feature back. Just add `golang.Snippets,` to your list of reducers and it should start working again.

Also, (if you didn't know) pressing <kbd>ctrl+.</kbd>,<kbd>ctrl+n</kbd> will create a new `.go` file with the package line already filled for you.
