### ISSUE TITLE
The new margo implementation causes high CPU usage

### ISSUE THREAD

**Issue by agnivade** [DisposaBoy/GoSublime#819]
First of all, thanks for the great project !

When I type code, the CPU spikes up to 100% of one core to show suggestions or errors. Just wanted to let you know in case you weren't aware.

**Comment by DisposaBoy** [comment]
Needs more info.

**Comment by agnivade** [comment]
To be more precise - whenever I press save, the `plugin_host` process goes to 80-100% CPU everytime. It comes down immediately after around 1-2 secs. But there is a notable lag where the editor freezes for a very short time (1-2 secs).

**Comment by gz-c** [comment]
I'm having a similar issue with high CPU usage. The issue seems to be persistent and not related to a save event, or at least it does not return to normal once triggered by something. 

Setting `"autoinst": false` corrects the problem.  

go1.10
Tried `r18.02.17-2` and `r18.03.05-1`, both had the same problem.

**Comment by DisposaBoy** [comment]
@agnivade 

* does this only happen with the new version of margo enabled?
* did you try disabling it? just adding the usual
  
      // +build ignore
      
      package margo

   to the `margo.go` file and restarting Sublime Text should be enough
* if it only happens when new margo is enabled, what reducers do you use? have you tried disabling some or all of them?
   note that all the builtin linters (that you `Use()`d) will run when you save the file, but they shouldn't freeze the ui so file a bug if that's the case

**Comment by DisposaBoy** [comment]
@gz-c thanks for the confirmation, I'll disable `autoinst` by default

**Comment by agnivade** [comment]
Update:

Setting `autoinst` to false does not solve my issue.

I have spent some more time on this. I agree with @gz-c's observations that the issue _does_  happen consistently while typing and is not related to save.

However, I also tried disabling margo with `// +build ignore` tag. And it still did not resolve for me. :cry: 

This is my user setting - 
```
{
  "env": {
    "GOPATH": "/home/agniva/play/go",
    "GOROOT": "/usr/local/go"
  },
  "on_save": [{"cmd": "gs_comp_lint"}],
  "fmt_cmd": ["goimports"],
  "autoinst": false,
}
```

I am on 18.03.16-1

**Comment by DisposaBoy** [comment]
@agnivade 

The closest thing I could reproduce was a buffering issue that causes completion and other blocking calls to take 300ms+ to respond and I could only reproduce it by using the gocode completion from the old version of margo - this should be fixed in the latest version.

If you previously enabled the new version of margo (by pressing <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd>) then by default gocode is configured, and the new version will disable the version in the older margo.

Also, please make sure you read the comments in `margo.go` (<kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd>) because by default it comes with `gofmt` which will disable your `goimports` settings. It also makes your `on_save` setting obsolete.

**Comment by Jayflux** [comment]
Not sure if this is the right issue to mention this in, but on every startup of sublime, the whole editor blocks for a few seconds whilst Margo is starting up.

Do you have a blocking call somewhere?

**Comment by DisposaBoy** [comment]
@Jayflux it sounds like a different issue. If you can reproduce it after the latest release, open a new bug report. All lines in the Sublime Text console that mention `margo` or `GoSublime` would be helpful.

**Comment by Jayflux** [comment]
@DisposaBoy added here:
https://github.com/DisposaBoy/GoSublime/issues/821

**Comment by agnivade** [comment]
Hmm .. this has been really frustrating. This issue started happening after I started using the new version of Margo. But even after disabling margo with the build tag, it keeps on happening. I tried disabling different reducers but it doesn't seem to make a difference. 

These are the reducers I have on right now -

```go
ma.Store.Use(
		// use gocode for autocompletion
		&golang.Gocode{
			// automatically install missing packages
			// Autobuild: true,

			// autocompete packages that are not yet imported
			// this goes well with GoImports
			UnimportedPackages: true,

			// show the function parameters. this can take up a lot of space
			ShowFuncParams: true,
		},

		// check the file for syntax errors
		&golang.SyntaxCheck{},
)
```

I would request to keep this bug open for some more time while I try out a few more things.

**Comment by DisposaBoy** [comment]
@agnivade obligatory dumb questions:

* are you on the latest version which is r18.03.19-1
* did you restart Sublime Text after enabling/disabling the new version of margo or after updating GoSublime
* is the new margo actually working. if you add `DayTimeStatus,` to your reducers, the time should appear in the status bar with the `:` blinking every `1` second.
* does this only happen in `.go` files and does it happen in all of them (I could only reproduce it in files that seem to be a few kb or larger and using the old gocode)
* did you try reverting to an older version of GoSublime
* are there  any errors in the Sublime Text console
* is the agent restarting
  after starting Sublime Text, the first agent is `agent#007` and unless you saved `margo.go`, you shouldn't see that number increasing

Also 

* try disabling calltips `"calltips": false` as well
* try disabling all code completion
  * comment out the gocode reducer
  * add `"gscomplete_enabled": false,` to your GoSublime settings
* add a print statement to `mg9.bcall` function to see how long each blocking ipc call is taking
  you can find it in [Packages/GoSublime/gosubl/mg9.py#L497](https://github.com/DisposaBoy/GoSublime/blob/master/gosubl/mg9.py#L497)

  wrap the line `res, err = q.get(True, timeout)` with something like:

		_start = time.time()
		res, err = q.get(True, timeout)
		print('bcall %s %0.3fs' % (method, time.time() - _start))

**Comment by agnivade** [comment]
> are you on the latest version which is r18.03.19-1

yes
> did you restart Sublime Text after enabling/disabling the new version of margo or after updating GoSublime is the new margo actually working. if you add DayTimeStatus, to your reducers, the time should appear in the status bar with the : blinking every 1 second.

it is blinking properly.

> does this only happen in .go files and does it happen in all of them (I could only reproduce it in files that seem to be a few kb or larger and using the old gocode)

it is happening on all files.

> did you try reverting to an older version of GoSublime

no

> are there any errors in the Sublime Text console

Yes.
```
[18:48:06] margo: restarting: agent is obsolete
[18:48:06] margo: agent#011: stopping
[18:48:06] margo: agent#012: starting
[18:48:06] margo: agent#012: ['/home/agniva/.config/sublime-text-3/Packages/GoSublime/bin/margo', 'sublime', '-codec', 'msgpack']
[18:48:06] margo: agent#012: log: run["go" "install" "-v" "-tags" "margo margo_extension" "disposa.blue/margo/cmd/margo.sublime"]
[18:48:07] margo: agent#012: log: run["/home/agniva/.config/sublime-text-3/Packages/GoSublime/bin/margo.sublime" "-codec" "msgpack"]
[18:48:07] margo: agent#012: log: agent.go:129: started
[18:49:37] margo: agent#012: log: Gocode pkg: "gitlab.com/xx/xxx/xx"
[18:49:37] margo: agent#012: log: Gocode env: gocode.margoEnv{LibPath:"/usr/local/go/pkg/linux_amd64:/home/agniva/play/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/local/go", GOPATH:"/home/agniva/play/go", InstallSuffix:""}
[18:49:39] margo: aborting QueryCompletions. it did not respond in time
[18:49:48] margo: aborting QueryCompletions. it did not respond in time
[18:49:51] margo: aborting QueryCompletions. it did not respond in time
[18:49:52] margo: aborting QueryCompletions. it did not respond in time
[18:49:54] margo: aborting QueryCompletions. it did not respond in time
[18:52:01] margo: aborting QueryCompletions. it did not respond in time
[18:52:03] margo: aborting QueryCompletions. it did not respond in time
[18:52:04] margo: aborting QueryCompletions. it did not respond in time
[18:52:05] margo: aborting QueryCompletions. it did not respond in time
[18:52:06] margo: aborting QueryCompletions. it did not respond in time
[18:52:06] margo: aborting QueryCompletions. it did not respond in time
[18:52:07] margo: aborting QueryCompletions. it did not respond in time
[18:52:07] margo: aborting QueryCompletions. it did not respond in time
[18:52:09] margo: aborting QueryCompletions. it did not respond in time
[18:52:11] margo: aborting QueryCompletions. it did not respond in time
```

> is the agent restarting after starting Sublime Text, the first agent is agent#007 and unless you saved margo.go, you shouldn't see that number increasing

The agent does not restart unless I save the file. I can see the "starting margo" message everytime I update "margo.go".

I will try your suggestions.

Do the console logs help you ?

**Comment by DisposaBoy** [comment]
the `margo: aborting QueryCompletions. it did not respond in time` error suggests that maybe it's the same issue I fixed in the older version's ipc or maybe completion really is taking that long.
Unfortunately I can't reproduce the issue so the simplest suggestion I have is to try changing the ipc codec to json.

In [Packages/GoSublime//gosubl/margo_agent.py#L14](https://github.com/DisposaBoy/GoSublime/blob/master/gosubl/margo_agent.py#L14), just after `ipc_ignore_exceptions = ...` add the following, and restart Sublime Text

```
import json
ipc_codec = 'json'
ipc_dec = json.load
ipc_enc = json.dump
```

**Comment by alecthomas** [comment]
I did some more testing.

1. I see typing lag with the Margo extension enabled, even if all reducers are disabled. ie. `func Margo(ma mg.Args) {ma.Store.Use()}`
2. I see no typing lag if I use `// +build ignore` to disable the Margo extension.

**Comment by agnivade** [comment]
I probably made some mistake last time. I reinstalled GoSublime, and now adding the build ignore tag resolves the issue. 

I also played around with the codecs. If I use the json codec, I don't see the query completion errors, but the message "starting margo" does not go away somehow. If I switch to cbor, I dont see the query completion errors. But in both cases, the cpu usage still remains high.

I have also double-checked that removing the build ignore tag brings back the high CPU usage.

@alecthomas - Does this happen to you for all files ? Or just .go files ? In my case, it happens for all files.

**Comment by DisposaBoy** [comment]
@agnivade If you edit the `Debounce.__call__` function in the file [Packages/GoSublime/gosubl/margo_common.py](https://github.com/DisposaBoy/GoSublime/blob/master/gosubl/margo_common.py#L100) and add `self.cb(*args, **kwargs); return` as the very first statement, does it help?

**Comment by agnivade** [comment]
Yes !

**Comment by agnivade** [comment]
Closing this one now. But I seem to have another issue where on-save, I see a freeze for around a second. Getting some console errors too. Filing a new bug.
