### ISSUE TITLE
Importing a command in an external test .go file causes infinite recursion/full cpu usage.

### ISSUE THREAD

**Issue by dmitshur** [DisposaBoy/GoSublime#820]
Suppose there's a Go command (i.e., `package main`) with the import path `example.com/cmd/foo` that contains an external test file:

```Go
package main_test

import (
	"testing"

	foo "example.com/cmd/foo"
)

func TestBar(t *testing.T) {
	err := foo.Bar()
	if err != nil {
		t.Errorf("got error: %v", err)
	}
}
```

Merely having such a .go file open with GoSublime causes CPU usage to go to nearly full:

![image](https://user-images.githubusercontent.com/1924134/37383345-98d9f37e-271e-11e8-9d53-facb5e354c8e.png)

It seems what happens is that it thinks `example.com/cmd/foo` is a library and tries to install it, but because it's a command, it gets installed into `$GOPATH/bin` rather than in `$GOPATH/pkg`. It doesn't find it in `$GOPATH/pkg`, so it keeps trying, on and on.

My `GoSublime.sublime-settings` is pretty minimal, so I expect this would happen with default settings too:

```
{
	//"fmt_enabled": false,
	"fmt_cmd": ["goimports", "-srcdir", "$_dir"],
	"ipc_timeout": 10
}
```

**Comment by DisposaBoy** [comment]
I wasn't able to reproduce this (probably didn't try hard enough).

If this happens after an autocompletion attempt, it might be the `autoinst` feature which is triggered by the old gocode integration.

You can just disable it (`"autoinst": false,`) and see if it helps. Both are obsolete in the new version of margo.

**Comment by shurcooL** [comment]
Thanks, let me try `"autoinst": false` now. I agree with your suspicion that it's likely the culprit.

**Comment by shurcooL** [comment]
Yep, adding `"autoinst": false` to my `GoSublime.sublime-settings` fixes the problem:

![image](https://user-images.githubusercontent.com/1924134/37530774-bc819d06-2910-11e8-92ab-3177efd1d1b2.png)

The problem is resolved for me now (assuming that having `"autoinst": false` doesn't cause any other issues, but from you said, it sounds like it should not affect anything now). I'll leave the issue open for you to decide if anything more is needed to resolve the issue in the general case.

Thank you very much!

**Comment by shurcooL** [comment]
When I look at the Default Settings for GoSublime, the comment for `autoinst` is:

```
// whether or not MarGo may automatically run `go install` for packages that are missing
// when you `import`, or `autocomplete` them
"autoinst": true,
```

From what you said, it sounded like this should be obsolete, but the way it's phrased there doesn't make it sound that way.

I'm not very familiar with the old/new MarGo and if there's anything I need to do to opt into using the new one.

**Comment by DisposaBoy** [comment]
I'm way behind on the docs but the gocode integration in the new version doesn't have the auto-install feature. It instead exposes gocode's `autobuild` but both `autoinst` and `autobuild` just call `go install` which you can already do when the file is saved and as a bonus, you get linting as well. see https://github.com/disposablue/margo/blob/master/extension-example/extension-example.go#L50
