### ISSUE TITLE
GoSublime seems to be blocking on startup causing the editor to freeze

### ISSUE THREAD

**Issue by jasonwilliams** [DisposaBoy/GoSublime#821]
**OS**
OS Name	Microsoft Windows 10 Pro
Version	10.0.16299 Build 16299

**Version**
GoSublime v2018.03.16.12.07.29

**Desc**
First off, good work with GoSublime, its a great plugin.
Every time I startup Sublime Text it freezes for a few seconds then it comes back to life.
It's happened ever since i installed GoSublime, my feeling is that somewhere GoSublime is blocking the whole editor whilst starting up Go somewhere. I've attached a gif to show this, although be aware that this gif runs faster than reality so its worse than it looks. The first one is without the console, the second one is with.

**Without Console**
The bit where the highlighting stops is where the editor freezes.
![goblock](https://user-images.githubusercontent.com/936006/37617876-490d5150-2bac-11e8-84db-8aa7f74f1b5b.gif)

**With Console**
The bit where the highlighting stops is where the editor freezes.
![goblock2](https://user-images.githubusercontent.com/936006/37617887-4ced318c-2bac-11e8-9c8e-319782b6fd43.gif)

**Output**
https://gist.github.com/Jayflux/b1a9a9c010cbcb310f16819df274624c

**Comment by DisposaBoy** [comment]
Can you still reproduce this on the latest version (`18.03.19-1`)?
I can only reproduce this if the sh-bootstrap time is high and it should only be high the first time because the binary's being compiled. Look for the line `shell bootstrap took ...`

**Comment by Jayflux** [comment]
**Version**
v2018.03.23.21.03.29

@DisposaBoy its looking much better now, not had proper time to do a thorough check, but i've not noticed any lag when starting up. Good work!
