### ISSUE TITLE
autocomplete_suggest_imports doesn't have any effects (anymore)

### ISSUE THREAD

**Issue by arsham** [DisposaBoy/GoSublime#822]
Having set the following settings:
```json
{
    "env": {
        "GOPATH": "/home/arsham/Projects/Go:/usr/bin/go",
        "PATH": "/home/arsham/Projects/Go/bin:$PATH:/usr/bin",
    },
    "comp_lint_enabled": true,
    "autocomplete_suggest_imports": true,
    "ipc_timeout": 5,
    "fmt_cmd": ["goimports", "-srcdir", "$_dir"],
    "on_save": [
        {"cmd": "gs_comp_lint"},
    ],
    "comp_lint_commands": [
        {"cmd": ["go", "build", "-i"]},
        {"cmd": ["golint $_fn"], "shell": true},
        {"cmd": ["go", "vet"]},
        {"cmd": ["goconst $_dir"], "shell": true},
        {"cmd": ["usedexports $_dir"], "shell": true},
        {"cmd": ["ineffassign $_fn"], "shell": true},
    ],
}
```
By invoking completion (`fmt.|`) while fmt is not imported already, it doesn't show any suggestions. I can confirm this functionality used to work with the same settings but not anymore.

**Comment by DisposaBoy** [comment]
I don't think this setting was ever implemented in a public release. Are you sure you weren't using a fork or another plugin?

In either case, I'd encourage you to upgrade to the new version of margo. Press <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd>, which will open a copy of this file [margo.go](https://github.com/disposablue/margo/blob/master/extension-example/extension-example.go).

You can remove `"comp_lint_enabled": true,`

* [gocode's UnimportedPackages setting](https://github.com/disposablue/margo/blob/master/extension-example/extension-example.go#L33) should do the same thing


You can remove `"fmt_cmd": ["goimports", "-srcdir", "$_dir"],`

* [the GoImports reducer](https://github.com/disposablue/margo/blob/master/extension-example/extension-example.go#L24) should do the same thing

You can remove `"on_save"...` and `"comp_lint_*"`;

* [the GoInstall](https://github.com/disposablue/margo/blob/master/extension-example/extension-example.go#L54) or [the GoInstallDiscardBinaries](https://github.com/disposablue/margo/blob/master/extension-example/extension-example.go#L56) reducers should take care of your `go build`. You might need to add the `-i` flag if you're using go1.10 and want the imported packages to be installed as well e.g. `golang.GoInstall("-i")` 


* in go1.10 [the GoTest reducer](https://github.com/disposablue/margo/blob/master/extension-example/extension-example.go#L63) takes care of your `go vet` as well, with the added bonus that you can now see test failures

* for all the rest, you can just add your own linter instances e.g. (untested)

		&golang.Linter{Label: "Go/Lint", Name: "golint"},
		&golang.Linter{Label: "Go/GoConst", Name: "goconst", Args: []string{"."}},
		&golang.Linter{Label: "Go/UsedExports", Name: "usedexports", Args: []string{"."}},
		&golang.Linter{Label: "Go/IneffAssign", Name: "ineffassign", Args: []string{"-n", "."}},

**Comment by arsham** [comment]
Awesome! It also clarified a few other things.

Nope, that was the latest version installed via the Package Manager. Where is this **entry-point** documented? Does setting up the plugin have any advantages over settings via GoSublime.sublime-settings?

Cheers.

**Comment by DisposaBoy** [comment]
I'm still behind (haven't started) on documentation, but hopefully the comments in that file `margo.go` are clear enough.

This version of margo will replace the old version. I eventually want to delete as much of the Python code as possible and make GoSublime essentially not much more than a ui for margo.
