### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by fogleman** [DisposaBoy/GoSublime#823]
I feel like every other time I launch Sublime Text, GoSublime updates and wants me to restart the app, and then I get the changelog. This is worsened by the fact that I use GoSublime on multiple machines. It's gotten rather annoying.

Can there be a less frequently updated release channel with major / critical updates only? Or silent updates?

**Comment by alexkavon** [comment]
This doesn't really answer your specific needs, but checkout #818.

**Comment by DisposaBoy** [comment]
@fogleman These are the installation instructions https://github.com/DisposaBoy/GoSublime#installation

Assuming you're using Package Control, @alexkavon  already told you how to stop the automatic update madness, but here is my position on it https://github.com/DisposaBoy/GoSublime/blob/master/SUPPORT.md#package-control

**Comment by fogleman** [comment]
@DisposaBoy Great, thanks!
