### ISSUE TITLE
.go file gets syntax highlighted as "GoSublime: HTML" if named "html.go".

### ISSUE THREAD

**Issue by shurcooL** [DisposaBoy/GoSublime#825]
If among the many `.go` files, one happens to be named `html.go` (e.g., [golang.org/x/tools/present/html.go](https://github.com/golang/tools/blob/77106db15f689a60e7d4e085d967ac557b918fb2/present/html.go)), it gets highlighted as HTML despite being a normal Go file:

![image](https://user-images.githubusercontent.com/1924134/37924219-2e33faf2-30ff-11e8-99ff-18ded24be47b.png)

I suspect the culprit is:

https://github.com/DisposaBoy/GoSublime/blob/52c498ac3ab061de4dcb37482e302eaab00d77ec/syntax/GoSublime-HTML.sublime-syntax#L6

Perhaps it should be changed to ".html.go"? But I'm not familiar with the syntax used there.

**Comment by DisposaBoy** [comment]
I don't think `.html.go` would work. It also seemed like the wrong syntax entirely (the go code should be highlited correctly) so I just went ahead and removed it
