### ISSUE TITLE
 cannot find package "gosublime/cmd/margo"

### ISSUE THREAD

**Issue by ymhhh** [DisposaBoy/GoSublime#826]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/local/Cellar/go@1.8/1.8.7/libexec/bin/go', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r18.03.26-1_go1.8.7.exe', 'gosublime/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > can't load package: package gosublime/cmd/margo: cannot find package "gosublime/cmd/margo" in any of:
|                > 	/usr/local/Cellar/go@1.8/1.8.7/libexec/src/gosublime/cmd/margo (from $GOROOT)
|                > 	~/Documents/code/360/golang/src/gosublime/cmd/margo (from $GOPATH)
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3143
| sublime.channel: stable
|       about.ann: a18.03.26-1
|   about.version: r18.03.26-1
|         version: r18.03.26-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r18.03.26-1_go1.8.7.exe (missing)
|          go.exe: /usr/local/Cellar/go@1.8/1.8.7/libexec/bin/go (ok)
|      go.version: go1.8.7
|          GOROOT: /usr/local/Cellar/go@1.8/1.8.7/libexec
|          GOPATH: ~/Documents/code/360/golang
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: /bin/zsh
|       shell.cmd: ['/bin/zsh', '-l', '-c', '${CMD}']
|    sh.bootstrap: 
|                > 	using shell env GOPATH=~/Documents/code/360/golang
|                > 	using shell env GOROOT=/usr/local/Cellar/go@1.8/1.8.7/libexec
|                > 	using shell env PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/Documents/code/360/golang/bin:~/bin:~/go/bin:/usr/local/go/bin:/usr/local/opt/go/bin
|                > 	go version: `go1.8.7` (raw version string `go1.8.7`)
|                > 	shell bootstrap took 1.180s
|                >

**Comment by DisposaBoy** [comment]
If the directory `...Sublime Text 3/Packages/src/gosublime/cmd/margo` exists, my only guess is that your shell env is overriding the env vars that are passed down (i.e `GOPATH`). How are you setting your `GOPATH` (e.g. `export GOPATH...`) and in which file(s) (e.g. `~/.profile`, `~/.zsh...`)

**Comment by ParadiseDS** [comment]
> If the directory ...Sublime Text 3/Packages/src/gosublime/cmd/margo exists, my only guess is that your shell env is overriding the env vars that are passed down (i.e GOPATH). How are you setting your GOPATH (e.g. export GOPATH...) and in which file(s) (e.g. ~/.profile, ~/.zsh...)

Same problem here. Every time i restart sublime the log says margo cannot be found in my `GOPATH`/`GOROOT` and thus fail to build it. Only way to find it is to reinstall gosublime...

From the log it seems that go sublime use the same `GOPATH` as the project rather than the one in which margo exist (...Sublime Text 3/Packages/src/gosublime/cmd/margo). The `GOPATH` printed in the log is the one deduced by option `"use_gs_gopath": true,` in my sublime as I use the option to set proper GOPATH for each project. When I turn off the option `use_gs_gopath `, gosublime use the `GOPATH` defined in my ~/.bash_profile. So it seems the `GOPATH` used by the project is also used to find margo.

**Comment by DisposaBoy** [comment]
@ParadiseDS I'm not sure I understand. Are you saying the turning off `use_gs_gopath` fixes it?

I can reproduce the bug with `use_gs_gopath`, but not without it.

**Comment by ParadiseDS** [comment]
> Are you saying the turning off use_gs_gopath fixes it?

Yes, at least no error occurs in log when `use_gs_gopath` is turned off.

**Comment by DisposaBoy** [comment]
@ParadiseDS Thanks, I'll push a fix tomorrow.

@ymhhh are you using `use_gs_gopath` as well?

**Comment by ParadiseDS** [comment]
> Thanks, I'll push a fix tomorrow.

Updated to new version just now, it works like a charm!
Thanks for the quick fix
