### ISSUE TITLE
GOSublime crashes if "too many errors" returned by 'go build'.

### ISSUE THREAD

**Issue by david9991** [DisposaBoy/GoSublime#837]
GoSublime crashes if "too many errors" returned by 'go build'.
e.g.
```
$ go build
...
syntax/syntax.go:121:29: too many errors
```

**Comment by DisposaBoy** [comment]
I need some instructions on to reproduce this.

**Comment by david9991** [comment]
Log file:
[log.txt](https://github.com/DisposaBoy/GoSublime/files/2088428/log.txt)

**Comment by DisposaBoy** [comment]
Maybe it's the same issue as https://github.com/DisposaBoy/GoSublime/issues/840

Have you tried disabling other plugins to isolate the issue to GoSublime?

You can also open the Sublime Text console <kbd>ctrl+`</kbd> IIRC, and run the `go build` command from there with `import subprocess; subprocess.call(['go', 'build'])`. If that also crashes, it's almost certainly the same issue as #840 which appears to be a Sublime Text issue. To work around that you might have some luck if you downgrade Sublime Text, probably to a version less than 3170.

**Comment by david9991** [comment]
Run `import subprocess; subprocess.call(['go', 'build'])` in console doesn't crash plugin host here, just returns `1`.
<img width="1085" alt="screen shot 2018-06-12 at 8 41 08 am" src="https://user-images.githubusercontent.com/123219/41263902-622f1daa-6e1c-11e8-928b-8edb581a042f.png">

**Comment by david9991** [comment]
I have located the line 120: `out=gs.ustr(out),` in `sh.py` cause the crash.
so the output from `go build/install` crashes the plugin host, I am keep investigating on it.

**Comment by david9991** [comment]
I found when crash occur, `b.in.ReadBytes('\n')` in`func (b *Broker) accept(jobsCh chan Job) (stopLooping bool)` got EOF error. so `stopLooping = true` then the margo process exit. But I am not sure if this caused plugin_host crash.

**Comment by DisposaBoy** [comment]
Are you saying it *doesn't* crash if you replace [that line](https://github.com/DisposaBoy/GoSublime/blob/master/gosubl/sh.py#L120) with `out=out,`? that'd suggest that it's something to do with the content of the output.

Does the follow console command crash as well? `from GoSublime.gosubl import gs; import subprocess; out = subprocess.Popen(['go', 'build'], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate(); print('output:', out); print('gs.ustr:', [gs.ustr(s) for s in out])`

If it doesn't, does `from GoSublime.gosubl import sh; sh.Command(['go', 'build']).run()` or `from GoSublime.gosubl import sh; sh.go(['build'])` crash?

Can you also attach or email me (support@kuroku.io) the output?
adding the following code on line 118 will write it to `/tmp/output.log`

		with open('/tmp/output.log', 'wb') as f:
			f.write(out)



Also what's the output of `import locale; locale.getpreferredencoding()`

**Comment by DisposaBoy** [comment]
margo exiting should be normal, it exits automatically if there are any issues reading or writing to the editor to avoid processes hanging around forever when you close the editor.

**Comment by david9991** [comment]
And I tried to produce few error, without plugin crash:
```
2018/06/12 17:26:19 W {"token":"mg9.autoken.1334421f-1560-4030-9948-0b2da709d028","error":"","tag":"r18.05.19-1","data":{"Candidates":[]}}
2018/06/12 17:26:19 CALL-done
2018/06/12 17:26:19 Run end
2018/06/12 17:26:19 ERROR # pocograph.com/plcc
./plcc.go:34:34: syntax error: unexpected newline, expecting comma or )
./plcc.go:46:2: syntax error: unexpected case, expecting }
./plcc.go:48:3: syntax error: non-declaration statement outside function body
...
2018/06/12 17:26:19 CALL-done
2018/06/12 17:26:20 STOP false
2018/06/12 17:26:20 DEBUG2 {[]}
```
I keep getting stopLooping = false.

**Comment by david9991** [comment]
With some investigation, I can provide more information, but still cannot locate cause of crash:
1. `err := c.Run()` in `func (m *mSh) Call() (interface{}, string)` cause the I/O EOF in some condition maybe.
2. After crash, `def _read_stdout(proc)` in mg9.py cannot receive any output due to plugin host already crashed.
3. After `err := c.Run()` run in margo, I got `Child exit` or `Broken pipe` signal randomly.
4. `c.Run()` returns `exit status 2` when it crash.
5. I have tried exec.CommandContext() with exec.Start(), it won't crash.
6. I have tried exec.Command() with exec.Start(), it will crash.
7. I have tried exec.Command() with exec.Start() and exec.Wait() it will crash.
8. I have tried to put exec.Run() in a groutine, it will crash.
9. I have tried force to use the Response Message which sent when it crash, instead of the normal compiled message, it won't crash, so the crash may not caused by the Response Message.
10. I cannot explain why a `c.Run()` could cause os.Stdin of parent process gets I/O EOF error.
I will keep investigating on it, some more advice?

**Comment by david9991** [comment]
both 
```
from GoSublime.gosubl import gs; import subprocess; out = subprocess.Popen(['go', 'build'], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate(); print('output:', out); print('gs.ustr:', [gs.ustr(s) for s in out])
```
and 
```
If it doesn't, does from GoSublime.gosubl import sh; sh.Command(['go', 'build']).run() or from GoSublime.gosubl import sh; sh.go(['build'])
```
 doesn't crash.

**Comment by david9991** [comment]
Output of `import locale; locale.getpreferredencoding()`
```
>>> import locale; locale.getpreferredencoding()
'US-ASCII'
```

**Comment by DisposaBoy** [comment]
To be clear: if `plugin_host` crashes or you close Sublime Text, margo will exit automatically so the `EOF` might not mean anything depending on where and when you're seeing it.



* Did you try `exec.CommandContext()` with `.Run()` or at least `.Wait()`? maybe waiting is the trigger.

* Did you try the `with open('/tmp/output.log..` code I posted above? what does it output when it crashes?

* Like the other issue, I have a feeling that the process might also be receiving a signal like `SIGCHLD` or `SIGPIPE` but I don't know how to debug it on Mac. If you have `gdb` installed, you can probably get some insight by running the command `sudo gdb attach (pidof plugin_host) -ex continue`. It should show what, if any, signal the process received when it died.


Also, have you tried the [development branch](https://github.com/DisposaBoy/GoSublime/tree/development). It has a new implementation of margo that might work better if it happens to be a margo issue and not just another case of the Sublime Text bug.

**Comment by david9991** [comment]
Sorry about have no enough time to follow this issue.
I have tried your development branch, with no luck... and I'll try to continue debug this if have enough time.

**Comment by DisposaBoy** [comment]
(I'm too lazy to read through all the comments)... make sure to try downgrading Sublime Text as the current and some previous versions have a bug where certain signals in child processes will cause `plugin_host` to crash.
You can just change the version number in the download url e.g. for version `3143` use https://download.sublimetext.com/Sublime%20Text%20Build%203143.dmg
