### ISSUE TITLE
GoSublime not available in Package Control

### ISSUE THREAD

**Issue by telegrammae** [DisposaBoy/GoSublime#838]
Recently, GoSublime seems to have disappeared from Package Control's main repository. The search does not find it. Looking at the number of installations for the package at packagecontrol.io, I see that GoSublime has almost no downloads starting with May 15.

**Comment by DisposaBoy** [comment]
It should appear next time the package control cache is updated

**Comment by chiumichael** [comment]
Unavailable from Package Control again

**Comment by DisposaBoy** [comment]
@chiumichael Install instructions are here https://github.com/DisposaBoy/GoSublime#installation--support
