### ISSUE TITLE
GoSublime error: MarGo build failed Update ## 18.05.19

### ISSUE THREAD

**Issue by alejoCandamil** [DisposaBoy/GoSublime#839]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > 
|                > 
|                > cmd: `['C:\\Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r18.05.19-1_go?.exe', 'gosublime/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > gosublime/margo
|                > net
|                > gosublime/margo/meth/importpaths
|                > gosublime/something-borrowed/types
|                > crypto/x509
|                > vendor/golang_org/x/net/lex/httplex
|                > vendor/golang_org/x/net/proxy
|                > net/textproto
|                > crypto/tls
|                > net/http/httptrace
|                > net/http
|                > net/rpc
|                > gosublime/something-borrowed/gocode
|                > gosublime/cmd/margo_pkg
|                > gosublime/cmd/margo
|                > go build gosublime/cmd/margo: open gosublime.margo_r18.05.19-1_go?.exe: The filename, directory name, or volume label syntax is incorrect.
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3176
| sublime.channel: stable
|       about.ann: a18.05.19-1
|   about.version: r18.05.19-1
|         version: r18.05.19-1
|        platform: windows-x64
|            ~bin: ~\Desktop\Sublime\Data\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r18.05.19-1_go?.exe (missing)
|          go.exe: C:\Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C:\Go\
|          GOPATH: C:\Users\user/go
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\WINDOWS\\system32\\cmd.exe', '/C', '${CMD}']
|    sh.bootstrap: 
|                > 	GOPATH is not set... setting it to the default: C:\Users\user/go
|                > 	error building gosubl\sh-bootstrap.go: open ~\AppData\Local\Temp\go-build651180994\b001\exe\a.out.exe: The process cannot access the file because it is being used by another process.
|                > 
|                > 	error running bin\gosubl-sh-bootstrap.exe: "bin\gosubl-sh-bootstrap.exe" no se reconoce como un comando interno o externo,

|                > programa o archivo por lotes ejecutable.

|                > 
|                > 	using shell env GOPATH=C:\Users\user/go
|                > 	go version: `` (raw version string ``)
|                > 	shell bootstrap took 3.914s
|                >

**Comment by DisposaBoy** [comment]
I'm not a Windows user so I can only guess that maybe your antivirus or something else is accessing the temporary `.exe` after it's created, preventing the Go compiler from moving it into the correct location.
