### ISSUE TITLE
GoSublime:Go syntax highlighting pair brackets in single quotes incorrectly

### ISSUE THREAD

**Issue by kortschak** [DisposaBoy/GoSublime#860]
When a bracket is in a single quote, it is not correctly isolated from brackets outside the quote, leading to incorrect pairing of brackets and incorrect indentiation on enter.

This screen clip show incorrectly paired brackets.
![screenshot from 2018-09-11 09-55-18](https://user-images.githubusercontent.com/275221/45331913-b1fdc200-b5ac-11e8-9102-d796b99556c9.png)

**Comment by DisposaBoy** [comment]
Does the syntax from the `Go` package work for you? it fixes this bug, but last time I tried switching to it, there were bug reports about it.

You can switch to it by via <kbd>Menu > View > Syntax > Open all with current extension as... > Go</kbd>

If you disabled the `Go` package, you can find a copy in the GoSublime sub-menu <kbd>Menu > View > Syntax > Open all with current extension as... > GoSublime > `Go` or `GoSublime: Go (ST)`</kbd>.

**Comment by kortschak** [comment]
Yes, that works, as does the Go syntax in <kbd>Menu > View > Syntax > Open all with current extension as... > GoSublime > Go </kbd>. I guess I'm just wondering by the <kbd>... GoSublime: Go</kbd> does not.

**Comment by DisposaBoy** [comment]
<kbd>... > GoSublime > Go</kbd> is a copy of <kbd>... >  Go</kbd> so you can have syntax highlighting even if you disable the `Go` package. <kbd>... > GoSublime > GoSublime: Go</kbd> is based on a very old syntax highlighting from long before the `.sublime-syntax` format was created so it doesn't support nesting of blocks/groupings like `()`, `[]` or `{}` very well (or at all).

I'll switch the default `GoSublime: Go` to one based on Sublime Text's in the future.

**Comment by kortschak** [comment]
Thanks for the explanation.
