### ISSUE TITLE
git.kuroku.io/GoSublime unavailable with Internal Server Error

### ISSUE THREAD

**Issue by leonklingele** [DisposaBoy/GoSublime#861]
Not directly related to this repo, but upstream source currently fails with `500 Internal Server Error`:

```sh
$ curl -sI https://git.kuroku.io/GoSublime | head -n1
HTTP/1.1 500 Internal Server Error
```

What's the recommended origin to clone this repo from? `https://git.kuroku.io/GoSublime` (as explained in https://margo.sh/b/migrate/) or `https://github.com/DisposaBoy/GoSublime`?

**Comment by DisposaBoy** [comment]
Sorry. It's fixed now.
The recommended origins is still https://git.kuroku.io/GoSublime

**Comment by leonklingele** [comment]
Thanks, works fine now.
