### ISSUE TITLE
go 1.11 seems to have broken gocode

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [DisposaBoy/GoSublime#863]
as of go 1.10, gocode worked flawlessly. just now, after updating to go 1.11, i see it has stopped working..

no errors are in console however..

**Comment by DisposaBoy** [comment]
Which version of GoSublime are you using? If you didn't install from the `development` branch, please switch to it. See https://margo.sh/b/migrate/

**Comment by anacrolix** [comment]
I had issues with `GO111MODULE=on`.
