### ISSUE TITLE
Shift+Ctrl test

### ISSUE THREAD

**Issue by jnpa1** [DisposaBoy/GoSublime#868]
I was having problems using shift + ctrl + left click to test single functions 
removing double quotes from gstst.py on lines 85 and 87
```
cmd = ['go', 'test', '-test.run=none', '-test.bench=%s' % pat]
cmd = ['go', 'test', '-test.run=%s' % pat]
```
solved the problem for me, is that the way to go or this should be some kind of configuration?

go version go1.10.1 linux/amd64
gosublime - 63d0f2534b0e53f93059d29fd22f77b41c0cdc48

**Comment by DisposaBoy** [comment]
TBH, I forgot about this feature.
It will need to be implemented upstream in margo (gstest is going away as well).
I will fix it sometime during this week, if I get a chance.

For now you can either keep using your fix, or use the command palette <kbd>ctrl+.</kbd>,<kbd>ctrl+t</kbd>, although the UX isn't as great.
