### ISSUE TITLE
query: How to Enable auto-completing words within the same file

### ISSUE THREAD

**Issue by weichuliu** [DisposaBoy/GoSublime#871]
Hi,

In sublime, naturally, there's a smart word completion -- when auto-complete, it finds all words in the same file and use them as autocomplete candidate.

With sublime-go, though we got proper completion, but the default completion is no more.

Is there a setting I can enable both default word completion and golang completion?

**Comment by DisposaBoy** [comment]
Press <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd> to open the margo pkg and add `AllowExplicitCompletions: true,` and/or `AllowWordCompletions:     true,` to the `&golang.Gocode{...}` reducer.
Word completions are for words in the file and explicit completions are for completions defined inside `sublime-completions` files.

e.g. using https://margo.sh/s/extension-example#L80 as base:

	&golang.Gocode{
		// show the function parameters. this can take up a lot of space
		ShowFuncParams: true,

		// whether or not to include Test*, Benchmark* and Example* functions in the auto-completion list
		// gs: this replaces the `autocomplete_tests` setting
		ProposeTests: false,

		// whether or not builtin types and functions should be shown in the auto-completion list
		// gs: this replaces the `autocomplete_builtins` setting
		ProposeBuiltins: false,

		AllowExplicitCompletions: true,
		AllowWordCompletions:     true,
	},

**Comment by DisposaBoy** [comment]
How can I reproduce this?
What settings (margo, GoSublime and sublime Text) are you using and what keys are you pressing in the screen recording?

**Comment by weichuliu** [comment]
I am using Sublime Text 3 Build 3176.

For margo.go, I added two lines according to your suggestion:

```
		&golang.Gocode{
			// automatically install missing packages
			Autobuild: true,

			// autocompete packages that are not yet imported
			// this goes well with GoImports
			UnimportedPackages: true,

			// show the function parameters. this can take up a lot of space
			ShowFuncParams: true,

			AllowExplicitCompletions: true,
			AllowWordCompletions:     true,
		},
```

I don't have other customized settings for GoSublime.

In the screen shot, I simply press Tab on Line 8 and Line 9 each.
In line 8, no autocompletion is triggered so it just tabbed.
In line 9, autocompletion is triggered with `.` and I can see other words such as `alongvariable` in the candidate list.

Do you need other information to reproduce?

**Comment by DisposaBoy** [comment]
I tried that and I can't reproduce the issue but I noticed that there is no gocode completion in your recording when I'd expect there to be suggestions for alongvariable` and `main()` when you type `a`.

The `.` triggering autocomplete is configured by `$Packages/GoSublime/Preferences.sublime-settings`, try commenting out the `"auto_complete_triggers...` line and see if that makes a difference.

**Comment by weichuliu** [comment]
My Preferences (I never modified):

```json
{
	"auto_complete_triggers": [ {"selector": "source.go", "characters": "."} ]
}
```

Commented it out, saved, then restarted Sublime. Still the same behavior.

I realized the word suggestion comes out sometimes (for instance after a symbol) and doesnot come out sometimes (for instance at the line beginning, or after `,`)

Since you say you can't reproduce, can you tell me what behavior is it like on your machine?

**Comment by weichuliu** [comment]
@DisposaBoy Hey, I followed the instruction and switched to development branch. Then all in a sudden, it seems to work now!

Thank you very much for your help!

**Comment by DisposaBoy** [comment]
What version were you using before?

What works as expected?

1. auto-completing `words` in the file work without `AllowExplicitCompletions` or `AllowWordCompletions`
2. or tab completion

**Comment by weichuliu** [comment]
Mine was `r18.07.22` with `go1.11`. I have no idea why package control said I have nothing to update.

Then with autocompletion of new GoSublime I realized autocompletion was totally not working.
![image](https://user-images.githubusercontent.com/1968755/46748413-7ca0dd00-ccee-11e8-88b0-cb3429516ae9.png)
As shown in screenshot, now autocompletion pops up properly and understand variables. While in the old gif it didn't understand what is `alongvariable`.

I am not sure if it's the re-installation fixed the GoSublime or the new branch, though.

**Comment by weichuliu** [comment]
I **expected** to have variables in the completion candidate list. And turned out it actually is the default behavior of GoSublime when working properly.

**Comment by DisposaBoy** [comment]
Oh!

When you originally said `word completion` I took it literally because Sublime Text offers primitive completion of words that appear in the file e.g. in your last screenshot, it would suggest `alongvariable` even though it's in a comment.

These `word completions` are often undesirable so they's disabled by default.

I sent out an update last week IIRC that should have notified users that the Package Control version is no longer supported, and how switch to the `development` branch. If you didn't see that, I'll have to investigate why not (since I don't use Package Control).

**Comment by weichuliu** [comment]
Ahhh, I don't read any of the notification I think that's why I missed it :)

Personally, I hope one day GoSublime will be back to package control because it's convenient and it auto updates :)

Thanks for all the help! I will close this ticket.

**Comment by DisposaBoy** [comment]
Funny enough, users not reading the CHANGELOG and the automatic updates is the reason for this messy situation.

There is a reducer that will tell you when GoSublime is updated, but it necessarily *phones home to the mothership* so you have to opt-in to it. See https://margo.sh/b/motd/ for more details.
