### ISSUE TITLE
method Reference not showing

### ISSUE THREAD

**Issue by nkostoulas** [DisposaBoy/GoSublime#875]
Hi

I've installed this package but method Reference (when hovering) no longer shows. Am I missing something?

Thanks

**Comment by DisposaBoy** [comment]
I'm not sure what you mean by `method Reference (when hovering)`. AFAIK GoSublime doesn't show anything on hover.

**Comment by nkostoulas** [comment]
![screen shot 2018-10-24 at 16 43 24](https://user-images.githubusercontent.com/14759579/47443328-f5526f80-d7ab-11e8-8e60-ef55ebbf2326.png)

Something like this. It's not from GoSublime. I thought it might be Sublime default but maybe not. GoSublime seems to disable the above for any `.go` code.

**Comment by DisposaBoy** [comment]
I can't reproduce the issue.
I had to re-enabled the Sublime Text settings `index_exclude_patterns`, `index_files`, `show_definitions` but after (and waiting a minute for it to index the files) it seems be working as expected.

**Comment by nkostoulas** [comment]
Do you get `References:` ? With `Definitions:` it is fine.

**Comment by DisposaBoy** [comment]
Yeah I see both. I tested on the margo source code.

**Comment by nkostoulas** [comment]
Hmm this is weird. I get "References" when they refer to other projects but not when this method is used within the same project/package.

**Comment by DisposaBoy** [comment]
Does it start working again if you disable GoSublime?

**Comment by DisposaBoy** [comment]
I don't see anything that should be a problem in your settings.

Maybe try changing the file syntax:

* `GoSublime: Go (Copy)` is a copy of the official Go syntax
* `GoSublime: Go/GoSublime: Go (Recommended)` is based on the official Go syntax
* `GoSublime: Go (Deprecated)` is the old GoSublime syntax

If that doesn't work try commenting out the [on_hover](https://github.com/DisposaBoy/GoSublime/blob/development/gosubl/margo_sublime.py#L38) function in [$Packages/GoSublime/gosubl/margo_sublime.py](https://github.com/DisposaBoy/GoSublime/blob/development/gosubl/margo_sublime.py#L38). It doesn't really do anything, but it doesn't hook into the hover event.

**Comment by nkostoulas** [comment]
Sorry I was not using the development version. I've tried this and everything works. Thanks for the patience!
