### ISSUE TITLE
Close outdated issues

### ISSUE THREAD

**Issue by andyone** [DisposaBoy/GoSublime#877]
Currently, GoSublime has 228 opened issues. But a big part of them it's outdated issues (_and most of them about legacy version_). From the user side, it looks like the project has a lot of unfixed problems. I think you should close all these answered issues where is no authors activity for more than one month.

**Comment by DisposaBoy** [comment]
Good point!

I'll too a big cleanup of the issue tracker soon&trade;

I'll leave this one open as a reminder :)
