### ISSUE TITLE
ubuntu16.04+sublime Build 3176--Finnal Step didn't show up

### ISSUE THREAD

**Issue by summery91** [DisposaBoy/GoSublime#885]
![_003](https://user-images.githubusercontent.com/7277932/48550642-4b7b8400-e90e-11e8-892a-b75b6bb0305c.png)

**Comment by summery91** [comment]
https://margo.sh/b/migrate/

These instructions assume that you're inside the Sublime Text Packages directory.--------CHECK
Uninstall GoSublime------------DIDN'T INSTALL BEFORE
Run the command git clone https://margo.sh/GoSublime to install GoSublime from the development branch.------------Only clone，anything else?
Restart Sublime Text. The status bar should instruct you to press ctrl+.,ctrl+x or cmd+.,cmd+x which creates the margo extension file. Please read all comments in the file.--------Didn't show up,and press ctrl+.,ctrl+x，nothing happens

**Comment by summery91** [comment]
@DisposaBoy SOS

**Comment by summery91** [comment]
OR，are there any manual way to finish the finnal step?

**Comment by DisposaBoy** [comment]
What directory did you clone GoSublime in? After you run `git clone https://margo.sh/GoSublime`, you should have the code in a directory like `...Library.../Sublime Text.../Packages/GoSublime`. You don't need to specify the branch, the `development` branch is the default.

Also be sure to restart Sublime Text. You need to quit it with <kbd>cmd+q</kbd>, simply closing the window probably doesn't do the right thing.

**Comment by summery91** [comment]
Maybe I'm in the wrong directory.
Use `locate Packages` i find there're two path,`/home/summery91/.config/sublime-text-3/Packages/` and `/home/summery91/下载/sublime_text_3/Packages`.
And i used the second one.
No wonder when i finish clone,new style didn't match.Clone a file,while in this path there are all `*.sublime-package` files.

Trying

**Comment by summery91** [comment]
I clone in the first path,then show up https://github.com/DisposaBoy/GoSublime/issues/884 just like this

press ctrl+., ctrl+x;show up the margo.go~~~
Don't know what to do ...
Then i just press ctrl+., ctrl+x and ctrl+s again, then it works~~

Don't understand why....which one is the magic step?

Anyway,thanks a lot.....

**Comment by DisposaBoy** [comment]
The magic step would be cloning into **.config/** and saving the file.
You can always find the `Packages` directory from within Sublime Text via the menu <kbd>Preferences > Browse Packages</kbd>.

**Comment by DisposaBoy** [comment]
> So,ctrl+.,ctr+x do the clone job

Not exactly... <kbd>ctrl+.</kbd>,<kbd>ctr+x</kbd> will only open the `margo.go` configuration file.

When you save this file (<kbd>ctrl+s</kbd>), margo (the app that gives you all the autocompletion, etc.) will automatically restart - that's why it started working after you saved this file.
