### ISSUE TITLE
 can not install gosublime

### ISSUE THREAD

**Issue by xqx1568** [DisposaBoy/GoSublime#887]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C://GO\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r18.11.06-1_go?.exe', 'gosublime/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > can't load package: package gosublime/cmd/margo: cannot find package "gosublime/cmd/margo" in any of:
|                > 	C:\GO\src\gosublime\cmd\margo (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\gosublime\cmd\margo (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosublime\cmd\margo
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3176
| sublime.channel: stable
|       about.ann: a18.11.06-1
|   about.version: r18.11.06-1
|         version: r18.11.06-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r18.11.06-1_go?.exe (missing)
|          go.exe: C://GO\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C://GO
|          GOPATH: D：//go
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\Windows\\system32\\cmd.exe', '/C', '${CMD}']
|    sh.bootstrap: 
|                > 	error building gosubl\sh-bootstrap.go: go: GOPATH entry is relative; must be absolute path: "D：//go".
|                > For more details see: 'go help gopath'
|                > 
|                > 	error running bin\gosubl-sh-bootstrap.exe: 系统找不到指定的路径。

|                > 
|                > 	go version: `` (raw version string ``)
|                > 	shell bootstrap took 0.136s
|                >

**Comment by DisposaBoy** [comment]
Your `GOPATH` contains `：` which is not a colon `:`. You need to change it to `D:/go`.

**Comment by xqx1568** [comment]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['C:/Go\\bin\\go.exe', 'build', '-tags', '', '-v', '-o', 'gosublime.margo_r18.11.06-1_go?.exe', 'gosublime/cmd/margo']`
|                > stdout: `
|                > 
|                > `
|                > stderr: `
|                > can't load package: package gosublime/cmd/margo: cannot find package "gosublime/cmd/margo" in any of:
|                > 	C:\Go\src\gosublime\cmd\margo (from $GOROOT)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\gosublime\cmd\margo (from $GOPATH)
|                > 	~\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\gosublime\cmd\margo
|                > `
|                > exception: `None`
|   install state: busy
| sublime.version: 3176
| sublime.channel: stable
|       about.ann: a18.11.06-1
|   about.version: r18.11.06-1
|         version: r18.11.06-1
|        platform: windows-x64
|            ~bin: ~\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\windows-x64\bin
|       margo.exe: ~bin\gosublime.margo_r18.11.06-1_go?.exe (missing)
|          go.exe: C:/Go\bin\go.exe (ok)
|      go.version: go?
|          GOROOT: C:/Go
|          GOPATH: D:/go
|           GOBIN: (not set)
|       set.shell: []
|       env.shell: 
|       shell.cmd: ['C:\\Windows\\system32\\cmd.exe', '/C', '${CMD}']
|    sh.bootstrap: 
|                > 	error building gosubl\sh-bootstrap.go: FindFirstFile gosubl\sh-bootstrap.go: The system cannot find the path specified.
|                > 
|                > 	error running bin\gosubl-sh-bootstrap.exe: 系统找不到指定的路径。

|                > 
|                > 	go version: `` (raw version string ``)
|                > 	shell bootstrap took 0.146s
|                >

**Comment by xqx1568** [comment]
![default](https://user-images.githubusercontent.com/43669838/48712400-a41d8a80-ec48-11e8-9a52-cc7b484f94f2.png)

**Comment by xqx1568** [comment]
no ：  all :

**Comment by xqx1568** [comment]
It just look like that

**Comment by DisposaBoy** [comment]
> error building gosubl\sh-bootstrap.go: FindFirstFile gosubl\sh-bootstrap.go: The system cannot find the path specified.

I don't know why this would fail.

Does the file `AppData\Roaming\Sublime Text 3\Packages\GoSublime\gosubl\sh-bootstrap.go` exist and is it readable?

**Comment by DisposaBoy** [comment]
If you open up a command prompt inside the directory `AppData\Roaming\Sublime Text 3\Packages\GoSublime`. Can you manually run the command `go build -o bin\gosubl-sh-bootstrap.exe gosubl\sh-bootstrap.go`?

**Comment by mwf** [comment]
Hi @xqx1568

I also first encountered the same problem as you on my Mac.
I did a little debug and realised I've got a `go.mod` in my $HOME directory. It was considered as a top-level go-mod during margo build, and go tried to build in Module mode.

I deleted the $HOME/go.mod and all was fine.

**Comment by endingman** [comment]
I have the same problem.

**Comment by DisposaBoy** [comment]
@endingman what problem is that? Please open a new issue with details.
