### ISSUE TITLE
Problem for installing MargGo

### ISSUE THREAD

**Issue by nicolasdilley** [DisposaBoy/GoSublime#889]
Hello,

I have been following the installation instructions in here https://margo.sh/b/migrate/ but I can't get margo to work. I have cloned the repo in /Application/Sublime Text 3/Contents/MacOS/Packages and restarted
Sublime text 3 but it still did not work. The command cmd+.+x does not work after restarting.
Thanks in advance!

**Comment by DisposaBoy** [comment]
@nicolasdilley the correct `Packages` directory is something like `~/Library/...Sublime Text 3.../Packages`. You can find it via menu <kbd>Preferences > Browse Packages...</kbd>.

**Comment by nicolasdilley** [comment]
Works like a charm thanks !
