### ISSUE TITLE
Unable to install GoSublime on macOS

### ISSUE THREAD

**Issue by jeffpierce** [DisposaBoy/GoSublime#892]
Uninstalled the Package Control version of GoSublime.
Cloned the new one to the Packages directory.
Restarted Sublime Text 3.

Absolutely nothing happens.  No prompt for the margo stuff, no nothing.  Just like if I uninstalled the old one and then did nothing.

Any ideas?

**Comment by jeffpierce** [comment]
Never mind, it's supposed to go in the Packages directory in the user's application support directory for ST3, rather than the Packages directory in the .app.  Just in case anyone is as silly as me and didn't realize it!

**Comment by Tucanix** [comment]
For anyone on Linux:

Run
`git clone https://margo.sh/GoSublime`
In
`.config/sublime-text-3/Packages`
