### ISSUE TITLE
Herd of Git processes on save

### ISSUE THREAD

**Issue by chowey** [DisposaBoy/GoSublime#902]
I am running GoSublime behind a proxy, so it cannot access the internet. I am running on a Windows computer.

I have a project with some external imports. When I press `ctrl+S` (save), I see a herd of Git processes (16+) launch in the Task Manager. Each one uses a full CPU, causing things to grid to a halt.

These Git processes seem to keep spawning for minutes. 

I know for a fact that Git can't be succeeding, since I am behind a proxy. Is there a way to disable this behavior? What is it trying to do, anyway?

**Comment by chowey** [comment]
On second look, I don't think this is related to `ctrl+S` at all. These Git processes spawn just by *looking* at my file.

**Comment by DisposaBoy** [comment]
> I am running GoSublime behind a proxy,

How? Unless I misunderstand, GoSublime only communicates over stdin/stdout/stderr in a way that's not configurable.

> 
> I have a project with some external imports. When I press `ctrl+S` (save), I see a herd of Git processes (16+) launch in the Task Manager. Each one uses a full CPU, causing things to grid to a halt.
> 
> These Git processes seem to keep spawning for minutes.
> 
> I know for a fact that Git can't be succeeding, since I am behind a proxy. Is there a way to disable this behavior? What is it trying to do, anyway?

AFAIK, GoSublime/margo doesn't do anything that could cause this unless you have it configured to do something.

* What version of GoSublime are you using?
* What does your GoSublime/margo configuration look like?
* Maybe you have some linter running and this is triggering some bad behavior with Go modules (which are not supported) like `go install` trying to fetch stuff from the internet?

**Comment by chowey** [comment]
You are right, I am not running GoSublime "behind a proxy". My whole computer cannot access the internet, unless I route it through a proxy.

I was using the latest from:

```
git clone https://margo.sh/GoSublime
```

I reverted to an older clone of GoSublime I had, which was at 39bf06cafd. This does not have the same problem so I have been using that for now.

I am not sure the exact commit I had been using, since I have now deleted it. But it should have been the latest on the development branch, no?

In my GoSublime/margo configuration, I used the default but added `golang.GoFmt` to the list. I have no linter running. The project does have a go.mod file for Go modules. Would that do unexpected things?

**Comment by chowey** [comment]
I updated GoSublime to the latest using `git pull`. It no longer seems to have the problem!

However, earlier I was running without any Go module dependencies being cached. Now all my Go module dependencies are cached. So Go wouldn't need to do any fetches to satisfy my imports.

I'm still a bit surprised that the latest GoSublime had the problem but the earlier GoSublime did not. And yes, the earlier GoSublime was running fine without any Go module dependencies being cached.

What are the plans on Go module support?

**Comment by DisposaBoy** [comment]
> What are the plans on Go module support?

TBH, Go modules don't solve any problem that I have/had so I only work on it if it comes up as part of something through @KurokuLabs work.

Unfortunately I wasted half of last month's allotted *Open Source* time discovering https://github.com/golang/go/issues/29452 so there is currently 0 motivation to work on it. It will depend on my mood when doing other work.

**Comment by chowey** [comment]
I read through your other issue so I understand better now the forces at play.

I have not been able to reproduce the issue even by deleting my Go module cache. I don't know what I changed in my environment. But so far things are working fine.
