### ISSUE TITLE
AddUnimportedPackages: true overwrites file header on autoimport

### ISSUE THREAD

**Issue by logrusorgru** [DisposaBoy/GoSublime#904]
Automatic import overwrites file head.

```go
// Configure general auto-completion behaviour
&golang.MarGocodeCtl{
	// ...
	AddUnimportedPackages: true,
	// ...
},

```
![gosublime_autoimport_overwriting_x4](https://user-images.githubusercontent.com/4060258/50924005-5f032100-145f-11e9-84c2-623c3c189787.gif)

**Comment by DisposaBoy** [comment]
There's still at least one more edge-case left, but the main issue should be fixed now.
