### ISSUE TITLE
GoSublime Crashing Sublime Text 3: MacOS X

### ISSUE THREAD

**Issue by gyant** [DisposaBoy/GoSublime#911]
I'm running into a very strange issue with the GoSublime plugin.

Currently, my setup is a MacBook Pro connected to 2 monitors. I have the laptop up on a stand with the clamshell open so from left to right my displays are MacBook Pro display -> 24" Asus 1080p (monitor 1) -> 24" Asus 1080p (monitor 2).

When I start new instances of Sublime (using `subl`), the new application instance pops up on my MacBook Pro display. 

So, let's say I have an instance of Sublime open on monitor 1 and I want to open a new instance of Sublime for a different project than my first instance. I go to a terminal on monitor 2 and type `subl .`. 

If my MacBook Pro display has a maximized application (in this case Slack) in focus, Sublime will go completely unresponsive. I have to force quit the application and start all over again.

However, if on my MacBook Pro Display I've changed to a workspace that's not a maximized application, I can spin up as many new instances of Sublime as I want and Sublime won't seize up. 

The problem is, there's nothing in the logs to indicate any code errors. I do know, however, that if I disable the GoSublime package, this problem does not occur at all. 

Sublime Text 3 is 3.1.1
GoSublime: 66dc145664e12da349caef653d1eb9ccbc224ef8
Margo: r18.11.28-1_go1.11.5
Go: 1.11.5

Is there any additional information I can provide to help narrow down the cause of this strange behavior?

**Comment by gyant** [comment]
Thank you for the suggestions! Upgrading to the dev build changes the behavior of how new instances of Sublime start up. Instead of keeping the maximized application on-screen, it actually moves you to the workspace where the new window is created.

I'm not getting freezing anymore! Thank you very much for the assist! Issue resolved.

**Comment by seripap** [comment]
I'm having this issue as well with GoSublime 66dc145, Sublime Text 3189

Get's stuck after this command:
```
GoSublime r18.11.28-1: _before.init()
GoSublime r18.11.28-1: gs.init()
GoSublime r18.11.28-1: sh.init()
```

Works perfectly when I revert to 9be2a67
```
GoSublime r18.11.28-1: _before.init()
GoSublime r18.11.28-1: gs.init()
GoSublime r18.11.28-1: sh.init()
GoSublime r18.11.28-1 sh: using shell env GOPATH=/Users/root/go
GoSublime r18.11.28-1 sh: using shell env GOROOT=/usr/local/Cellar/go/1.11.4/libexec
...
GoSublime r18.11.28-1: margo.init()
GoSublime r18.11.28-1: mg9.init()
[21:00:29] margo: agent#007: starting
GoSublime r18.11.28-1: _after.init()

** 2019-02-05 21:00:29.661729 **:
GoSublime init r18.11.28-1 (0.009s)
```

**Comment by gyant** [comment]
I actually ran into another crash today but it's happening much less infrequently. I'll give that commit hash a try and see if I get any different behavior.

**Comment by DisposaBoy** [comment]
@seripap Are you able to reliably reproduce this? the most likely cause would be https://github.com/DisposaBoy/GoSublime/commit/b1a490fe87db8de906acf9350f1fb8a93ff9ac17 but I can't really see how. Are you able to reproduce it there too?

Did you try my suggestions in https://github.com/DisposaBoy/GoSublime/issues/911#issuecomment-460567640?

**Comment by seripap** [comment]
@DisposaBoy- I did initially try killing the margo processes but Sublime was still stuck- however, changing `mg.AllLangs` to `""` seemed to have fixed the loop crash.

After margo successfully loaded, I changed it back to `mg.AllLangs`, restarted and then it seemed like it continued to boot & work afterwards. Not entirely sure why the magical 9be2a67 was working without having to do this workaround.

**Comment by gyant** [comment]
I'm not having this issue at all on 9be2a67. Not one crash for a couple weeks.

**Comment by li-ang** [comment]
Maybe I can you some reliable steps to reproducing `stuck`。

Sublime Text 3 is 3.2.0
GoSublime: 99d577a
Margo: r18.11.28-1_go1.11.5
Go: 1.11.5

```

**Comment by DisposaBoy** [comment]
Thanks @li-ang I'll give that a try this weeken.

**Comment by DisposaBoy** [comment]
The latest release (19.06.16) fix this.

**Comment by gyant** [comment]
I've confirmed this behavior is no longer present on the latest sublime and GoSublime for my workstation.

Thank you for your efforts on this! Much appreciated. :)
