### ISSUE TITLE
Code autocompletion and live lint is not working when i have one very long line in a file

### ISSUE THREAD

**Issue by lnshi** [DisposaBoy/GoSublime#920]
![image](https://user-images.githubusercontent.com/24580114/54801915-098b9180-4ca4-11e9-8baf-0a4c98ae3af1.png)

As above pic shows, when i have a very long line(line 150 contains 2804825 characters) in a go source file, then the code autocompletion and live lint will be not working for that whole file, even i wait long enough, looks it even doesn't try to work :)

What configuration can i change to make it try to work? i mean maybe respond a bit slower?

I use sublime 3 and just upgrade GoSublime from the development branch yesterday, for other cases it works very well.

**Comment by DisposaBoy** [comment]
File sizes are currently limited to 512KiB. To raise the limit to e.g. 8MiB you can change [$Packages/GoSublime/gosubl/margo_state.py#L243](https://github.com/DisposaBoy/GoSublime/blob/development/gosubl/margo_state.py#L243) from `512 << 10` to `8 << 20`. If that works and you haven't noticed any stuttering or other performance issues I will consider raising the limit permanently.

**Comment by lnshi** [comment]
@DisposaBoy I did the change, it worked, and for my laptop i feel it is totally fine, though respond a bit slower.

Processor: `2.9 GHz Intel Core i7`

**Comment by DisposaBoy** [comment]
This has been changed on the `next` branch and will be in a future release.
