### ISSUE TITLE
MacOS Freezing And Crashing: If System set "Prefer tabs when opening documents"

### ISSUE THREAD

**Issue by pelemarse** [DisposaBoy/GoSublime#930]
If in Mac OS System Preferences --> Dock --> Prefer tabs when opening documents --> Always, then Sublime Text Freezing.
1) This bug exists only when installed GoSublime.
2) Affect GoSublime versions from last (99d577af) to (b1a490fe).
3) Sublime Text 3 (Build: 3208 Dev), (Build: 3207 Stable)
4) MacOS Versions: 10.14.4 and 10.14.5

**Comment by pelemarse** [comment]
the bug also exists if you open two windows, without "Prefer tabs when opening documents"

**Comment by mknycha** [comment]
I am using:
• Sublime Text 3: build 3207
• MacOS version: 10.14.5
• GoSublime: [99d577a](https://github.com/DisposaBoy/GoSublime/commit/99d577af9289bd5347189649e51ddedff1787f4c)
I have set up Prefer tabs when opening documents: Always, and opened two windows with sublime, but I am unable to replicate the issue.
Is it occurring when you open sublime, or only when you try to install the package?
Could you please check if [issue 911](https://github.com/DisposaBoy/GoSublime/issues/911) is not related?

**Comment by pelemarse** [comment]
**My Steps**
1. Fresh Install Sublime Text 3 (Build 3207)
2. Open Terminal `~/Library/Application Support/Sublime Text 3/Packages`
2. Install GoSublime with `git clone https://margo.sh/GoSublime`
3. Open Sublime Text, started install GoSublime, and appears file `CHANGELOG.md`
4. Press `super+.`, `super+x`
5. Appears file `margo.go`
6. Quit Sublime Text and Open Sublime Text.
7. Sublime Open with two files `CHANGELOG.md`, `margo.go`.
8. Open new tab from menu: Window->New Tab.
9. Quit Sublime Text and Open Sublime text.
10. Done. Sublime Text Freeze.

**Comment by pelemarse** [comment]
1. Fresh Install Sublime Text 3 (Build 3207) on MacOS (10.14.5)
2. Open Terminal `~/Library/Application Support/Sublime Text 3/Packages`
2. Install GoSublime with `git clone https://margo.sh/GoSublime`
3. Open Sublime Text, started install GoSublime, and appears file `CHANGELOG.md`
4. Press `super+.`, `super+x`
5. Appears file `margo.go`
6. Quit Sublime Text and Open Sublime Text.
7. Sublime Open with two files `CHANGELOG.md`, `margo.go`.
8. Open new tab from menu: Window->New Tab.
9. Quit Sublime Text and Open Sublime text.
10. Done. Sublime Text Freeze.

**Comment by DisposaBoy** [comment]
I suspect this is some kind of deadlock, but I don't see how it could happen.

I can't reproduce this on Linux even while triggering an action every 100ms and holding <kbd>ctrl+tab</kbd> to repeatedly cycle between files and occasionally switching between multiple open projects.

I've also tried upgrading Mac OS all the way the way from El Capitan -> El Capitan latest version -> High Sierra -> Mojave and wasn't able to reproduce this.

@pelemarse Did try my suggestions in https://github.com/DisposaBoy/GoSublime/commit/99d577af9289bd5347189649e51ddedff1787f4c?

**Comment by pelemarse** [comment]
No. This fix doesn't work. Only can help GoSublime revert to version (**9be2a67d** rename Go.sublime-syntax to Go-Copy.sublime-syntax as work-around for DisposaBoy/GoSublime#893).

From GoSublime version **b1a490fe ** Fix #905 to Latest **99d577af** Merge pull request #913 from y0ssar1an/development, I reproduce this bug.

![Capto_Capture 2019-06-11_07-31-58_PM](https://user-images.githubusercontent.com/29234307/59290515-65512f80-8c81-11e9-894f-9f9597a12287.png)

**Comment by pelemarse** [comment]
error occurs when there is at least one blank window without any opening file, after reopen sublime.

**Comment by pelemarse** [comment]
Sublime Text 3: Build 3208 Dev
MacOS: 10.14.5 (18F132)

1) System Preferences: Prefer tabs when opening documents: In Fullsceen Only
2) Two windows one with opened file, second empty window
3) Close sublime text with active "empty window"
4) Open sublime text, everything works fine.

![2019-06-12 02 11 54](https://user-images.githubusercontent.com/29234307/59313123-56d23a80-8cb8-11e9-9031-511489254bcb.gif)

**Comment by pelemarse** [comment]
Sublime Text 3: Build 3208 Dev
MacOS: 10.14.5 (18F132)

1. System Preferences: Prefer tabs when opening documents: In Fullsceen Only
2. Two windows one with opened file, second empty window
3. Close sublime text with active "window with file"
4. Open sublime text and application freezes.

![2019-06-12 02 14 03](https://user-images.githubusercontent.com/29234307/59313517-15428f00-8cba-11e9-8d64-7b1d6e2eb4e0.gif)

**Comment by pelemarse** [comment]
Sublime Text 3: Build 3208 Dev
MacOS: 10.14.5 (18F132)

1) System Preferences: Prefer tabs when opening documents: Always
2) Two windows (tabs) one with opened file, second empty window
3) Close sublime text with active "empty window"
4) Open sublime text, everything works fine.

![2019-06-12 02 55 59](https://user-images.githubusercontent.com/29234307/59314553-766c6180-8cbe-11e9-8c2d-51029b570c1b.gif)

**Comment by pelemarse** [comment]
Sublime Text 3: Build 3208 Dev
MacOS: 10.14.5 (18F132)

1) System Preferences: Prefer tabs when opening documents: Always
2) Two windows (tabs) one with opened file, second empty window
3) Close sublime text with active "window with file"
4) Open sublime text and application freezes.

![2019-06-12 02 57 09](https://user-images.githubusercontent.com/29234307/59314617-c64b2880-8cbe-11e9-8d22-75407c7ca0a2.gif)

**Comment by DisposaBoy** [comment]
The latest release (19.06.16) fix this.
