### ISSUE TITLE
Cursor move on tab

### ISSUE THREAD

**Issue by tleb** [DisposaBoy/GoSublime#934]
I recently took the time to properly configure GoSublime and MarGo, it works great!

I just have one issue. Let's suppose we have the following file:

```go
package main

import "fmt"

func main() {
	var foobar string
	fmt.Prin
}
```

If I press `TAB` to autocomplete `Prin`, the line will turn into `fmt.Println()` with the cursor between the parenthesis. Now, if I write `foo` and press `TAB`, the cursor will move at the end of the line and won't autocomplete foobar (which was shown in the autocomplete dialog).

1. Write `fmt.Prin` and press `TAB`;
2. The cursor is between the parenthesis;
3. Write `foo` and press `TAB`;
5. `foo` has not been autocompleted and the cursor is at the end of the line.

Is there any way to remove this cursor marker? Or at least to change its priority?

Thanks!

**Comment by DisposaBoy** [comment]
I think this is a Sublime Text issue. Maybe setting `"auto_complete_commit_on_tab": true,` will help.

**Comment by tleb** [comment]
Setting both `auto_complete_commit_on_tab` and `auto_complete_with_fields` to true solved it, thanks.
