### ISSUE TITLE
I can not use GoSublime after clone code to 'Packges' folder

### ISSUE THREAD

**Issue by thodquach** [DisposaBoy/GoSublime#938]
I have done the follow things:
1. I have "git clone https://margo.sh/GoSublime"
/Users/tho/Library/Application Support/Sublime Text 3/Packages/User/GoSublime
2. Quit and restart the Sublime
3. I can put the "command + ." to show the menu like this:
![Screen Shot 2019-07-23 at 4 23 28 PM](https://user-images.githubusercontent.com/17809804/61700083-4b1d6d80-ad66-11e9-8334-b27a4a3839cd.png)
But i saw the GoSublime did not work
When i open GoSublime setting or README.md
It shows nothings like this:
![Screen Shot 2019-07-23 at 4 25 48 PM](https://user-images.githubusercontent.com/17809804/61700280-a4859c80-ad66-11e9-9dc3-452a203ff5d2.png)
And if i copy this file from the git source, i still can not save this file because of this:
![Screen Shot 2019-07-23 at 4 32 20 PM](https://user-images.githubusercontent.com/17809804/61700911-781e5000-ad67-11e9-95dc-b75970e07214.png)
Please help me check if I done anythings wrongs
This plugin very helpful but i can not use this for now.

**Comment by DisposaBoy** [comment]
I think you installed it i the wrong place. The path should be `/Users/tho/Library/Application Support/Sublime Text 3/Packages/GoSublime` i.e. not inside *Packages/**User**/*.

**Comment by thodquach** [comment]
> I think you installed it i the wrong place. The path should be `/Users/tho/Library/Application Support/Sublime Text 3/Packages/GoSublime` i.e. not inside _Packages/**User**/_.

Tks @DisposaBoy , i have installed this plugin successfully :D :+1
