### ISSUE TITLE
GoSublime overrides .sublime-completions files

### ISSUE THREAD

**Issue by carlpett** [DisposaBoy/GoSublime#943]
I've created a .sublime-completions file with a few shortcuts for myself. However, while GoSublime is active, they aren't available.
Is it possible to retain that behaviour without recoding the snippets as `golang.SnippetFuncs` in the margo.go configuration?

**Comment by DisposaBoy** [comment]
Maybe:

		&golang.Gocode{
			AllowExplicitCompletions: true,
			// AllowWordCompletions:     true,
		},

**Comment by carlpett** [comment]
Yep, that did it. Thanks!

**Comment by carlpett** [comment]
Huh, it does not seem to work within test files, though... Expected?
