### ISSUE TITLE
Is it possible to turn off autocomplete? 

### ISSUE THREAD

**Issue by dvcrn** [DisposaBoy/GoSublime#946]
I'm using gopls for my projects and get duplicated results from SublimeGo and LSP. I'd still love to use all the other SublimeGo things though like auto-running gofmt/gimports on save, goto definition and what not. 

Is it possible to completely disable the autocomplete functionality of GoSublime?

**Comment by DisposaBoy** [comment]
For the old version, it's disabled in the default settings https://github.com/DisposaBoy/GoSublime/blob/development/GoSublime.sublime-settings#L33

For the new version (`development` or `next` branch) just delete or comment out the relevant code. E.g. from the default example https://margo.sh/s/extension-example just remove the `&golang.Gocode{...}`.

Maybe https://margo.sh/b/hello-margo/ is also useful.

**Comment by dvcrn** [comment]
Thank you!
