### ISSUE TITLE
go test  no tests to run

### ISSUE THREAD

**Issue by lobo-a** [DisposaBoy/GoSublime#947]
env：Mac OS X 10.13.5
gosublime：lastest
make a testing ,the terminal message :
[ `go test '-test.run="Test.*"'` | done ]
	testing: warning: no tests to run
	PASS
	ok  utils/crypt	0.005s

the cmd does not need single quotation marks。

**Comment by DisposaBoy** [comment]
Which version of GoSublime is that? it doesn't look like latest version.
See installation instructions here https://github.com/DisposaBoy/GoSublime#installation--support

**Comment by lobo-a** [comment]
GoSublime Sanity Check

|   install state: done
| sublime.version: 3211
| sublime.channel: stable
|       about.ann: a19.06.16-1
|   about.version: r19.06.16-1
|         version: r19.06.16-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r19.06.16-1_go1.13.1.exe (ok)

**Comment by lobo-a** [comment]
> Which version of GoSublime is that? it doesn't look like latest version.
> See installation instructions here https://github.com/DisposaBoy/GoSublime#installation--support

GoSublime Sanity Check

|   install state: done
| sublime.version: 3211
| sublime.channel: stable
|       about.ann: a19.06.16-1
|   about.version: r19.06.16-1
|         version: r19.06.16-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r19.06.16-1_go1.13.1.exe (ok)

**Comment by lobo-a** [comment]
> Which version of GoSublime is that? it doesn't look like latest version.
> See installation instructions here https://github.com/DisposaBoy/GoSublime#installation--support

gstest.py > handle_action :
                ......
                 if prefix == 'Benchmark':
			cmd = ['go', 'test', '-test.run=none', '-test.bench="%s"' % pat]
		else:
			cmd = ['go', 'test', '-test.run="%s"' % pat]
               ......

In my opinion, a string contain a string, maybe the engine does not know how to pares the parameter, so just as a string.

then corect the code :

                 ......
                 if prefix == 'Benchmark':
			cmd = ['go', 'test', '-test.run=none', '-test.bench', '%s' % pat]
		else:
			cmd = ['go', 'test', '-test.run', '%s' % pat]
               ......

It be ok....

**Comment by DisposaBoy** [comment]
I see... gstest is dead but I forgot to change the command palette entry for `GoSublime: Run Tests`. If that's how you're running the tests, use the key bindings for now: <kbd>cmd+.</kbd>,<kbd>cmd+t</kbd>.

If you've got a command or key bound to `gstest`, use the new command:

	{
		"command": "margo_user_cmds",
		"args": {"action": "QueryTestCmds"},
	},

**Comment by lobo-a** [comment]
> I see... gstest is dead but I forgot to change the command palette entry for `GoSublime: Run Tests`. If that's how you're running the tests, use the key bindings for now: cmd+.,cmd+t.
> 
> If you've got a command or key bound to `gstest`, use the new command:
> 
> ```
> {
> 	"command": "margo_user_cmds",
> 	"args": {"action": "QueryTestCmds"},
> },
> ```

TKS, got it !
