### ISSUE TITLE
cannot load github.com/nicksnyder/go-i18n/i18n

### ISSUE THREAD

**Issue by ghost** [DisposaBoy/GoSublime#958]
Hi,

Hope you are all well !

I have the following error in the sublime console each time I start it with GoSublime:

```bash
build gopkg.in/alecthomas/gometalinter.v1: cannot load github.com/nicksnyder/go-i18n/i18n: module github.com/nicksnyder/go-i18n@latest found (v2.0.3+incompatible), but does not contain package github.com/nicksnyder/go-i18n/i18n
[Finished in 19.8s with exit code 1]
```

Any way to solve this error message ?

Cheers,
X.

**Comment by DisposaBoy** [comment]
I assume this is no longer an issue?

If it is, please let me know what version of GoSublime you're using and how to reproduce this error - it looks like an error from the Go compiler.
