### ISSUE TITLE
https://api.margo.sh/motd.json doesn't know about v20.03.01 release

### ISSUE THREAD

**Issue by dmitshur** [DisposaBoy/GoSublime#964]
This is a very minor issue that I'd like to report. The MOTD message is showing up telling me that a new GoSublime release is available, but in reality I have a more recent release.

Fetching https://api.margo.sh/motd.json right now:

```
{
	"Message": "★★ New GoSublime Release ★ https://margo.sh/cl/20.2.1 ★★",
	"Error": "",
	"ANN": {
		"Tag": {
			"Y": 20,
			"M": 2,
			"D": 1,
			"N": 1
		},
		"Content": "\nThis release focuses on fixing a performance issue due to a failure to resetting all cached data prematurely.\n- Cache some files in memory to avoid re-reading from disk every time.\n- The `\u0026nodejs.PackageScripts{}` reducer now uses `yarn` instead of `npm` if the `yarn.lock` file is present."
	},
	"Tag": "20.02.01-1"
}
```

According to https://github.com/DisposaBoy/GoSublime/releases, the latest release is v20.03.01, released 6 days ago.

This causes the "new release" message to continuously show up, despite me having a newer version installed:

![image](https://user-images.githubusercontent.com/1924134/76150302-fb7e7e80-6076-11ea-9a77-3ca7878f9e17.png)

![image](https://user-images.githubusercontent.com/1924134/76150315-1c46d400-6077-11ea-9f9e-8cc8322be606.png)

**Comment by dmitshur** [comment]
The current logic in `motd.go` is to show the announcement whenever the installed GoSublime version doesn't match what's reported by the motd.json endpoint:

https://github.com/DisposaBoy/GoSublime/blob/96954d155a65112cd0d6a61c811ce7fb3029d295/src/margo.sh/mg/motd.go#L189-L190

That means it displays the message when the installed GoSublime version is either newer or older.

**Comment by DisposaBoy** [comment]
Thanks for spotting that!
The motd.json should now be fixed. I'll fix the tag check soon.

**Comment by dmitshur** [comment]
Thank you @DisposaBoy!
