### ISSUE TITLE
margo start error

### ISSUE THREAD

**Issue by zpLiuHH** [DisposaBoy/GoSublime#967]
window8+SublimeText3+go 1.14.1
console print：
[21:43:52] margo: agent#055: starting
  margo: agent#055: ['go', 'install', '-v', '-x', 'margo.sh']:
  WORK=C:\Users\liuai\AppData\Local\Temp\go-build829520754
  
[21:43:53] margo: agent#055: ['C:\\Users\\liuai\\AppData\\Roaming\\Sublime Text 3\\Packages\\GoSublime\\bin\\margo.sh.exe', 'start', 'margo.sublime', '-codec', 'msgpack']
[21:43:54] margo: agent#055: log: ``` go install -v -tags=margo margo.sh/cmd/margo.sublime ```
[21:43:55] margo: agent#055: log: press ` ctrl+. `,` ctrl+x ` to configure margo or check console for errors
[21:43:55] margo: agent#055: log: *Not* using margo extension: Error: cannot find package "margo" in any of:
[21:43:55] margo: agent#055: log: 	E:\develop\software\go\src\margo (from $GOROOT)
[21:43:55] margo: agent#055: log: 	C:\Users\liuai\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime\src\margo (from $GOPATH)
[21:43:55] margo: agent#055: log: 	C:\Users\liuai\AppData\Roaming\Sublime Text 3\Packages\GoSublime\src\margo
[21:43:55] margo: agent#055: log: agent GOPATH is C:\Users\liuai\AppData\Roaming\Sublime Text 3\Packages\User\GoSublime;C:\Users\liuai\AppData\Roaming\Sublime Text 3\Packages\GoSublime
[21:43:55] margo: agent#055: stopping

**Comment by DisposaBoy** [comment]
Does it work if you press <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd> and save the file that opens?

**Comment by zpLiuHH** [comment]
> Does it work if you press ctrl+.,ctrl+x and save the file that opens?

There was no response, and the loop started all the time.

**Comment by DisposaBoy** [comment]
If you're unsable to type those key bindings, the same command is available via the command palette by pressing <kbd>ctrl+shift+p</kbd> or menu <kbd>Tools > Command Palette...</kbd> and then start typing `GoSublime: Edit Margo Extension` in the palette that opens. Once you press enter, it should open a new file named `margo.go`.

**Comment by zpLiuHH** [comment]
> If you're unsable to type those key bindings, the same command is available via the command palette by pressing ctrl+shift+p or menu Tools > Command Palette... and then start typing `GoSublime: Edit Margo Extension` in the palette that opens. Once you press enter, it should open a new file named `margo.go`.

Thank you very much! I hit CTRL +shift+p and type GoSublime, and then select GoSublime: Edit Margo Extension. The console prints some of the Margo's load information and opens the margo.go file, finally showing that the startup was successful. Can you tell me what "GoSublime: Edit Margo Extension" does? What does this command do?

**Comment by DisposaBoy** [comment]
`Edit Margo...` opens the config file/package that margo uses. margo is the app that provides auto-completion, etc. GoSublime is just a front-end to it.

You'll need to edit the `margo.go` file that opens to configure things as you need e.g. choosing plain `go fmt` or `goimports` to do code formatting when you save a `.go` file.

After you've made your changes, just save the file and margo will automatically restart.



Sorry, the docs are poor - I know - but hopefully https://margo.sh/b/hello-margo provides a useful introduction. Otherwise feel free to ask any questions here.


BTW, in-case you didn't know. Key bindings like <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd> are what's known as `chords` in Sublime Text. You can press it by first pressing and holding `ctrl` followed by `. (dot)` and then while still holding `ctrl`, press `x`. i.e. it's like typing <kbd>ctrl+.</kbd> and then <kbd>ctrl+x</kbd> immediately afterwards.

**Comment by zpLiuHH** [comment]
> `Edit Margo...` opens the config file/package that margo uses. margo is the app that provides auto-completion, etc. GoSublime is just a front-end to it.
> 
> You'll need to edit the `margo.go` file that opens to configure things as you need e.g. choosing plain `go fmt` or `goimports` to do code formatting when you save a `.go` file.
> 
> After you've made your changes, just save the file and margo will automatically restart.
> 
> Sorry, the docs are poor - I know - but hopefully https://margo.sh/b/hello-margo provides a useful introduction. Otherwise feel free to ask any questions here.
> 
> BTW, in-case you didn't know. Key bindings like ctrl+.,ctrl+x are what's known as `chords` in Sublime Text. You can press it by first pressing and holding `ctrl` followed by `. (dot)` and then while still holding `ctrl`, press `x`. i.e. it's like typing ctrl+. and then ctrl+x immediately afterwards.

Thank you for your answer, hope GoSublime is getting better and better.
