### ISSUE TITLE
Never success config

### ISSUE THREAD

**Issue by jingyuexing** [DisposaBoy/GoSublime#968]
I'm afraid I'll never be able to get config in my life,if you ask me ,why,I will answer you,because i'm lazy,i want it can be used once installed.I just want "installed" equals "you can use". All profiles are generated by the application.This Plugin is very good, but config is too complex.None of the configurations have been successful so far.

**Comment by DisposaBoy** [comment]
I can only help if you tell me what the actual problem is.

The simplest configuration consists of:

1. pressing <kbd>ctrl+.</kbd>,<kbd>ctrl+x</kbd>
2. maybe un-commenting a line or two in the file that opens
3. pressing <kbd>ctrl+s</kbd> to save the file

**Comment by jingyuexing** [comment]
![image](https://user-images.githubusercontent.com/19589872/80698561-3fd54a80-8b0d-11ea-8721-477d713326dc.png)

**Comment by jingyuexing** [comment]
# margo.sh/vendor/github.com/urfave/cli
  Data\Packages\GoSublime\src\margo.sh\vendor\github.com\urfave\cli\fish.go:72:18: undefined: strings.Builder
  Data\Packages\GoSublime\src\margo.sh\vendor\github.com\urfave\cli\fish.go:121:18: undefined: strings.Builder
  Data\Packages\GoSublime\src\margo.sh\vendor\github.com\urfave\cli\fish.go:158:45: undefined: strings.Builder
  # margo.sh/vfs
  Data\Packages\GoSublime\src\margo.sh\vfs\meta.go:11:23: undefined: os.ModeIrregular

**Comment by DisposaBoy** [comment]
https://golang.org/pkg/strings/#Builder says the strings builder was added in `go1.10` which suggests your *Go* installation is too old. See https://github.com/DisposaBoy/GoSublime/blob/development/SUPPORT.md#go GoSublime/margo follows the official Go release support policy. i.e. we only support the current and previous versions of Go. See https://golang.org/dl/ for the latest version of Go which is at this time `go1.14.2`.

**Comment by jingyuexing** [comment]
OK,Update golang

**Comment by jingyuexing** [comment]
> https://golang.org/pkg/strings/#Builder says the strings builder was added in `go1.10` which suggests your _Go_ installation is too old. See https://github.com/DisposaBoy/GoSublime/blob/development/SUPPORT.md#go GoSublime/margo follows the official Go release support policy. i.e. we only support the current and previous versions of Go. See https://golang.org/dl/ for the latest version of Go which is at this time `go1.14.2`.

thanks! I have hope,now
