### ISSUE TITLE
Go/TypeCheck wrong issue report

### ISSUE THREAD

**Issue by arsham** [DisposaBoy/GoSublime#971]
Hi mate,

## The issue

I have enabled the `TypeCheck` reducer and I'm getting this wired gutter icon:
![screenshot2](https://user-images.githubusercontent.com/428611/83390143-3d566100-a3e9-11ea-8e3c-e536aa332f9a.png)

In the HUD:
![screenshot3](https://user-images.githubusercontent.com/428611/83390157-45160580-a3e9-11ea-8a78-0e79ff4c5c02.png)

#### More info

My project is in the `GOPATH` but gomodules are enabled (I know, but it makes the whole thing faster). 

The prometheus client is an indirect dependency:
```go
github.com/prometheus/client_golang v1.6.0 // indirect
github.com/prometheus/common v0.10.0 // indirect
```
If I remove it, the issue remains until I restart margo. If I bring the dependency back, the issue is not reported until I restart margo again. I also tried saving the file, closing the tab and opening it again, still the same effect.

## Thank you

Thanks for all the hard work for the past few years, I absolutely love this plugin.

**Comment by DisposaBoy** [comment]
Which branch are you on?
$company is taking all by time these days so I haven't had time to push a new release, unfortunately, but I made some fixes on the `next` branch that should stop reporting errors in the wrong file.
I don't think it fixes the typecheck error (which I'm trying to fix when I get time), but it should hopefully stop reporting it in the wrong place so less distracting.

**Comment by arsham** [comment]
I'm using `next` branch at the moment. This bug is a very low-priority.

**Comment by DisposaBoy** [comment]
Apparently I forgot to push the latest commits. They should now be on the `next` branch.

**Comment by arsham** [comment]
I can confirm the issue is being resolved. Thank you.

**Comment by DisposaBoy** [comment]
Thanks for confirming @arsham. I'll try and update CHANGELOG.md this weekend and push a new release.
