### ISSUE TITLE
Question: Any support to debug?

### ISSUE THREAD

**Issue by amarjeetanandsingh** [DisposaBoy/GoSublime#975]
Do we have support to debug?
It would be better if we can have support to debug without depending other plugin.

**Comment by DisposaBoy** [comment]
I don't have any plans to add support.
I'm willing to add whatever UI (GoSublime) or RPC (margo) feature is necessary to support it, but I've always found printf (and tools like profilers) to be sufficient, so I've never actually used a debugger beyond the very basics like getting a backtrace and that was for C/C++ so I'm not really the best person to add such support.

**Comment by amarjeetanandsingh** [comment]
Thanks for the response @DisposaBoy
